### PR TITLE
Update Unit/Integration tests to match DSCResouces templates. Fixes #86

### LINKED ISSUE #86: Update Unit\Integration test header code to match change in templates in DSCResource
A recent change was made to the [Tests.Template in the DSCResouce](https://github.com/PowerShell/DscResources/tree/master/Tests.Template) repository to allow unit and integration tests to be run from any folder under the tests folder.

Original Issue: https://github.com/PowerShell/DscResource.Tests/issues/24
PR to resolve: https://github.com/PowerShell/DscResources/pull/85

The templates and unit/integration tests in this repo need to be updated to match.

Also, the integration config template should also be updated with as per this Issue: https://github.com/PowerShell/DscResources/issues/83

PR to remove quotes:
https://github.com/PowerShell/DscResources/pull/84

### PR DESCRIPTION
**Pull request by PlagueHO**
This PR fixes #86.

The changes are:
1. All Unit/Integration tests header regions are updated to be able to be invoked from the DSC module root folder or from the tests folder or below.
2. Unit/Integration tests templates header region updated to match DSCResource Tests.Template header regions.
3. Bad quotes removed from around resource name in Integration_config_template.ps1

### CODE REVIEW

**Comment by TravisEz13** [comment]
It looks good to me.  I'm going to leave it open for review for a while longer for comments.  @KarolKaczmarek @tysonjhayes   Any comments?

**Comment by tysonjhayes** [comment]
Seems pretty good to me. :+1:

**Comment by TravisEz13** [comment]
Thanks for the contribution!

**Comment by PlagueHO** [comment]
A pleasure - as always. Cheers!

**Pull request merged**
