### PR TITLE
Updated xNetworkTeam to meet HQRM guidelines - Fixes #305

### LINKED ISSUE #305: Convert xNetworkTeam to HQRM and convert Exceptions to use Common Code
Work on issues:

 - #135
 - #176

### PR DESCRIPTION
**Pull request by PlagueHO**
**Pull Request (PR) description**
Updated xNetworkTeam to meet HQRM guidelines

**This Pull Request (PR) fixes the following issues:**
- Fixes #305

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [x] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [x] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xnetworking/307)

### CODE REVIEW

**Comment by johlju** [comment]
Awesome work as usual! Just minor stuff again.  :smile: 

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[Modules/xNetworking/DSCResources/MSFT_xNetworkTeam/MSFT_xNetworkTeam.psm1, line 261 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/307#-L4aSDEzDZyGhqLt4Myf:-L4aSDF-NNdlZ37U42ss:b2iycbs) ([raw file](https://github.com/powershell/xnetworking/blob/b6fc29c69ae17c63d87f702692b8563148368055/Modules/xNetworking/DSCResources/MSFT_xNetworkTeam/MSFT_xNetworkTeam.psm1#L261)):*
> ```PowerShell
> 
>         [Parameter()]
>         [ValidateSet("SwitchIndependent", "LACP", "Static")]
> ```

Single-qoutes. Throughout.

---

*[Tests/Integration/MSFT_xNetworkTeam.Integration.Tests.ps1, line 104 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/307#-L4aSraTSH0uyT3Al30N:-L4aSraTSH0uyT3Al30O:b-9mx213) ([raw file](https://github.com/powershell/xnetworking/blob/b6fc29c69ae17c63d87f702692b8563148368055/Tests/Integration/MSFT_xNetworkTeam.Integration.Tests.ps1#L104)):*
> ```PowerShell
> finally
> {
>     Remove-NetLbfoTeam `
> ```

Non-blocking: Couldn't an integration test remove the team as well? With Ensure -eq 'Absent'?

---

*[Tests/Unit/MSFT_xNetworkTeam.Tests.ps1, line 49 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/307#-L4aT4e-a_mBIplhmqyC:-L4aT4e-a_mBIplhmqyD:bjyhi80) ([raw file](https://github.com/powershell/xnetworking/blob/b6fc29c69ae17c63d87f702692b8563148368055/Tests/Unit/MSFT_xNetworkTeam.Tests.ps1#L49)):*
> $Result

`$result` lower-case 'r'. Throughout.

---

*[Tests/Unit/MSFT_xNetworkTeam.Tests.ps1, line 213 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/307#-L4aTJsBItbqUrAo1qkC:-L4aTJsBItbqUrAo1qkD:bmg4n93) ([raw file](https://github.com/powershell/xnetworking/blob/b6fc29c69ae17c63d87f702692b8563148368055/Tests/Unit/MSFT_xNetworkTeam.Tests.ps1#L213)):*
> 'absent'

'Absent' (upper 'A')

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/307#-:-L4aT_4IuFN2GcfW2J8w:b-841doz)*

**Comment by PlagueHO** [comment]
Review status: 5 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[Modules/xNetworking/DSCResources/MSFT_xNetworkTeam/MSFT_xNetworkTeam.psm1, line 261 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/307#-L4aSDEzDZyGhqLt4Myf:-L4cWPeCHszW-wcJ1MG5:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/b6fc29c69ae17c63d87f702692b8563148368055/Modules/xNetworking/DSCResources/MSFT_xNetworkTeam/MSFT_xNetworkTeam.psm1#L261)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Single-qoutes. Throughout.
</blockquote></details>

Done.

---

*[Tests/Integration/MSFT_xNetworkTeam.Integration.Tests.ps1, line 104 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/307#-L4aSraTSH0uyT3Al30N:-L4cgIDHHMBuPgF0ex0n:b-1lnmc) ([raw file](https://github.com/powershell/xnetworking/blob/b6fc29c69ae17c63d87f702692b8563148368055/Tests/Integration/MSFT_xNetworkTeam.Integration.Tests.ps1#L104)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Non-blocking: Couldn't an integration test remove the team as well? With Ensure -eq 'Absent'?
</blockquote></details>

Good idea! All done!

---

*[Tests/Unit/MSFT_xNetworkTeam.Tests.ps1, line 49 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/307#-L4aT4e-a_mBIplhmqyC:-L4cWfSqiQZ6QwXGMrJM:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/b6fc29c69ae17c63d87f702692b8563148368055/Tests/Unit/MSFT_xNetworkTeam.Tests.ps1#L49)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> $Result

`$result` lower-case 'r'. Throughout.
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xNetworkTeam.Tests.ps1, line 213 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/307#-L4aTJsBItbqUrAo1qkC:-L4cWjpzPnALEcENWny6:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/b6fc29c69ae17c63d87f702692b8563148368055/Tests/Unit/MSFT_xNetworkTeam.Tests.ps1#L213)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> 'absent'

'Absent' (upper 'A')
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/307)*

**Comment by PlagueHO** [comment]
All done! Good to go. Thanks @johlju

---

Review status: 5 of 8 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/307#-:-L4cov8CjW4j0DjlrS6o:b-ha43xe)*

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/307#-:-L4doEQ7WYKxkuwiPKx5:bnfp4nl)*

**Comment by PlagueHO** [comment]
Hi @johlju - could you sign this off again for me? I rebased after merging #302. Thank you sir!

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/307#-:-L4gllhCSUPbCHrGi7WD:bnfp4nl)*

**Comment by PlagueHO** [comment]
Thanks @johlju

**Pull request merged**
