### PR TITLE
Refactoring xHostsFile & Tests

### PR DESCRIPTION
**Pull request by tysonjhayes**
Refactoring Get-TargetResource for performance.
Added logic to ignore inline comments on host files
Adding remove and modify integration tests to cover more surface area.

Perf:
Get-TargetResource had a bit of a code smell to it, lots of piping and modifying of objects that just didn't look like it was needed. I refactored this to use a foreach loop and added an early out once it found whatever it was we were looking for.

To test this I pulled in an old hosts file from [StevenBlack/hosts](https://github.com/StevenBlack/hosts) which has about 38,000 lines in it.

Using measure-command I found it took about 4 seconds to locate a line at the bottom of the file using the existing logic.

````powershell
Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 4
Milliseconds      : 899
Ticks             : 48990607
TotalDays         : 5.67020914351852E-05
TotalHours        : 0.00136085019444444
TotalMinutes      : 0.0816510116666667
TotalSeconds      : 4.8990607
TotalMilliseconds : 4899.0607
````

Using my refactored code this drops to 907 milliseconds finding the same domain (again at the end of the file so this isn't just leveraging the early out).

````powershell
Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 907
Ticks             : 9076952
TotalDays         : 1.05057314814815E-05
TotalHours        : 0.000252137555555556
TotalMinutes      : 0.0151282533333333
TotalSeconds      : 0.9076952
TotalMilliseconds : 907.6952
````

Inline Comments:
In my testing I found the host file to contain inline comments such as:
> 0.0.0.0 s.gateway.messenger.live.com # breaks Skype GH-183

I added some logic to strip the comments allowing us to only look for the domain.

Integration tests:
I added two more tests to test modifying and removing the host file.
I also removed the 30 second sleep because it should be unneeded and just slowed down the tests.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xnetworking/181)

### CODE REVIEW

**Comment by PlagueHO** [comment]
@tysonjhayes - Wow! That is awesome dude!

I'll give this a review tomorrow though because I've run out of steam for tonight. Been a bit of a long day at the office.

**Comment by PlagueHO** [comment]
@tysonjhayes - fantastic job there pal! I really couldn't find fault except for the utterly trivial nitpicks. Let me know if they're not worth fixing and I'll merge.

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[Modules/xNetworking/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1, line 212 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/181#-KaxHY3rTMT3dsiWMP28:-KaxHY3sDrCQoh-DKvua:b4iopzk) ([raw file](https://github.com/powershell/xnetworking/blob/703edd7f505427d1a41c8fa019e0d9a954aaa062/Modules/xNetworking/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1#L212)):*
> ```PowerShell
>     )
> 
>     $allHosts = Get-Content -Path "$env:windir\System32\drivers\etc\hosts" | `
> ```

You don't need to end the line with a backtick if it already ends with a | - so backtick is not required.

---

*[Modules/xNetworking/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1, line 239 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/181#-KaxHqKXIT2slL4TE1DW:-KaxHqKYF1d7zK4WYZwT:b-49dtwv) ([raw file](https://github.com/powershell/xnetworking/blob/703edd7f505427d1a41c8fa019e0d9a954aaa062/Modules/xNetworking/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1#L239)):*
> ```PowerShell
> 
>             $result = @{
>                 Host = $array
> ```

Nitpick: Could you align the = signs?

---

*[Modules/xNetworking/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1, line 246 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/181#-KaxHuQiywem5tE9EbIR:-KaxHuQiywem5tE9EbIS:b-49dtwv) ([raw file](https://github.com/powershell/xnetworking/blob/703edd7f505427d1a41c8fa019e0d9a954aaa062/Modules/xNetworking/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1#L246)):*
> ```PowerShell
>         {
>             $result = @{
>                 Host = $data[1]
> ```

Nitpick: Could you align the = signs?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/181#-:-KaxIHE07HuHIJ-nbRY2:b-5hvz8i)*

**Comment by tysonjhayes** [comment]
Review status: 7 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[Modules/xNetworking/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1, line 212 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/181#-KaxHY3rTMT3dsiWMP28:-KbC_6cqHcwnlM-mbcDy:b-qssebl) ([raw file](https://github.com/powershell/xnetworking/blob/703edd7f505427d1a41c8fa019e0d9a954aaa062/Modules/xNetworking/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1#L212)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

You don't need to end the line with a backtick if it already ends with a | - so backtick is not required.
</blockquote></details>

fixed.

---

*[Modules/xNetworking/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1, line 239 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/181#-KaxHqKXIT2slL4TE1DW:-KbC_A9r5YTODVxmvrYr:bt2vr1b) ([raw file](https://github.com/powershell/xnetworking/blob/703edd7f505427d1a41c8fa019e0d9a954aaa062/Modules/xNetworking/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1#L239)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Nitpick: Could you align the = signs?
</blockquote></details>

Fixed.

---

*[Modules/xNetworking/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1, line 246 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/181#-KaxHuQiywem5tE9EbIR:-KbC_BCYYPJNoz1HpEC8:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/703edd7f505427d1a41c8fa019e0d9a954aaa062/Modules/xNetworking/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1#L246)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Nitpick: Could you align the = signs?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/181)*

**Comment by PlagueHO** [comment]
Nice job! Thanks @tysonjhayes :lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/181#-:-KbE0PlTLraFuaBvuk-K:bwcjwoy)*

**Pull request merged**
