### PR TITLE
Corrected style and formatting of xNetAdapterLso to meet HQRM guidelines - Fixes #294

### LINKED ISSUE #294: Convert xNetAdapterLso to HQRM and convert Exceptions to use Common Code
Work on issues:

- #135
- #176

### PR DESCRIPTION
**Pull request by PlagueHO**
**Pull Request (PR) description**
Corrected style and formatting to meet HQRM guidelines for xNetAdapterLso.

**This Pull Request (PR) fixes the following issues:**

- #294 

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [x] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [x] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

@johlju - getting close to getting xNetworking to HQRM. Would you mind reviewing?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xnetworking/295)

### CODE REVIEW

**Comment by johlju** [comment]
Reviewed 9 of 10 files at r1.
Review status: 9 of 10 files reviewed at latest revision, 5 unresolved discussions.

---

*[Modules/xNetworking/DSCResources/MSFT_xNetAdapterLso/MSFT_xNetAdapterLso.psm1, line 42 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/295#-L12R0AmDMU_MnRYIVGM:-L12R0AmDMU_MnRYIVGN:bjz3lmy) ([raw file](https://github.com/powershell/xnetworking/blob/06dca32b8e7353273b933b30e5542b9a8c904cab/Modules/xNetworking/DSCResources/MSFT_xNetAdapterLso/MSFT_xNetAdapterLso.psm1#L42)):*
> ```PowerShell
> 
>         [Parameter(Mandatory = $true)]
>         [ValidateSet("V1IPv4", "IPv4", "IPv6")]
> ```

Single quotes

---

*[Modules/xNetworking/DSCResources/MSFT_xNetAdapterLso/MSFT_xNetAdapterLso.psm1, line 123 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/295#-L12R2C6U6QptEvLHQBi:-L12R2C6U6QptEvLHQBj:bjz3lmy) ([raw file](https://github.com/powershell/xnetworking/blob/06dca32b8e7353273b933b30e5542b9a8c904cab/Modules/xNetworking/DSCResources/MSFT_xNetAdapterLso/MSFT_xNetAdapterLso.psm1#L123)):*
> ```PowerShell
> 
>         [Parameter(Mandatory = $true)]
>         [ValidateSet("V1IPv4", "IPv4", "IPv6")]
> ```

Single quotes

---

*[Modules/xNetworking/DSCResources/MSFT_xNetAdapterLso/MSFT_xNetAdapterLso.psm1, line 211 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/295#-L12R7bz80ntQUWssGj9:-L12R7bz80ntQUWssGjA:bjz3lmy) ([raw file](https://github.com/powershell/xnetworking/blob/06dca32b8e7353273b933b30e5542b9a8c904cab/Modules/xNetworking/DSCResources/MSFT_xNetAdapterLso/MSFT_xNetAdapterLso.psm1#L211)):*
> ```PowerShell
> 
>         [Parameter(Mandatory = $true)]
>         [ValidateSet("V1IPv4", "IPv4", "IPv6")]
> ```

Single quotes

---

*[Tests/Integration/MSFT_xNetAdapterBinding.Integration.Tests.ps1, line 44 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/295#-L12RlyfEge_6g4jdOKl:-L12RlyfEge_6g4jdOKm:b-ub5duw) ([raw file](https://github.com/powershell/xnetworking/blob/06dca32b8e7353273b933b30e5542b9a8c904cab/Tests/Integration/MSFT_xNetAdapterBinding.Integration.Tests.ps1#L44)):*
> ```PowerShell
>                     -Force `
>                     -ErrorAction Stop
>             } | Should Not Throw
> ```

Should this use new Pester syntax or is that another PR? Throughout.

---

*[Tests/Unit/MSFT_xNetAdapterLso.Tests.ps1, line 374 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/295#-L12SNfENTkDUb3los4T:-L12SNfENTkDUb3los4U:bxd7rab) ([raw file](https://github.com/powershell/xnetworking/blob/06dca32b8e7353273b933b30e5542b9a8c904cab/Tests/Unit/MSFT_xNetAdapterLso.Tests.ps1#L374)):*
> ```PowerShell
> 
>                 It 'Should throw an exception' {
>                     { Set-TargetResource @testAdapterNotFound } | Should Throw
> ```

Should this throw any exception? Throughout. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/295)*

**Comment by PlagueHO** [comment]
Thank you for the review @Johlju - should be good to go now! I'm planning on doing the Pester V4 syntax changes all in one big go, but I'll start making them at the same time as the HQRM too.

---

Review status: 6 of 10 files reviewed at latest revision, 5 unresolved discussions.

---

*[Modules/xNetworking/DSCResources/MSFT_xNetAdapterLso/MSFT_xNetAdapterLso.psm1, line 42 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/295#-L12R0AmDMU_MnRYIVGM:-L13iumwZwsCs3tR4g4x:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/06dca32b8e7353273b933b30e5542b9a8c904cab/Modules/xNetworking/DSCResources/MSFT_xNetAdapterLso/MSFT_xNetAdapterLso.psm1#L42)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Single quotes
</blockquote></details>

Done.

---

*[Modules/xNetworking/DSCResources/MSFT_xNetAdapterLso/MSFT_xNetAdapterLso.psm1, line 123 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/295#-L12R2C6U6QptEvLHQBi:-L13ivJ-7MwACMTbdn_u:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/06dca32b8e7353273b933b30e5542b9a8c904cab/Modules/xNetworking/DSCResources/MSFT_xNetAdapterLso/MSFT_xNetAdapterLso.psm1#L123)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Single quotes
</blockquote></details>

Done.

---

*[Modules/xNetworking/DSCResources/MSFT_xNetAdapterLso/MSFT_xNetAdapterLso.psm1, line 211 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/295#-L12R7bz80ntQUWssGj9:-L13iviBN7sWKVEBofdd:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/06dca32b8e7353273b933b30e5542b9a8c904cab/Modules/xNetworking/DSCResources/MSFT_xNetAdapterLso/MSFT_xNetAdapterLso.psm1#L211)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Single quotes
</blockquote></details>

Done.

---

*[Tests/Integration/MSFT_xNetAdapterBinding.Integration.Tests.ps1, line 44 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/295#-L12RlyfEge_6g4jdOKl:-L13jLR2c-IeSg74u3fg:b-xnhxpi) ([raw file](https://github.com/powershell/xnetworking/blob/06dca32b8e7353273b933b30e5542b9a8c904cab/Tests/Integration/MSFT_xNetAdapterBinding.Integration.Tests.ps1#L44)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Should this use new Pester syntax or is that another PR? Throughout.
</blockquote></details>

I was going to do all this in one go (issue #272) - but no harm doing it now in each one :grin:

So done.

---

*[Tests/Unit/MSFT_xNetAdapterLso.Tests.ps1, line 374 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/295#-L12SNfENTkDUb3los4T:-L13kc9nt9IbWlhXzH6e:b-o4ly33) ([raw file](https://github.com/powershell/xnetworking/blob/06dca32b8e7353273b933b30e5542b9a8c904cab/Tests/Unit/MSFT_xNetAdapterLso.Tests.ps1#L374)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Should this throw any exception? Throughout. 
</blockquote></details>

Good call! Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/295#-:-L13kwirmkWjST9cjY3_:be6rk46)*

**Comment by johlju** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Tests/Integration/MSFT_xNetAdapterBinding.Integration.Tests.ps1, line 44 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/295#-L12RlyfEge_6g4jdOKl:-L13nBJJloywxSMFIeXY:b-nf6riu) ([raw file](https://github.com/powershell/xnetworking/blob/06dca32b8e7353273b933b30e5542b9a8c904cab/Tests/Integration/MSFT_xNetAdapterBinding.Integration.Tests.ps1#L44)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

I was going to do all this in one go (issue #272) - but no harm doing it now in each one :grin:

So done.
</blockquote></details>

Didn't stick in this files. But you can do all in another PR. :)

---

*[Tests/Unit/MSFT_xNetAdapterLso.Tests.ps1, line 162 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/295#-L13nV4GCG6nw-lOcnzy:-L13nV4GCG6nw-lOcnzz:b7zmttz) ([raw file](https://github.com/powershell/xnetworking/blob/00324a0c52eafb3fb764a08d6bcd3341ca28799d/Tests/Unit/MSFT_xNetAdapterLso.Tests.ps1#L162)):*
> Should throw an exception

nitpick: 'Should throw the correct exception'. :) Throughout.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/295)*

**Comment by PlagueHO** [comment]
Review status: 8 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[Tests/Integration/MSFT_xNetAdapterBinding.Integration.Tests.ps1, line 44 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/295#-L12RlyfEge_6g4jdOKl:-L13sdNJ_AqO0qjTQ8YO:bqscv5y) ([raw file](https://github.com/powershell/xnetworking/blob/06dca32b8e7353273b933b30e5542b9a8c904cab/Tests/Integration/MSFT_xNetAdapterBinding.Integration.Tests.ps1#L44)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Didn't stick in this files. But you can do all in another PR. :)
</blockquote></details>

Doh! I did the LSO one and not the bindings one! Done :grin:

---

*[Tests/Unit/MSFT_xNetAdapterLso.Tests.ps1, line 162 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/295#-L13nV4GCG6nw-lOcnzy:-L13sK0hcuSIeCaYyY6D:b-4d8hjb) ([raw file](https://github.com/powershell/xnetworking/blob/00324a0c52eafb3fb764a08d6bcd3341ca28799d/Tests/Unit/MSFT_xNetAdapterLso.Tests.ps1#L162)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> Should throw an exception

nitpick: 'Should throw the correct exception'. :) Throughout.
</blockquote></details>

Doh! Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/295)*

**Comment by johlju** [comment]
:lgtm:

All good. Great work! :smile: 

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/295#-:-L13uujkC1xkffWmpvSl:bo0fud2)*

**Comment by PlagueHO** [comment]
Thank you again @johlju

**Pull request merged**
