### PR TITLE
Added HostsFile DSC resource

### PR DESCRIPTION
**Pull request by rchaganti**
This closes issue #8.

### CODE REVIEW

**Comment by rchaganti** [comment]
Any idea why this is failing tests?
Tests for DSC resource and Schema are passing locally. So, unable to see what is wrong in the module. 

Describing Schema Validation HostsFile
 [-] should pass Test-xDscResource 2.54s
   Exception calling "ShouldProcess" with "2" argument(s): "The method or operation is not implemented."
   at line: 2646 in C:\Users\appveyor\Documents\WindowsPowerShell\Modules\xDSCResourceDesigner\xDSCResourceDesigner.psm1
 [-] should pass Test-xDscResource 104ms
   Exception calling "ShouldProcess" with "2" argument(s): "The method or operation is not implemented."
   at line: 2646 in C:\Users\appveyor\Documents\WindowsPowerShell\Modules\xDSCResourceDesigner\xDSCResourceDesigner.psm1

**Comment by tysonjhayes** [comment]
Strangely I'm not abel to repro this exact error. However, the encoding for the file might be incorrect. I pulled it down and rank Pester and ssaw these errors.

````
Invoke-Pester .\HostsFile.Tests.ps1
Describing Schema Validation HostsFile

Confirm
Are you sure you want to perform this action?
Performing the operation "The encoding for the schema file is not supported. Convert to Unicode?" on target "D:\GitHub\tysonjhayes\xNetworking\DSCResources\HostsFile\HostsFile.schema.mof".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): n
Test-xDscSchemaEncoding : The encoding for the schema file is not supported. Please use Unicode or ASCII.
At C:\program files\windowspowershell\modules\xDSCResourceDesigner\xDSCResourceDesigner.psm1:2664 char:15
+     if (-not (Test-xDscSchemaEncoding $Schema))
+               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Test-xDscSchemaEncoding

 [-] should pass Test-xDscResource 1.16s
   Expected: {True}
   But was:  {False}
   at line: 12 in D:\GitHub\tysonjhayes\xNetworking\tests\HostsFile.Tests.ps1
   12:         $result | Should Be $true

Confirm
Are you sure you want to perform this action?
Performing the operation "The encoding for the schema file is not supported. Convert to Unicode?" on target "D:\GitHub\tysonjhayes\xNetworking\DSCResources\HostsFile\HostsFile.schema.mof".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): n
Test-xDscSchemaEncoding : The encoding for the schema file is not supported. Please use Unicode or ASCII.
At C:\program files\windowspowershell\modules\xDSCResourceDesigner\xDSCResourceDesigner.psm1:2664 char:15
+     if (-not (Test-xDscSchemaEncoding $Schema))
+               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Test-xDscSchemaEncoding

 [-] should pass Test-xDscResource 3.39s
   Expected: {True}
   But was:  {False}
   at line: 18 in D:\GitHub\tysonjhayes\xNetworking\tests\HostsFile.Tests.ps1
   18:         $result | Should Be $true
Tests completed in 4.55s
Passed: 0 Failed: 2 Skipped: 0 Pending: 0
````

Also I'm noticing that many of your files do not have an extra line break at the end of the file, so you might want to review the [StyleGuide](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and make some changes while we scratch our heads at this.

**Comment by tysonjhayes** [comment]
I'll need some help reviewing why AppVeyor is failing this as I can't repro it. That being said I'd encourage you to update the script to match the [StyleGuide](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) specifically around braces on new lines, pascal casing, and verb-noun function names.

@KarolKaczmarek @TravisEz13 can either one of you repro the failures on AppVeyor? I'm unable to reproduce this failure locally.

**Comment by rchaganti** [comment]
I will update the scripts as per the style guidelines and check-in again.

**Comment by rchaganti** [comment]
Closing this pull request. I will submit another one that follows right style guidelines and encoding.

**Pull request closed without merging**
