### PR TITLE
Corrected style and formatting to meet HQRM guidelines - Fixes #281

### LINKED ISSUE #281: Convert xNetAdapterBinding to HQRM and convert Exceptions to use Common Code
Work on issues:

- #135
- #176

### PR DESCRIPTION
**Pull request by PlagueHO**
**Pull Request (PR) description**
Corrected style and formatting to meet HQRM guidelines for xNetAdapterbinding.

**This Pull Request (PR) fixes the following issues:**
- Fixes #281

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [x] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [x] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xnetworking/282)

### CODE REVIEW

**Comment by johlju** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Tests/Unit/MSFT_xNetAdapterBinding.Tests.ps1, line 59 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/282#-KyjnT8jmxbsidcy8k3p:-KyjnT8jmxbsidcy8k3q:bv3zsdw) ([raw file](https://github.com/powershell/xnetworking/blob/834ec3ae3a6efd0bda9b58d6d867939e346d905b/Tests/Unit/MSFT_xNetAdapterBinding.Tests.ps1#L59)):*
> ```PowerShell
>         }
> 
>         $MockBindingMixed = @(
> ```

Lower-case here as well?

---

*[Tests/Unit/MSFT_xNetAdapterBinding.Tests.ps1, line 77 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/282#-KyjnW_x5YGOmwV-HxDh:-KyjnW_x5YGOmwV-HxDi:b-x9582r) ([raw file](https://github.com/powershell/xnetworking/blob/834ec3ae3a6efd0bda9b58d6d867939e346d905b/Tests/Unit/MSFT_xNetAdapterBinding.Tests.ps1#L77)):*
> $Result

Lower-case here as well. Throughout.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/282)*

**Comment by PlagueHO** [comment]
All changes done! Thanks for reviewing @Johlju

---

Review status: 6 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[Tests/Unit/MSFT_xNetAdapterBinding.Tests.ps1, line 59 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/282#-KyjnT8jmxbsidcy8k3p:-KyoR8Po6HtRi7FuZcqO:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/834ec3ae3a6efd0bda9b58d6d867939e346d905b/Tests/Unit/MSFT_xNetAdapterBinding.Tests.ps1#L59)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Lower-case here as well?
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xNetAdapterBinding.Tests.ps1, line 77 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/282#-KyjnW_x5YGOmwV-HxDh:-KyoR94soUbrNgJdw5MQ:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/834ec3ae3a6efd0bda9b58d6d867939e346d905b/Tests/Unit/MSFT_xNetAdapterBinding.Tests.ps1#L77)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> $Result

Lower-case here as well. Throughout.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/282#-:-KyoRAKjalUPLBKgZGXF:blieylu)*

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/282#-:-Kyr4_foa3ClLiR2bAKi:bnfp4nl)*

**Comment by tysonjhayes** [comment]
Reviewed 6 of 7 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/282)*

**Pull request merged**
