### PR TITLE
Change: xNetAdapterAdvancedProperty: Add advanced properties

### LINKED ISSUE #314: Need more properties in xNetAdapterAdvancedProperty
I'm trying to set a number of NIC advanced properties that don't seem to be accepted by the code in MSFT_xNetAdapterAdvancedProperty.psm1.   I would imagine that this list is completely dependent on the network card manufacturer and which features it supports.  Is there a way to set arbitrary advanced properties that are not listed in this file or should I submit a merge request to add mine?

Here are the list i'm trying to add:
```
*DcbxMode: '2'
*EncapsulatedPacketTaskOffload: '1'
*NetworkDirect: '1'
*NumRSSQueues: '30'
*PacketDirect: '1'
*QOS: '1'
*RecvCompletionMethod: 1'
*RoceMaxFrameSize: '0'
*RscIPv4: '1'
*RssOnHostVPorts: '1'
*RssProfile: '1'
*RxIntModeration: '2'
*RxIntModerationProfile: '1'
*Sriov: '0'
*TCPUDPChecksumOffloadIPv4: '3'
*TCPUDPChecksumOffloadIPv6: '3'
*TxIntModerationProfile: '1'
*VMQ: '1'
*VMQVlanFiltering: '1'
*VlanID: '0'
```

### PR DESCRIPTION
**Pull request by BarnumD**
Add the folloing advanced properties:
"*DcbxMode","*EncapsulatedPacketTaskOffload","*NetworkDirect","*PacketDirect","*QOS","*RecvCompletionMethod","*RoceMaxFrameSize","*RscIPv4","*RssOnHostVPorts","RxIntModeration","*RxIntModerationProfile","*Sriov","*TCPUDPChecksumOffloadIPv4","*TCPUDPChecksumOffloadIPv6","*TxIntModerationProfile","*VMQ","*VMQVlanFiltering","*VlanID"

**This Pull Request (PR) fixes the following issues:**
Fixes #314 

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [x] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [ ] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [ ] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xnetworking/317)

### CODE REVIEW

**Comment by PlagueHO** [comment]
I'm not sure why the tests failed here, so I'm going to close and repoen this PR so that the tests execute again - which will hopefully fix the issue.

**Comment by PlagueHO** [comment]
Just some minor tweaks to the CHANGELOG.MD - great stuff and thank you for submitting this @BarnumD

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[CHANGELOG.md, line 12 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/317#-L6sVTRVazD-p6UxTBNB:-L6sVTRVazD-p6UxTBNC:bg8gmtw) ([raw file](https://github.com/powershell/xnetworking/blob/5565acc2823566ac2b1740611a8349be837672cc/CHANGELOG.md#L12)):*
> ```Markdown
>   - Converted exceptions to use ResourceHelper functions.
>   - Changed unit tests to output Verbose logs.
> - MSFT_xNetAdapterAdvancedProperty
> ```

Just for consistency, can you add a : to the end of this line?

---

*[CHANGELOG.md, line 13 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/317#-L6sVfKxJcdtpyk7npgc:-L6sVfKxJcdtpyk7npgd:b-tq9txq) ([raw file](https://github.com/powershell/xnetworking/blob/5565acc2823566ac2b1740611a8349be837672cc/CHANGELOG.md#L13)):*
> ```Markdown
>   - Changed unit tests to output Verbose logs.
> - MSFT_xNetAdapterAdvancedProperty
>   - Added a number of additional advanced properties.
> ```

Can you add a ` - Fixes [issue #314](https://github.com/PowerShell/xNetworking/issues/314).` to the end of this line?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/317#-:-L6sWmCWdlE59viy646t:bx60b3i)*

**Comment by BarnumD** [comment]
How's that?

**Comment by PlagueHO** [comment]
:lgtm:

Thank you very much @BarnumD - that is very much appreciated.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/317#-:-L73-IUKk2e4VS0DsUXN:b-qazgfb)*

**Pull request merged**
