### PR TITLE
Feature/lm lookup

### PR DESCRIPTION
**Pull request by raandree**
Added support for enabling / disabling LMHosts lookups using the MSFT_xNetBIOS resource.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xnetworking/189)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Thanks for @raandree! It appears you're MSFT so I'm not sure why the msftclas bot is requiring a CLA. @TravisEz13 - do you know if the bot is working correctly here?

@raandree - once my PR #186 is through I'll review your PR (at the moment I'll spend all my time reviewing my own PR :grin: ).

**Comment by TravisEz13** [comment]
@PlagueHO you can get the bot to rerun if you close and re-open the PR.  I usually do that before I contact the CLA team.

**Comment by PlagueHO** [comment]
@TravisEz13 - very handy to know! I'll remember to do that. Thanks Travis!

**Comment by PlagueHO** [comment]
Hi @Randree - can you rebase your PR onto the latest commit to xNetworking so that your PR doesn't try to undo all the recent changes? Thank you!

**Comment by raandree** [comment]
@PlagueHO , actually I have no idea how to do this. Isn't it possible to do the rebase then merging the pull request? The other option is to create a new pull reuest and close this one.

**Comment by PlagueHO** [comment]
Hi @raandree - sorry for spelling your handle wrong earlier. To be honest I'm not much good at rebasing myself - sometimes it works, sometimes I mess it up and have to start over, other times I give up and just do a '''Git Pull Upstream Dev``` to pull all the latest changes to my branch. Actually, with Rebasing most of the time it doesn't work (probably my own fault) and I give up and just recreate all my changes in a new fork. A bit of bad behaviour really :cry:

Have you taken a look at this guide: https://github.com/PowerShell/DscResources/blob/master/GettingStartedWithGitHub.md#resolve-merge-conflicts

It does help but it's a bit long winded. If you're still running into trouble, recommend trying the method of making a copy of your changed files then reforking and cloning the latest copy and then applying your changes again.

**Comment by raandree** [comment]
@PlagueHO, I will close this one and start again with a new pull request. This seems to be the easiest way.

Thanks for you help so far.

**Pull request closed without merging**
