### PR TITLE
 MSFT_xDhcpClient: Correct Style to meet HQRM and exceptions to use ResourceHelper functions - Fixes #225

### LINKED ISSUE #225: Convert xDhcpClient to HQRM and convert Exceptions to use Common Code
Work on issues:

- #135 
- #176

### PR DESCRIPTION
**Pull request by PlagueHO**
MSFT_xDhcpClient:
  - Corrected style and formatting to meet HQRM guidelines.
  - Converted exceptions to use ResourceHelper functions.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xnetworking/228)

### CODE REVIEW

**Comment by johlju** [comment]
:lgtm:

Just non-blocking comments.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Modules/xNetworking/DSCResources/MSFT_xDhcpClient/MSFT_xDhcpClient.psm1, line 38 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/228#-KoqoU7VbLSR8HpUIdhT:-KoqoU7VbLSR8HpUIdhU:b-w9jn4s) ([raw file](https://github.com/powershell/xnetworking/blob/148a23de696b2d1c88f5a5efdb899d898b7f5c36/Modules/xNetworking/DSCResources/MSFT_xDhcpClient/MSFT_xDhcpClient.psm1#L38)):*
> ```PowerShell
>         [Parameter(Mandatory = $true)]
>         [ValidateNotNullOrEmpty()]
>         [String]
> ```

Maybe you want to use [System.String]? Okay as-is too.

---

*[Modules/xNetworking/DSCResources/MSFT_xDhcpClient/MSFT_xDhcpClient.psm1, line 165 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/228#-KoqoaGiTijZuXBI46VL:-KoqoaGiTijZuXBI46VM:b6lnbdn) ([raw file](https://github.com/powershell/xnetworking/blob/148a23de696b2d1c88f5a5efdb899d898b7f5c36/Modules/xNetworking/DSCResources/MSFT_xDhcpClient/MSFT_xDhcpClient.psm1#L165)):*
> ```PowerShell
> 
>     # Flag to signal whether settings are correct
>     [Boolean] $desiredConfigurationMatch = $true
> ```

Maybe you want to use [System.Boolean]? Okay as-is too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/228#-:-KoqpY16TYxkavZq7Ut1:b-pwfn7y)*

**Comment by PlagueHO** [comment]
Thanks @johlju - all done!

---

Review status: 5 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[Modules/xNetworking/DSCResources/MSFT_xDhcpClient/MSFT_xDhcpClient.psm1, line 38 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/228#-KoqoU7VbLSR8HpUIdhT:-KosMYjqLAH8nbZe6iQq:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/148a23de696b2d1c88f5a5efdb899d898b7f5c36/Modules/xNetworking/DSCResources/MSFT_xDhcpClient/MSFT_xDhcpClient.psm1#L38)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Maybe you want to use [System.String]? Okay as-is too.
</blockquote></details>

Done.

---

*[Modules/xNetworking/DSCResources/MSFT_xDhcpClient/MSFT_xDhcpClient.psm1, line 165 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/228#-KoqoaGiTijZuXBI46VL:-KosMYGG2SOQOqUsIOJZ:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/148a23de696b2d1c88f5a5efdb899d898b7f5c36/Modules/xNetworking/DSCResources/MSFT_xDhcpClient/MSFT_xDhcpClient.psm1#L165)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Maybe you want to use [System.Boolean]? Okay as-is too.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/228#-:-KosMe1a58RKM7devumq:bqapjfz)*

**Comment by PlagueHO** [comment]
@Johlju - I will need to get you to sign off the files again though because I changed them from your comments :grin:

---

Review status: 5 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/228#-:-KosMjunoeJoTKnvBN7S:brsibpf)*

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/228#-:-KowPVKMYD_H3lOMvTRS:bnfp4nl)*

**Comment by PlagueHO** [comment]
Are you able to quickly review the README.MD again ? I had a merge conflict I needed to fix. 

---

Review status: 6 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/228#-:-KoxScyxjNprS1q7tUP3:btio605)*

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/228#-:-KoxUWhl7Kdlury0pEdw:bnfp4nl)*

**Comment by johlju** [comment]
Third times the charm, right? 😄

**Comment by PlagueHO** [comment]
Woop! Cheers @Johlju!

**Pull request merged**
