### PR TITLE
MSFT_xNetPowerManagement

### PR DESCRIPTION
**Pull request by edycus**
function Get-TargetResource
{
	[CmdletBinding()]
	[OutputType([System.Collections.Hashtable])]
	param
	(
		[parameter(Mandatory = $true)]
		[System.String]
		$AdapterType
	)

    #Write-Verbose "Use this cmdlet to deliver information about command processing."

    #Write-Debug "Use this cmdlet to write debug information while troubleshooting."
    $nic = Get-WmiObject Win32_NetworkAdapter | where {$_.AdapterType -eq $AdapterType}
    $powerMgmt = Get-WmiObject MSPower_DeviceEnable -Namespace root\wmi | where {$_.InstanceName.ToUpper().Contains($nic.PNPDeviceID)}

    $returnValue = @{
        NICPowerSavingEnable = $powerMgmt.Enable
        AdapterType = $AdapterType
    }

    $returnValue
}
#Get-TargetResource -AdapterType 'Ethernet 802.3'

function Set-TargetResource
{
	[CmdletBinding()]
	param
	(
		[parameter(Mandatory = $true)]
		[System.String]
		$AdapterType,

		[ValidateSet("Present","Absent")]
		[System.String]
		$Ensure
	)

    $nics = Get-WmiObject Win32_NetworkAdapter | where {$_.AdapterType -eq $AdapterType}
    foreach ($nic in $nics)
    {
        $powerMgmt = Get-WmiObject MSPower_DeviceEnable -Namespace root\wmi | where {$_.InstanceName.ToUpper().Contains($nic.PNPDeviceID)}
            
        If ($Ensure -eq 'Present'){
            Write-Verbose "Disabling the NIC power management setting."
            $powerMgmt.Enable = $False #Turn off PowerManagement feature
        }ELSE{
            Write-Verbose "Enabling the NIC power management setting."
            $powerMgmt.Enable = $true #Turn on PowerManagement feature
        }
            
        $powerMgmt.psbase.Put() | Out-Null
    }
}
#Set-TargetResource -AdapterType 'Ethernet 802.3'  -Ensure 'Absent'

function Test-TargetResource
{
	[CmdletBinding()]
	[OutputType([System.Boolean])]
	param
	(
		[parameter(Mandatory = $true)]
		[System.String]
		$AdapterType,

		[ValidateSet("Present","Absent")]
		[System.String]
		$Ensure
	)

    Write-Verbose "Checking to see if the power setting on the NIC for Adapter Type $AdapterType."

    #Write-Debug "Use this cmdlet to write debug information while troubleshooting."

    $nic = Get-WmiObject Win32_NetworkAdapter | where {$_.AdapterType -eq $AdapterType}
    $powerMgmt = Get-WmiObject MSPower_DeviceEnable -Namespace root\wmi | where {$_.InstanceName.ToUpper().Contains($nic.PNPDeviceID)}

    If ($Ensure -eq 'Present'){
        If ($powerMgmt.Enable -eq $false){
            Write-Verbose "NIC Power Management setting is disabled."
            $result = $true
        }ELSE{
            Write-Verbose "NIC Power Management setting is not disabled. - Disabling"
            $result = $false
        }
    }

    If ($Ensure -eq 'Absent'){
        If ($powerMgmt.Enable -eq $false) {
            Write-Verbose "NIC Power Management setting is disabled. - Enabling."
            $result = $false
        }ELSE{
            Write-Verbose "NIC Power Management setting is not disabled."
            $result = $true
        }
    }

$result
}
#Test-TargetResource -AdapterType 'Ethernet 802.3'  -Ensure 'Present'
Export-ModuleMember -Function *-TargetResource

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xnetworking/190)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Hi @edycus - This PR doesn't seem to contain any actual changes to code. Are you able to commit changes to this PR for review?

**Comment by edycus** [comment]
I am working on it now. I'll get something posted today. I had a deadline at work that took my attention.

**Comment by edycus** [comment]
function Get-TargetResource
{
	[CmdletBinding()]
	[OutputType([System.Collections.Hashtable])]
	param
	(
		[parameter(Mandatory = $true)]
		[System.String]
		$AdapterType
	)

    #Write-Verbose "Use this cmdlet to deliver information about command processing."

    #Write-Debug "Use this cmdlet to write debug information while troubleshooting."
    $nic = Get-WmiObject Win32_NetworkAdapter | where {$_.AdapterType -eq 'Ethernet 802.3'}
    $powerMgmt = Get-WmiObject MSPower_DeviceEnable -Namespace root\wmi | where {$_.InstanceName.ToUpper().Contains($nic.PNPDeviceID)}

    If ($powerMgmt.Enable -eq $true){
        $State = $False
    }ELSE{
        $State = $true
    }


    $returnValue = @{
        NICPowerSaving = $powerMgmt.Enable
        AdapterType = $AdapterType
        State = $State
    }

    $returnValue
}


function Set-TargetResource
{
	[CmdletBinding()]
	param
	(
		[parameter(Mandatory = $true)]
		[System.String]
		$AdapterType,

		[ValidateSet("Enabled","Disabled")]
		[System.String]
		$State
	)


    $nics = Get-WmiObject Win32_NetworkAdapter | where {$_.AdapterType -eq $AdapterType}
    foreach ($nic in $nics)
    {
        $powerMgmt = Get-WmiObject MSPower_DeviceEnable -Namespace root\wmi | where {$_.InstanceName.ToUpper().Contains($nic.PNPDeviceID)}
            
        If ($State -eq 'Disabled'){
            Write-Verbose "Disabling the NIC power management setting."
            $powerMgmt.Enable = $False #Turn off PowerManagement feature
        }ELSE{
            Write-Verbose "Enabling the NIC power management setting."
            $powerMgmt.Enable = $true #Turn on PowerManagement feature
        }
            
        $powerMgmt.psbase.Put() | Out-Null
    }


}


function Test-TargetResource
{
	[CmdletBinding()]
	[OutputType([System.Boolean])]
	param
	(
		[parameter(Mandatory = $true)]
		[System.String]
		$AdapterType,

		[ValidateSet("Enabled","Disabled")]
		[System.String]
		$State
	)

    Write-Verbose "Checking to see if the power setting on the NIC for Adapter Type $AdapterType."

    #Write-Debug "Use this cmdlet to write debug information while troubleshooting."

    $nic = Get-WmiObject Win32_NetworkAdapter | where {$_.AdapterType -eq 'Ethernet 802.3'}
    $powerMgmt = Get-WmiObject MSPower_DeviceEnable -Namespace root\wmi | where {$_.InstanceName.ToUpper().Contains($nic.PNPDeviceID)}

    If ($State -eq 'Disabled'){
        If ($powerMgmt.Enable -eq $false){
            Write-Verbose "NIC Power Management setting is disabled."
            $result = $true
        }ELSE{
            Write-Verbose "NIC Power Management setting is not disabled. - Disabling"
            $result = $false
        }
    }

    If ($State -eq 'Enabled'){
        If ($powerMgmt.Enable -eq $false) {
            Write-Verbose "NIC Power Management setting is disabled. - Enabling."
            $result = $false
        }ELSE{
            Write-Verbose "NIC Power Management setting is not disabled."
            $result = $true
        }
    }

$result
}


Export-ModuleMember -Function *-TargetResource

**Comment by edycus** [comment]
[ClassVersion("1.0.0.0"), FriendlyName("MSFT_xNetPowerManagement")]
class MSFT_xNetPowerManagement : OMI_BaseResource
{
	[Key, Description("Specifies the adapter Type you want to effect. Example Ethernet 802.3 for Ethernet adapters")] String AdapterType;
	[Write, Description("Specifies to Enable or Disable the power management feature of the NIC."), ValueMap{"Enabled","Disabled"}, Values{"Enabled","Disabled"}] String State;
};

**Comment by edycus** [comment]
@PlagueHO

**Comment by PlagueHO** [comment]
Sorry @edycus - I missed this somehow! The MOF looks good. Do you want to submit the new resource as a Pull Request? It will require a bit more stuff though (unit and integration tests if possible). The automated tests can be a bit tricky if you're new to it, so I can help with those if you submit the plain PR with your new resource.

**Comment by edycus** [comment]
Yes, I will submit it as a Pull request. This stuff is all new to me so any help is appreciated.  I am done for tonight so I will do it in the morning.

Eric

**Comment by edycus** [comment]
ok, I'm confused. I am not sure where to start. All the videos are saying create a fork then make changes. How do I just create a Pull request? how do I upload the files to the correct spot?

**Comment by edycus** [comment]
@PlagueHO . Any good videos or blogs to tell me what I suppose to be doing?

**Comment by PlagueHO** [comment]
Hi @edycus - The best place to start on this would be here:
https://github.com/PowerShell/DscResources/blob/master/CONTRIBUTING.md

I also did write a [blog series](https://dscottraynsford.wordpress.com/2015/12/14/creating-professional-dsc-resources-part-1/) on some of this stuff a while back - however it is a little bit out of date (but the principals still hold).

I'm happy to answer any questions you might have on the process. Everyone starts on this somewhere :grin:

**Pull request closed without merging**
