### PR TITLE
Fix xDnsClientGlobalSetting to handle search list arrays - Fixes #171

### LINKED ISSUE #171: xDnsClientGlobalSetting Test-TargetResource returns incorrect result
When you pass an array of DNS suffices to the SuffixSearchList parameter, the Test-TargetResource always returns false, even if the current suffix search order is set correctly.

### PR DESCRIPTION
**Pull request by ripclawffb**
This change is [Reviewable](https://reviewable.io/reviews/powershell/xnetworking/172)

### CODE REVIEW

**Comment by tysonjhayes** [comment]
Could you add some tests for this to confirm that its handling arrays correctly? The code change itself looks good though.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/172#-:-KZPiNjHywdcyA1KXM0L:b-wl9fqc)*

**Comment by PlagueHO** [comment]
Great catch and thank you very much for submitting the fix to this @ripclawffb.

Would you mind updating the unit tests (Tests/Unit/MSFT_xDnsClientGlobalSetting.Tests.ps1) to cover this as well? If you're not familiar with the test framework, I'm happy to give you some pointers as to what to do (it's a great skill to have).

---

Reviewed 2 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/172#-:-KZPi1GN08TW5a-U-eEz:b-7u2b6q)*

**Comment by PlagueHO** [comment]
Doh! What @tysonjhayes said! :grin:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/172#-:-KZPiW1CmnoRyDTL4ST6:b-uhjv7c)*

**Comment by tysonjhayes** [comment]
We're just on top of it tonight. :grin:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/172#-:-KZPjD8CZpQpWrm1oKIV:b-62r57i)*

**Comment by ripclawffb** [comment]
Sure, I'll take a crack at it. I've never written one before, so I'd appreciate any pointers. Thanks!

**Comment by msftgits** [comment]
Hi, I am closing and re-opening this PR to bump the CLA bot. Sorry for the inconvenience!

**Comment by tysonjhayes** [comment]
OK - so it's been a while since I've looked at this repo so I might be a bit ignorant on your changes in particular.  However, you are making a change to test arrays that are being passed in.  So I would add a **new** test to the [Set-TargetResource in xDnsClientGlobalSetting](https://github.com/PowerShell/xNetworking/blob/dev/Tests/Unit/MSFT_xDnsClientGlobalSetting.Tests.ps1#L57)

Easiest way would to probably grab an existing test and make a few modifications. I've outlined an idea with some comments of what I'm thinking

````powershell
Describe "MSFT_xDnsClientGlobalSetting\Set-TargetResource" {
    Context 'DNS Client Global Settings SuffixSearchList is different' {
        #creating our list here so we can reuse it
        $suffixSearchList = @('fabrikam.com','fourthcoffee.com')

        # Creating a parameterfilter so we know we're getting the right one
        Mock -CommandName Set-DnsClientGlobalSetting -ParameterFilter {suffixSearchList -eq $suffixSearchList} {return $null}

        # not 100% sure this works but in theory we can test that we're calling the right one.
        # So if this is called we'll throw which we don't want. Which means we didn't correctly put in the array.
        Mock -CommandName Set-DnsClientGlobalSetting -MockWith {throw}
        It 'should not throw error' {
            {
                $Splat = $DnsClientGlobalSettingsSplat.Clone()
                $Splat.SuffixSearchList = $suffixSearchList
                Set-TargetResource @Splat
            } | Should Not Throw
        }
        It 'should call expected Mocks' {
            Assert-MockCalled -commandName Get-DnsClientGlobalSetting -Exactly 1
            Assert-MockCalled -commandName Set-DnsClientGlobalSetting -ParameterFilter {suffixSearchList -eq $suffixSearchList} -Exactly 1
        }
    }
}
````

I'm not 100% sure the code will work, I just mocked it up but it gives you an idea of what we're looking for. Please feel free to ask questions (and sign the CLA 😁 )

**Comment by ripclawffb** [comment]
Thanks for the guidance. I read the Pester documentation, but I'm having trouble understanding the line below. Specifically the comparison: suffixSearchList -eq $suffixSearchList. Where is the first suffixSearchList coming from? It doesn't look to be a variable or a string.

Mock -CommandName Set-DnsClientGlobalSetting -ParameterFilter {suffixSearchList -eq $suffixSearchList} {return $null}

Thanks.

**Comment by johlju** [comment]
It is a parameter for the cmdlet `Set-DnsClientGlobalSetting`. This mock should only be used when the cmdlet (mock) is called with 'suffixSearchList' equals the value in $suffixSearchList.

**Comment by ripclawffb** [comment]
Thanks for the guidance. I took an initial crack at it. Hopefully, it's what you're looking for. Let me know if any changes are required.

**Comment by PlagueHO** [comment]
Great job @ripclawffb ! Looks like you've done an awesome job getting to grips with Pester.

It took me a few minutes to get my head around how you were using the ParameterFilter on the *-DNSClientGlobalSettings mocks, but that is just because I'm a bit slow :grin:

Anyway :lgtm:

@johlju, @tysonjhayes?

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/172#-:-KZz5Zs_MrxY_nUBvEYl:b-ojb50b)*

**Comment by johlju** [comment]
:lgtm:

Just a few style comments.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[Tests/Unit/MSFT_xDnsClientGlobalSetting.Tests.ps1, line 94 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/172#-KZzpCg53FsTihbH6zNt:-KZzpCg6z2zsGiuMEZdz:b4id2de) ([raw file](https://github.com/powershell/xnetworking/blob/922f600e41092833c3a3c9a00c8372e90cab438a/Tests/Unit/MSFT_xDnsClientGlobalSetting.Tests.ps1#L94)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>
>                 Mock -CommandName Set-DnsClientGlobalSetting -ParameterFilter `
>                     {(Compare-Object -ReferenceObject $suffixSearchList -DifferenceObject `
>                     $suffixSearchListArray -SyncWindow 0).Length -eq 0} {return $null}
>                 Mock -CommandName Set-DnsClientGlobalSetting -MockWith {throw}
</details>

It's kind of hard reading this. Rather see this more readable, maybe something like

```powershell
Mock -CommandName Set-DnsClientGlobalSetting -ParameterFilter {
    (Compare-Object -ReferenceObject $suffixSearchList -DifferenceObject $suffixSearchListArray -SyncWindow 0).Length -eq 0
} -MockWith {
    return $null
}

Mock -CommandName Set-DnsClientGlobalSetting -MockWith {
    throw
}
``` 

Same for all the rest.

---

*[Tests/Unit/MSFT_xDnsClientGlobalSetting.Tests.ps1, line 99 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/172#-KZzpmUmW9FBi17ncCrU:-KZzpmUnc7G9xHkDIOOS:b80gusx) ([raw file](https://github.com/powershell/xnetworking/blob/922f600e41092833c3a3c9a00c8372e90cab438a/Tests/Unit/MSFT_xDnsClientGlobalSetting.Tests.ps1#L99)):*
> ```PowerShell
>                 It 'should not throw error' {
>                     {
>                         $Splat = $DnsClientGlobalSettingsSplat.Clone()
> ```

This seems like it is an old technical debt, but could we change `$Splat` to something more explanatory, like `$setTargetResourceParameters` and `$getTargetResourceParameters`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/172#-:-KZzrT6J4leRk-cARFE8:btnfjcx)*

**Comment by ripclawffb** [comment]
Appreciate the feedback. I was going to include comments in the unit tests to explain my logic, but I didn't see any other comments.

I have made the formatting changes as well as the variable name changes as requested. I didn't see $Splat used for any Get-* tests, so I only used $setTargetResourceParameters and $testTargetResourceParameters variable names.

**Comment by johlju** [comment]
@ripclawffb Would you mind going into Reviewable and type 'Done' in each comment? That way I know you have fixed the comment and I can resolve them.
You find a purple Reviewable image in the top comment, click on that and you will go to Reviewable. Type 'Done' in each comment, the when you done, click on the big green Publish button at the top. That means you publish your comments back to GitHub (this PR).

Thank you!

**Comment by ripclawffb** [comment]
Done.

---

Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[Tests/Unit/MSFT_xDnsClientGlobalSetting.Tests.ps1, line 94 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/172#-KZzpCg53FsTihbH6zNt:-K_4kvlZwPvxMEDWJCwV:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/922f600e41092833c3a3c9a00c8372e90cab438a/Tests/Unit/MSFT_xDnsClientGlobalSetting.Tests.ps1#L94)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

>                 Mock -CommandName Set-DnsClientGlobalSetting -ParameterFilter `
>                     {(Compare-Object -ReferenceObject $suffixSearchList -DifferenceObject `
>                     $suffixSearchListArray -SyncWindow 0).Length -eq 0} {return $null}
>                 Mock -CommandName Set-DnsClientGlobalSetting -MockWith {throw}

It's kind of hard reading this. Rather see this more readable, maybe something like

```powershell
Mock -CommandName Set-DnsClientGlobalSetting -ParameterFilter {
    (Compare-Object -ReferenceObject $suffixSearchList -DifferenceObject $suffixSearchListArray -SyncWindow 0).Length -eq 0
} -MockWith {
    return $null
}

Mock -CommandName Set-DnsClientGlobalSetting -MockWith {
    throw
}
``` 

Same for all the rest.
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xDnsClientGlobalSetting.Tests.ps1, line 99 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/172#-KZzpmUmW9FBi17ncCrU:-K_4kyvldZTJRFqjeWZN:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/922f600e41092833c3a3c9a00c8372e90cab438a/Tests/Unit/MSFT_xDnsClientGlobalSetting.Tests.ps1#L99)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

This seems like it is an old technical debt, but could we change `$Splat` to something more explanatory, like `$setTargetResourceParameters` and `$getTargetResourceParameters`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/172#-:-K_4lCTCLUc4q4IsT26s:b-896fix)*

**Comment by ripclawffb** [comment]
It looks like there were only 3 comments that I was able to respond to with done. Let me know if I missed any. Thanks.

**Comment by johlju** [comment]
Awesome, you did not miss any. Thank you. Just one more comment.

---

Reviewed 1 of 2 files at r1, 1 of 2 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Tests/Unit/MSFT_xDnsClientGlobalSetting.Tests.ps1, line 46 at r4](https://reviewable.io:443/reviews/powershell/xnetworking/172#-K_4rkePS7Cq3hcIF_Qj:-K_4rkePS7Cq3hcIF_Qk:blk65to) ([raw file](https://github.com/powershell/xnetworking/blob/e34803ce7966a2d71ad205728a699bb804ef9cf9/Tests/Unit/MSFT_xDnsClientGlobalSetting.Tests.ps1#L46)):*
> ```PowerShell
> 
>                 It 'should return correct DNS Client Global Settings values' {
>                     $Result = Get-TargetResource -IsSingleInstance 'Yes'
> ```

Would you mind changing this one `$Result` to `$getTargetResourceParameters`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/172#-:-K_4s5TzDWGffenpucBr:bi8rufg)*

**Comment by ripclawffb** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[Tests/Unit/MSFT_xDnsClientGlobalSetting.Tests.ps1, line 46 at r4](https://reviewable.io:443/reviews/powershell/xnetworking/172#-K_4rkePS7Cq3hcIF_Qj:-K_4wQ3hvcsbMVgrkJ0d:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/e34803ce7966a2d71ad205728a699bb804ef9cf9/Tests/Unit/MSFT_xDnsClientGlobalSetting.Tests.ps1#L46)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Would you mind changing this one `$Result` to `$getTargetResourceParameters`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/172)*

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/172#-:-K_53lIz227R5RgRtSB0:bnfp4nl)*

**Comment by PlagueHO** [comment]
Awesome job @ripclawffb - thanks again for all your work on this. It is much appreciated!

**Pull request merged**
