### PR TITLE
Added xNetAdapterRDMA

### PR DESCRIPTION
**Pull request by rchaganti**
Added a new resource for configuring RDMA setting on Network Adapters.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xnetworking/161)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Awesome job as always and another great resource, thanks @rchaganti

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 18 unresolved discussions.

---

*[DSCResources/MSFT_xNetAdapterRDMA/MSFT_xNetAdapterRDMA.psm1, line 15 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/161#-KVcozULgFkkXHbFLEjD:-KVcozUMS4oCivulVGzJ:b-s1byw8) ([raw file](https://github.com/powershell/xnetworking/blob/34e886a9429ea1456d00b75cc759544175137585/DSCResources/MSFT_xNetAdapterRDMA/MSFT_xNetAdapterRDMA.psm1#L15)):*
> ```PowerShell
> #endregion
> 
> function Get-TargetResource
> ```

In preparation for HQRM (I'm working hard getting the other resources in this module to HQRM) are you able to add a standard help header to the ```*-TargetResource``` functions? Only the .synopsis and .parameter sections are required for HQRM.

---

*[DSCResources/MSFT_xNetAdapterRDMA/MSFT_xNetAdapterRDMA.psm1, line 21 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/161#-KVcmj1zGM4mWyfJU9Iy:-KVcmj2-39rVmPNZPQQ7:b-s4ocbi) ([raw file](https://github.com/powershell/xnetworking/blob/34e886a9429ea1456d00b75cc759544175137585/DSCResources/MSFT_xNetAdapterRDMA/MSFT_xNetAdapterRDMA.psm1#L21)):*
> ```PowerShell
>     param
>     (
>         [parameter(Mandatory)]
> ```

Are you able to change this to ```[Parameter(Mandatory = $true)]```? - as per https://github.com/PowerShell/DscResources/issues/209#issuecomment-257123100

---

*[DSCResources/MSFT_xNetAdapterRDMA/MSFT_xNetAdapterRDMA.psm1, line 22 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/161#-KVcnZXY6GvHNV1_a83d:-KVcnZXZnS7WT1933gzB:b-uqs07k) ([raw file](https://github.com/powershell/xnetworking/blob/34e886a9429ea1456d00b75cc759544175137585/DSCResources/MSFT_xNetAdapterRDMA/MSFT_xNetAdapterRDMA.psm1#L22)):*
> ```PowerShell
>     (
>         [parameter(Mandatory)]
>         [String] $Name
> ```

Can you put Parameter name on the line following the parameter type as per https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#parameters

---

*[DSCResources/MSFT_xNetAdapterRDMA/MSFT_xNetAdapterRDMA.psm1, line 46 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/161#-KVcpHyq5hUReL4Yp9PT:-KVcpHyrPe1R6rNNpPLr:b-s1byw8) ([raw file](https://github.com/powershell/xnetworking/blob/34e886a9429ea1456d00b75cc759544175137585/DSCResources/MSFT_xNetAdapterRDMA/MSFT_xNetAdapterRDMA.psm1#L46)):*
> ```PowerShell
> }
> 
> function Set-TargetResource
> ```

In preparation for HQRM (I'm working hard getting the other resources in this module to HQRM) are you able to add a standard help header to the ```*-TargetResource``` functions? Only the .synopsis and .parameter sections are required for HQRM.

---

*[DSCResources/MSFT_xNetAdapterRDMA/MSFT_xNetAdapterRDMA.psm1, line 51 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/161#-KVcnFEapwgqo88t81_-:-KVcnFEb3alu7K0mTL7p:b-s4ocbi) ([raw file](https://github.com/powershell/xnetworking/blob/34e886a9429ea1456d00b75cc759544175137585/DSCResources/MSFT_xNetAdapterRDMA/MSFT_xNetAdapterRDMA.psm1#L51)):*
> ```PowerShell
>     param
>     (
>         [parameter(Mandatory)]
> ```

Are you able to change this to ```[Parameter(Mandatory = $true)]```? - as per https://github.com/PowerShell/DscResources/issues/209#issuecomment-257123100

---

*[DSCResources/MSFT_xNetAdapterRDMA/MSFT_xNetAdapterRDMA.psm1, line 52 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/161#-KVcnqkq6AJWxg9YR8xU:-KVcnqkq6AJWxg9YR8xV:b-uqs07k) ([raw file](https://github.com/powershell/xnetworking/blob/34e886a9429ea1456d00b75cc759544175137585/DSCResources/MSFT_xNetAdapterRDMA/MSFT_xNetAdapterRDMA.psm1#L52)):*
> ```PowerShell
>     (
>         [parameter(Mandatory)]
>         [String] $Name,
> ```

Can you put Parameter name on the line following the parameter type as per https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#parameters

---

*[DSCResources/MSFT_xNetAdapterRDMA/MSFT_xNetAdapterRDMA.psm1, line 55 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/161#-KVcnrU8q89pvpv7gRcN:-KVcnrU8q89pvpv7gRcO:b-uqs07k) ([raw file](https://github.com/powershell/xnetworking/blob/34e886a9429ea1456d00b75cc759544175137585/DSCResources/MSFT_xNetAdapterRDMA/MSFT_xNetAdapterRDMA.psm1#L55)):*
> ```PowerShell
> 
>         [parameter()]
>         [Boolean] $Enabled = $true
> ```

Can you put Parameter name on the line following the parameter type as per https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#parameters

---

*[DSCResources/MSFT_xNetAdapterRDMA/MSFT_xNetAdapterRDMA.psm1, line 83 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/161#-KVcpJrXpyZfnQdZTwgC:-KVcpJrXpyZfnQdZTwgD:b-s1byw8) ([raw file](https://github.com/powershell/xnetworking/blob/34e886a9429ea1456d00b75cc759544175137585/DSCResources/MSFT_xNetAdapterRDMA/MSFT_xNetAdapterRDMA.psm1#L83)):*
> ```PowerShell
> }
> 
> function Test-TargetResource
> ```

In preparation for HQRM (I'm working hard getting the other resources in this module to HQRM) are you able to add a standard help header to the ```*-TargetResource``` functions? Only the .synopsis and .parameter sections are required for HQRM.

---

*[DSCResources/MSFT_xNetAdapterRDMA/MSFT_xNetAdapterRDMA.psm1, line 89 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/161#-KVcnE5bXAgtTE8uSqWe:-KVcnE5bXAgtTE8uSqWf:b-s4ocbi) ([raw file](https://github.com/powershell/xnetworking/blob/34e886a9429ea1456d00b75cc759544175137585/DSCResources/MSFT_xNetAdapterRDMA/MSFT_xNetAdapterRDMA.psm1#L89)):*
> ```PowerShell
>     param
>     (
>         [parameter(Mandatory)]
> ```

Are you able to change this to ```[Parameter(Mandatory = $true)]```? - as per https://github.com/PowerShell/DscResources/issues/209#issuecomment-257123100

---

*[DSCResources/MSFT_xNetAdapterRDMA/MSFT_xNetAdapterRDMA.psm1, line 90 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/161#-KVcntCeiTd1OjX7Pe00:-KVcntCfVEtzblOrqUNY:b-uqs07k) ([raw file](https://github.com/powershell/xnetworking/blob/34e886a9429ea1456d00b75cc759544175137585/DSCResources/MSFT_xNetAdapterRDMA/MSFT_xNetAdapterRDMA.psm1#L90)):*
> ```PowerShell
>     (
>         [parameter(Mandatory)]
>         [String] $Name,
> ```

Can you put Parameter name on the line following the parameter type as per https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#parameters

---

*[DSCResources/MSFT_xNetAdapterRDMA/MSFT_xNetAdapterRDMA.psm1, line 93 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/161#-KVcnsjJdutDtuExACcV:-KVcnsjJdutDtuExACcW:b-uqs07k) ([raw file](https://github.com/powershell/xnetworking/blob/34e886a9429ea1456d00b75cc759544175137585/DSCResources/MSFT_xNetAdapterRDMA/MSFT_xNetAdapterRDMA.psm1#L93)):*
> ```PowerShell
> 
>         [parameter()]
>         [Boolean] $Enabled = $true
> ```

Can you put Parameter name on the line following the parameter type as per https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#parameters

---

*[DSCResources/MSFT_xNetAdapterRDMA/en-US/MSFT_xNetAdapterRDMA.psd1, line 2 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/161#-KVcnIkm4Uz62xnav8OT:-KVcnIknT7vxMsoyK2F5:b-n0joer) ([raw file](https://github.com/powershell/xnetworking/blob/34e886a9429ea1456d00b75cc759544175137585/DSCResources/MSFT_xNetAdapterRDMA/en-US/MSFT_xNetAdapterRDMA.psd1#L2)):*
> ```PowerShell
> ConvertFrom-StringData @'    
>     CheckNetAdapter=Checking if network adapter exists or not.
> ```

Nitpick - can you put spaces around the = ?

---

*[Examples/Sample_xNetAdapterRDMA_Disable.ps1, line 1 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/161#-KVcnxKw313M25KLCciO:-KVcnxKw313M25KLCciP:b4t3u5k) ([raw file](https://github.com/powershell/xnetworking/blob/34e886a9429ea1456d00b75cc759544175137585/Examples/Sample_xNetAdapterRDMA_Disable.ps1#L1)):*
> ```PowerShell
> configuration Sample_xNetAdapterRDMA_Enable
> ```

Can you please a description of the purpose example above the configuration?

---

*[Examples/Sample_xNetAdapterRDMA_Enable.ps1, line 1 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/161#-KVco9B3mX9NGPAzD1YP:-KVco9B3mX9NGPAzD1YQ:b4t3u5k) ([raw file](https://github.com/powershell/xnetworking/blob/34e886a9429ea1456d00b75cc759544175137585/Examples/Sample_xNetAdapterRDMA_Enable.ps1#L1)):*
> ```PowerShell
> configuration Sample_xNetAdapterRDMA_Disable
> ```

Can you please a description of the purpose example above the configuration?

---

*[Tests/Integration/MSFT_xNetAdapterRDMA.Integration.Tests.ps1, line 7 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/161#-KVcoFRWI6pk-LSTn_cH:-KVcoFRXBCZkYE2dUVG9:by0ees7) ([raw file](https://github.com/powershell/xnetworking/blob/34e886a9429ea1456d00b75cc759544175137585/Tests/Integration/MSFT_xNetAdapterRDMA.Integration.Tests.ps1#L7)):*
> ```PowerShell
> $Global:DSCResourceName    = 'MSFT_xNetAdapterRDMA'
> 
> #region HEADER
> ```

Can you please update this header to v1.1.1 as per https://github.com/PowerShell/DscResources/blob/master/Tests.Template/integration_template.ps1

Note: This will also require replacing all the ```$Global:``` scope variables with ```$Script:```.

---

*[Tests/Integration/MSFT_xNetAdapterRDMA.Integration.Tests.ps1, line 35 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/161#-KVcoOUlR_ByonC1gZOZ:-KVcoOUlR_ByonC1gZO_:b-l7x62l) ([raw file](https://github.com/powershell/xnetworking/blob/34e886a9429ea1456d00b75cc759544175137585/Tests/Integration/MSFT_xNetAdapterRDMA.Integration.Tests.ps1#L35)):*
> ```PowerShell
>         It 'Should compile without throwing' {
>             {
>                 Invoke-Expression -Command "$($Global:DSCResourceName)_Config -OutputPath `$TestEnvironment.WorkingFolder"
> ```

Can you remove the ```Invoke-Expression``` and use the method in this template instead: https://github.com/PowerShell/DscResources/blob/master/Tests.Template/integration_template.ps1

---

*[Tests/Integration/MSFT_xNetAdapterRDMA.Integration.Tests.ps1, line 41 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/161#-KVcq18ZXqAPDVXSwn9X:-KVcq18_F5tvqKgSfNy1:b-3ql0if) ([raw file](https://github.com/powershell/xnetworking/blob/34e886a9429ea1456d00b75cc759544175137585/Tests/Integration/MSFT_xNetAdapterRDMA.Integration.Tests.ps1#L41)):*
> ```PowerShell
> 
>         It 'should be able to call Get-DscConfiguration without throwing' {
>             Start-Sleep -Seconds 30
> ```

How come we wait for 30 seconds here? Is there any way other way of doing this?

---

*[Tests/Unit/MSFT_xNetAdapterRDMA.Tests.ps1, line 4 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/161#-KVconTwb8dygEKN7Ulf:-KVconTwb8dygEKN7Ulg:buhl8dz) ([raw file](https://github.com/powershell/xnetworking/blob/34e886a9429ea1456d00b75cc759544175137585/Tests/Unit/MSFT_xNetAdapterRDMA.Tests.ps1#L4)):*
> ```PowerShell
> $Global:DSCResourceName = 'MSFT_xNetAdapterRDMA'
> 
> #region HEADER
> ```

Can you please update this header to v1.1.1 as per https://github.com/PowerShell/DscResources/blob/master/Tests.Template/unit_template.ps1

Note: This will also require replacing all the ```$Global:``` scope variables with ```$Script:```.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/161#-:-KVcpe7j-g-kjp1utCcv:b-muvl4d)*

**Comment by rchaganti** [comment]
Review status: 2 of 10 files reviewed at latest revision, 18 unresolved discussions.

---

*[DSCResources/MSFT_xNetAdapterRDMA/MSFT_xNetAdapterRDMA.psm1, line 15 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/161#-KVcozULgFkkXHbFLEjD:-KVj6VST4Kas90JmZJSk:b-896fja) ([raw file](https://github.com/powershell/xnetworking/blob/34e886a9429ea1456d00b75cc759544175137585/DSCResources/MSFT_xNetAdapterRDMA/MSFT_xNetAdapterRDMA.psm1#L15)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> In preparation for HQRM (I'm working hard getting the other resources in this module to HQRM) are you able to add a standard help header to the ```*-TargetResource``` functions? Only the .synopsis and .parameter sections are required for HQRM.
</details>
Done!

---

*[DSCResources/MSFT_xNetAdapterRDMA/MSFT_xNetAdapterRDMA.psm1, line 21 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/161#-KVcmj1zGM4mWyfJU9Iy:-KVj6Y7M-YJ352xO69Qc:b-896fja) ([raw file](https://github.com/powershell/xnetworking/blob/34e886a9429ea1456d00b75cc759544175137585/DSCResources/MSFT_xNetAdapterRDMA/MSFT_xNetAdapterRDMA.psm1#L21)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> Are you able to change this to ```[Parameter(Mandatory = $true)]```? - as per https://github.com/PowerShell/DscResources/issues/209#issuecomment-257123100
</details>
Done!

---

*[DSCResources/MSFT_xNetAdapterRDMA/MSFT_xNetAdapterRDMA.psm1, line 22 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/161#-KVcnZXY6GvHNV1_a83d:-KVj6Z82csWFJJ3pLLLE:b-896fja) ([raw file](https://github.com/powershell/xnetworking/blob/34e886a9429ea1456d00b75cc759544175137585/DSCResources/MSFT_xNetAdapterRDMA/MSFT_xNetAdapterRDMA.psm1#L22)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> Can you put Parameter name on the line following the parameter type as per https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#parameters
</details>
Done!

---

*[DSCResources/MSFT_xNetAdapterRDMA/MSFT_xNetAdapterRDMA.psm1, line 46 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/161#-KVcpHyq5hUReL4Yp9PT:-KVj6_8jJnI86ntKzEEH:b-896fja) ([raw file](https://github.com/powershell/xnetworking/blob/34e886a9429ea1456d00b75cc759544175137585/DSCResources/MSFT_xNetAdapterRDMA/MSFT_xNetAdapterRDMA.psm1#L46)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> In preparation for HQRM (I'm working hard getting the other resources in this module to HQRM) are you able to add a standard help header to the ```*-TargetResource``` functions? Only the .synopsis and .parameter sections are required for HQRM.
</details>
Done!

---

*[DSCResources/MSFT_xNetAdapterRDMA/MSFT_xNetAdapterRDMA.psm1, line 51 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/161#-KVcnFEapwgqo88t81_-:-KVj6aEszUvlBa3P99Ed:b-896fja) ([raw file](https://github.com/powershell/xnetworking/blob/34e886a9429ea1456d00b75cc759544175137585/DSCResources/MSFT_xNetAdapterRDMA/MSFT_xNetAdapterRDMA.psm1#L51)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> Are you able to change this to ```[Parameter(Mandatory = $true)]```? - as per https://github.com/PowerShell/DscResources/issues/209#issuecomment-257123100
</details>
Done!

---

*[DSCResources/MSFT_xNetAdapterRDMA/MSFT_xNetAdapterRDMA.psm1, line 52 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/161#-KVcnqkq6AJWxg9YR8xU:-KVj6bccHFP-Kcrgwrw3:b-896fja) ([raw file](https://github.com/powershell/xnetworking/blob/34e886a9429ea1456d00b75cc759544175137585/DSCResources/MSFT_xNetAdapterRDMA/MSFT_xNetAdapterRDMA.psm1#L52)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> Can you put Parameter name on the line following the parameter type as per https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#parameters
</details>
Done!

---

*[DSCResources/MSFT_xNetAdapterRDMA/MSFT_xNetAdapterRDMA.psm1, line 55 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/161#-KVcnrU8q89pvpv7gRcN:-KVj6cmJKeoNlVqwpPC3:b-896fja) ([raw file](https://github.com/powershell/xnetworking/blob/34e886a9429ea1456d00b75cc759544175137585/DSCResources/MSFT_xNetAdapterRDMA/MSFT_xNetAdapterRDMA.psm1#L55)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> Can you put Parameter name on the line following the parameter type as per https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#parameters
</details>
Done!

---

*[DSCResources/MSFT_xNetAdapterRDMA/MSFT_xNetAdapterRDMA.psm1, line 83 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/161#-KVcpJrXpyZfnQdZTwgC:-KVj6dglWO0Kfshf3chy:b-896fja) ([raw file](https://github.com/powershell/xnetworking/blob/34e886a9429ea1456d00b75cc759544175137585/DSCResources/MSFT_xNetAdapterRDMA/MSFT_xNetAdapterRDMA.psm1#L83)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> In preparation for HQRM (I'm working hard getting the other resources in this module to HQRM) are you able to add a standard help header to the ```*-TargetResource``` functions? Only the .synopsis and .parameter sections are required for HQRM.
</details>
Done!

---

*[DSCResources/MSFT_xNetAdapterRDMA/MSFT_xNetAdapterRDMA.psm1, line 89 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/161#-KVcnE5bXAgtTE8uSqWe:-KVj6eVWUnuENeZTbpXS:b-896fja) ([raw file](https://github.com/powershell/xnetworking/blob/34e886a9429ea1456d00b75cc759544175137585/DSCResources/MSFT_xNetAdapterRDMA/MSFT_xNetAdapterRDMA.psm1#L89)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> Are you able to change this to ```[Parameter(Mandatory = $true)]```? - as per https://github.com/PowerShell/DscResources/issues/209#issuecomment-257123100
</details>
Done!

---

*[DSCResources/MSFT_xNetAdapterRDMA/MSFT_xNetAdapterRDMA.psm1, line 90 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/161#-KVcntCeiTd1OjX7Pe00:-KVj6fIGzb0KpHB5EWnK:b-896fja) ([raw file](https://github.com/powershell/xnetworking/blob/34e886a9429ea1456d00b75cc759544175137585/DSCResources/MSFT_xNetAdapterRDMA/MSFT_xNetAdapterRDMA.psm1#L90)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> Can you put Parameter name on the line following the parameter type as per https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#parameters
</details>
Done!

---

*[DSCResources/MSFT_xNetAdapterRDMA/MSFT_xNetAdapterRDMA.psm1, line 93 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/161#-KVcnsjJdutDtuExACcV:-KVj6yhhcNis12WO9-2m:b-896fja) ([raw file](https://github.com/powershell/xnetworking/blob/34e886a9429ea1456d00b75cc759544175137585/DSCResources/MSFT_xNetAdapterRDMA/MSFT_xNetAdapterRDMA.psm1#L93)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> Can you put Parameter name on the line following the parameter type as per https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#parameters
</details>
Done!

---

*[DSCResources/MSFT_xNetAdapterRDMA/en-US/MSFT_xNetAdapterRDMA.psd1, line 2 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/161#-KVcnIkm4Uz62xnav8OT:-KVj6gUyDWp4xmd-53Ck:b-896fja) ([raw file](https://github.com/powershell/xnetworking/blob/34e886a9429ea1456d00b75cc759544175137585/DSCResources/MSFT_xNetAdapterRDMA/en-US/MSFT_xNetAdapterRDMA.psd1#L2)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> Nitpick - can you put spaces around the = ?
</details>
Done!

---

*[Examples/Sample_xNetAdapterRDMA_Disable.ps1, line 1 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/161#-KVcnxKw313M25KLCciO:-KVj6irs5ruLmWwgIvnc:b-896fja) ([raw file](https://github.com/powershell/xnetworking/blob/34e886a9429ea1456d00b75cc759544175137585/Examples/Sample_xNetAdapterRDMA_Disable.ps1#L1)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> Can you please a description of the purpose example above the configuration?
</details>
Done!

---

*[Examples/Sample_xNetAdapterRDMA_Enable.ps1, line 1 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/161#-KVco9B3mX9NGPAzD1YP:-KVj6jyVGFoYQgpgoM9f:b-896fja) ([raw file](https://github.com/powershell/xnetworking/blob/34e886a9429ea1456d00b75cc759544175137585/Examples/Sample_xNetAdapterRDMA_Enable.ps1#L1)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> Can you please a description of the purpose example above the configuration?
</details>
Done!

---

*[Tests/Integration/MSFT_xNetAdapterRDMA.Integration.Tests.ps1, line 7 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/161#-KVcoFRWI6pk-LSTn_cH:-KVj6oBEOQAUl2PjpOsH:b-896fja) ([raw file](https://github.com/powershell/xnetworking/blob/34e886a9429ea1456d00b75cc759544175137585/Tests/Integration/MSFT_xNetAdapterRDMA.Integration.Tests.ps1#L7)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> Can you please update this header to v1.1.1 as per https://github.com/PowerShell/DscResources/blob/master/Tests.Template/integration_template.ps1
> 
> Note: This will also require replacing all the ```$Global:``` scope variables with ```$Script:```.
</details>
Done!

---

*[Tests/Integration/MSFT_xNetAdapterRDMA.Integration.Tests.ps1, line 35 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/161#-KVcoOUlR_ByonC1gZOZ:-KVj6pxXTfLVVpoJp3pW:b-896fja) ([raw file](https://github.com/powershell/xnetworking/blob/34e886a9429ea1456d00b75cc759544175137585/Tests/Integration/MSFT_xNetAdapterRDMA.Integration.Tests.ps1#L35)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> Can you remove the ```Invoke-Expression``` and use the method in this template instead: https://github.com/PowerShell/DscResources/blob/master/Tests.Template/integration_template.ps1
</details>
Done!

---

*[Tests/Integration/MSFT_xNetAdapterRDMA.Integration.Tests.ps1, line 41 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/161#-KVcq18ZXqAPDVXSwn9X:-KVj6r4jlQJr2Qt0-CS8:b-896fja) ([raw file](https://github.com/powershell/xnetworking/blob/34e886a9429ea1456d00b75cc759544175137585/Tests/Integration/MSFT_xNetAdapterRDMA.Integration.Tests.ps1#L41)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> How come we wait for 30 seconds here? Is there any way other way of doing this?
</details>
Done!

---

*[Tests/Unit/MSFT_xNetAdapterRDMA.Tests.ps1, line 4 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/161#-KVconTwb8dygEKN7Ulf:-KVj6sJjpcyWoHKgVcB7:b-896fja) ([raw file](https://github.com/powershell/xnetworking/blob/34e886a9429ea1456d00b75cc759544175137585/Tests/Unit/MSFT_xNetAdapterRDMA.Tests.ps1#L4)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> Can you please update this header to v1.1.1 as per https://github.com/PowerShell/DscResources/blob/master/Tests.Template/unit_template.ps1
> 
> Note: This will also require replacing all the ```$Global:``` scope variables with ```$Script:```.
</details>
Done!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/161)*

**Comment by PlagueHO** [comment]
@rchaganti - are you able to fix the Merge conflicts in Readme.md? Thank you!

**Comment by rchaganti** [comment]
Fixing it today!

**Comment by rchaganti** [comment]
hmm! I may need some help here. I though I resolved the conflict but Github doesn't think so. I can see my local version is same as the dev branch.

**Comment by PlagueHO** [comment]
@rchaganti - I'm not 100% sure what is conflicting with the Readme.md. Github should be able to correctly report on the conflicts though - so I'm not sure why it isn't.

I did make significant changes to the Readme.md between when you first submitted this PR though, so I am not surprised that is conflicting.

I do notice that the entry for your new resource appears in two places: Under ### Unreleased and under ### 3.0.0.0

I'm thinking it shouldn't be under 3.0.0.0.

**Comment by rchaganti** [comment]
I see that but that may not be causing the conflict. Can we just override the readme in the PR and merge if that is an option? I can submit a right readme once after that.

**Comment by PlagueHO** [comment]
@rchaganti - unfortunately Github won't let me merge this (button is disabled) until this is resolved.

Perhaps you should close this PR and submit it again?

**Comment by rchaganti** [comment]
hmm! lets do that. This is hanging here for too long.

**Pull request closed without merging**
