### PR TITLE
Improve xNetAdapterName Resource to handle already renamed adapters - Fixes #209

### LINKED ISSUE #209: xNewAdapterName output misleading when Adapter Not Found
If the xNewAdapterName resource is used to rename an adapter using the name where an adapter with the existing or new name can't be found then a misleading error message will be shown.

### PR DESCRIPTION
**Pull request by PlagueHO**
I've improved the log information as well and extended the integration and unit tests to provide better coverage of these scenarios.

The resource can now be correctly used to rename an adapter by just identifying it by name. But this isn't the primary user story that drove this. If you know the adapter name already, then renaming it isn't really that useful (but it'll work).

The primary user story that this should address is when you don't know the adapter name in the OS - you only know various parameters of the adapter (e.g. MAC Address, Driver) and therefore need to rename it so that that all other resources have a known name they can reference.

For example:
```powershell
        xNetAdapterName RenameNetAdapterCluster
        {
            NewName        = 'Cluster'
            MacAddress     = '9C-D2-1E-61-B5-DA'
        }
```

This will work fine - but it's not really the primary purpose:
```powershell
        xNetAdapterName RenameNetAdapterCluster
        {
            NewName        = 'Cluster'
            Name      = 'Ethernet 1'
        }
```

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xnetworking/210)

### CODE REVIEW

**Comment by johlju** [comment]
While I was in review mode I did this one too :smile: 

---

Reviewed 10 of 11 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 15 unresolved discussions.

---

*[Modules/xNetworking/DSCResources/MSFT_xNetAdapterName/MSFT_xNetAdapterName.psm1, line 115 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/210#-KlZULy79KzMiW3PWP97:-KlZULy79KzMiW3PWP98:boauwze) ([raw file](https://github.com/powershell/xnetworking/blob/9802c784dd3b74b263c8599d82fced479c8c73bd/Modules/xNetworking/DSCResources/MSFT_xNetAdapterName/MSFT_xNetAdapterName.psm1#L115)):*
> ```PowerShell
>     if (-not $adapter)
>     {
>         $PSBoundParameters.Remove('NewName')
> ```

Maybe write a verbose message her as well using $LocalizedData.GettingNetAdapterNameMessage but for the Name parameter?

---

*[Modules/xNetworking/DSCResources/MSFT_xNetAdapterName/MSFT_xNetAdapterName.psm1, line 237 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/210#-KlZThrZ99pZRJkVErUj:-KlZThrZ99pZRJkVErUk:b-ql53gz) ([raw file](https://github.com/powershell/xnetworking/blob/9802c784dd3b74b263c8599d82fced479c8c73bd/Modules/xNetworking/DSCResources/MSFT_xNetAdapterName/MSFT_xNetAdapterName.psm1#L237)):*
> ```PowerShell
>         ) -join '')
> 
>     $null = $PSBoundParameters.Remove('NewName')
> ```

Maybe use the same method (style) as removing the parameter as it is done in the Get-method?

---

*[Modules/xNetworking/DSCResources/MSFT_xNetAdapterName/MSFT_xNetAdapterName.psm1, line 352 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/210#-KlZTVXbprjfJSpJNZHh:-KlZTVXbprjfJSpJNZHi:b-ql53gz) ([raw file](https://github.com/powershell/xnetworking/blob/9802c784dd3b74b263c8599d82fced479c8c73bd/Modules/xNetworking/DSCResources/MSFT_xNetAdapterName/MSFT_xNetAdapterName.psm1#L352)):*
> ```PowerShell
>         ) -join '')
> 
>     $null = $PSBoundParameters.Remove('NewName')
> ```

Maybe use the same method (style) as removing the parameter as it is done in the Get-method?

---

*[Modules/xNetworking/DSCResources/MSFT_xNetAdapterName/MSFT_xNetAdapterName.psm1, line 370 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/210#-KlZU6QpMYYoeVK3u9ml:-KlZU6QpMYYoeVK3u9mm:blfhk4u) ([raw file](https://github.com/powershell/xnetworking/blob/9802c784dd3b74b263c8599d82fced479c8c73bd/Modules/xNetworking/DSCResources/MSFT_xNetAdapterName/MSFT_xNetAdapterName.psm1#L370)):*
> ```PowerShell
>     else
>     {
>         # Find an adapter matching the parameters - throw if none can be found
> ```

Maybe write a verbose message her as well using $LocalizedData.TestingNetAdapterNameMessage but for the Name parameter?

---

*[Modules/xNetworking/Modules/NetworkingDsc.Common/NetworkingDsc.Common.psm1, line 223 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/210#-KlZVCLbw6cSSoUeLH5h:-KlZVCLbw6cSSoUeLH5i:b-jbqv2a) ([raw file](https://github.com/powershell/xnetworking/blob/9802c784dd3b74b263c8599d82fced479c8c73bd/Modules/xNetworking/Modules/NetworkingDsc.Common/NetworkingDsc.Common.psm1#L223)):*
> ```PowerShell
>         New-InvalidOperationException `
>             -Message ($LocalizedData.NetAdapterNotFoundError)
>         return $null
> ```

Why do you need return here when you are throwing before?

---

*[Modules/xNetworking/Modules/NetworkingDsc.Common/NetworkingDsc.Common.psm1, line 241 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/210#-KlZVOZ1Lp4vCPIQ_Hrm:-KlZVOZ1Lp4vCPIQ_Hrn:bn40wg9) ([raw file](https://github.com/powershell/xnetworking/blob/9802c784dd3b74b263c8599d82fced479c8c73bd/Modules/xNetworking/Modules/NetworkingDsc.Common/NetworkingDsc.Common.psm1#L241)):*
> ```PowerShell
>                         -Message ($LocalizedData.InvalidNetAdapterNumberError `
>                             -f $matchingAdapters.Count,$InterfaceNumber)
>                     return $null
> ```

Same as above (just mark so I know where to verify)

---

*[Modules/xNetworking/Modules/NetworkingDsc.Common/NetworkingDsc.Common.psm1, line 249 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/210#-KlZVP5pMKSBIX0yy0OR:-KlZVP5pMKSBIX0yy0OS:bn40wg9) ([raw file](https://github.com/powershell/xnetworking/blob/9802c784dd3b74b263c8599d82fced479c8c73bd/Modules/xNetworking/Modules/NetworkingDsc.Common/NetworkingDsc.Common.psm1#L249)):*
> ```PowerShell
>                     -Message ($LocalizedData.MultipleMatchingNetAdapterFound `
>                         -f $matchingAdapters.Count)
>                 return $null
> ```

Same as above (just mark so I know where to verify)

---

*[Modules/xNetworking/Modules/NetworkingDsc.Common/en-us/NetworkingDsc.Common.strings.psd1, line 3 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/210#-KlZW4VFyy-JpeDgz3aC:-KlZW4VFyy-JpeDgz3aD:b3pl44h) ([raw file](https://github.com/powershell/xnetworking/blob/9802c784dd3b74b263c8599d82fced479c8c73bd/Modules/xNetworking/Modules/NetworkingDsc.Common/en-us/NetworkingDsc.Common.strings.psd1#L3)):*
> Found all Network Adapters because no filter parameters provided.

'network adapters' with lower-case?

---

*[Tests/Integration/MSFT_xNetAdapterName.Integration.Tests.ps1, line 103 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/210#-KlZWWTZN6BGruxT64ea:-KlZWWTZN6BGruxT64eb:b-yuk0nn) ([raw file](https://github.com/powershell/xnetworking/blob/9802c784dd3b74b263c8599d82fced479c8c73bd/Tests/Integration/MSFT_xNetAdapterName.Integration.Tests.ps1#L103)):*
> ```PowerShell
> 
>         #region DEFAULT TESTS
>         It 'should compile and apply the MOF without throwing' {
> ```

Should with upper 'S' (to match the one above) - and all the rest. TestsGuideline says 'Should' with upper 'S'.

---

*[Tests/Integration/MSFT_xNetAdapterName.Integration.Tests.ps1, line 119 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/210#-KlZWPUVjp7HduPi77r_:-KlZWPUVjp7HduPi77ra:b-iqa19c) ([raw file](https://github.com/powershell/xnetworking/blob/9802c784dd3b74b263c8599d82fced479c8c73bd/Tests/Integration/MSFT_xNetAdapterName.Integration.Tests.ps1#L119)):*
> ```PowerShell
>                     -OutputPath $TestDrive `
>                     -ConfigurationData $configData
>                 Start-DscConfiguration -Path $TestDrive `
> ```

Blank row before this one.

---

*[Tests/Unit/MSFT_xNetAdapterName.Tests.ps1, line 99 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/210#-KlZXabCZuPyV3Uk2pJA:-KlZXabCZuPyV3Uk2pJB:b-uaacy9) ([raw file](https://github.com/powershell/xnetworking/blob/9802c784dd3b74b263c8599d82fced479c8c73bd/Tests/Unit/MSFT_xNetAdapterName.Tests.ps1#L99)):*
> Assert-MockCalled -commandName Find-NetworkAdapter -Exactly 1

I think this should be `-Exactly -Times 1`

Also a bunch of them. :)

---

*[Tests/Unit/MSFT_xNetAdapterName.Tests.ps1, line 110 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/210#-KlZXryuG-QM6zMvOrrv:-KlZXryuG-QM6zMvOrrw:b9dk4cc) ([raw file](https://github.com/powershell/xnetworking/blob/9802c784dd3b74b263c8599d82fced479c8c73bd/Tests/Unit/MSFT_xNetAdapterName.Tests.ps1#L110)):*
> ```PowerShell
>                     -ParameterFilter { $Name -eq $script:adapterName }
> 
>                 It 'should not throw' {
> ```

Upper 'S' in 'Should' (an all others)

---

*[Tests/Unit/NetworkingDsc.Common.tests.ps1, line 380 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/210#-KlZZEpUAmFDDubsz6sO:-KlZZEpUAmFDDubsz6sP:buz05o8) ([raw file](https://github.com/powershell/xnetworking/blob/9802c784dd3b74b263c8599d82fced479c8c73bd/Tests/Unit/NetworkingDsc.Common.tests.ps1#L380)):*
> ```PowerShell
>                     -Message ($LocalizedData.NetAdapterNotFoundError)
> 
>                 It 'should throw exception' {
> ```

Should throw the correct error
(or exception)

---

*[Tests/Unit/NetworkingDsc.Common.tests.ps1, line 397 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/210#-KlZZAX1EMdi9p6ixHCi:-KlZZAX1EMdi9p6ixHCj:buz05o8) ([raw file](https://github.com/powershell/xnetworking/blob/9802c784dd3b74b263c8599d82fced479c8c73bd/Tests/Unit/NetworkingDsc.Common.tests.ps1#L397)):*
> ```PowerShell
>                     -Message ($LocalizedData.MultipleMatchingNetAdapterFound -f 2)
> 
>                 It 'should throw exception' {
> ```

Should throw the correct error
(or exception)

---

*[Tests/Unit/NetworkingDsc.Common.tests.ps1, line 411 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/210#-KlZZbcvgRBKet4Bb0ko:-KlZZbcvgRBKet4Bb0kp:b-kyt3d7) ([raw file](https://github.com/powershell/xnetworking/blob/9802c784dd3b74b263c8599d82fced479c8c73bd/Tests/Unit/NetworkingDsc.Common.tests.ps1#L411)):*
> ```PowerShell
>                     -MockWith { $adapterArray }
> 
>                 It 'should throw exception' {
> ```

Should not throw an error
(or exception)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/210#-:-KlZZlku62plBn9nWRAi:b-134a7e)*

**Comment by PlagueHO** [comment]
Wow! You're a legend @johlju - I'd even forgotten I had this one sitting around! :grin: I can now begin working on some new features and bug fixes! Go :sweden: !

---

Review status: 3 of 10 files reviewed at latest revision, 15 unresolved discussions.

---

*[Modules/xNetworking/DSCResources/MSFT_xNetAdapterName/MSFT_xNetAdapterName.psm1, line 115 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/210#-KlZULy79KzMiW3PWP97:-Klf6cxYXmcoLguBJvZZ:bw1c3e0) ([raw file](https://github.com/powershell/xnetworking/blob/9802c784dd3b74b263c8599d82fced479c8c73bd/Modules/xNetworking/DSCResources/MSFT_xNetAdapterName/MSFT_xNetAdapterName.psm1#L115)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Maybe write a verbose message her as well using $LocalizedData.GettingNetAdapterNameMessage but for the Name parameter?
</blockquote></details>

I've added the logging message, but I created a new message - as this search will most likely be querying using other things (not usually name) - e.g. MAC Address, adapter type.

---

*[Modules/xNetworking/DSCResources/MSFT_xNetAdapterName/MSFT_xNetAdapterName.psm1, line 237 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/210#-KlZThrZ99pZRJkVErUj:-Klf8zXiXaKwyn6b8n39:bsp0ozw) ([raw file](https://github.com/powershell/xnetworking/blob/9802c784dd3b74b263c8599d82fced479c8c73bd/Modules/xNetworking/DSCResources/MSFT_xNetAdapterName/MSFT_xNetAdapterName.psm1#L237)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Maybe use the same method (style) as removing the parameter as it is done in the Get-method?
</blockquote></details>

I've actually changed the one in Get-TargetResource - that one was wrong - this is the correct method that should be used.

---

*[Modules/xNetworking/DSCResources/MSFT_xNetAdapterName/MSFT_xNetAdapterName.psm1, line 352 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/210#-KlZTVXbprjfJSpJNZHh:-Klf9CdZbDejFdq3kvr7:bsp0ozw) ([raw file](https://github.com/powershell/xnetworking/blob/9802c784dd3b74b263c8599d82fced479c8c73bd/Modules/xNetworking/DSCResources/MSFT_xNetAdapterName/MSFT_xNetAdapterName.psm1#L352)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Maybe use the same method (style) as removing the parameter as it is done in the Get-method?
</blockquote></details>

I've actually changed the one in Get-TargetResource - that one was wrong - this is the correct method that should be used.

---

*[Modules/xNetworking/DSCResources/MSFT_xNetAdapterName/MSFT_xNetAdapterName.psm1, line 370 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/210#-KlZU6QpMYYoeVK3u9ml:-Klf9HweB0UFnd7gz2fF:bpr1vej) ([raw file](https://github.com/powershell/xnetworking/blob/9802c784dd3b74b263c8599d82fced479c8c73bd/Modules/xNetworking/DSCResources/MSFT_xNetAdapterName/MSFT_xNetAdapterName.psm1#L370)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Maybe write a verbose message her as well using $LocalizedData.TestingNetAdapterNameMessage but for the Name parameter?
</blockquote></details>

Done - but as above it is a generic message because we do not know the search parameters that are being used.

---

*[Modules/xNetworking/Modules/NetworkingDsc.Common/NetworkingDsc.Common.psm1, line 223 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/210#-KlZVCLbw6cSSoUeLH5h:-KlfAMOyPh1n_w5nfrvK:bf5g07t) ([raw file](https://github.com/powershell/xnetworking/blob/9802c784dd3b74b263c8599d82fced479c8c73bd/Modules/xNetworking/Modules/NetworkingDsc.Common/NetworkingDsc.Common.psm1#L223)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Why do you need return here when you are throwing before?
</blockquote></details>

I've added a comment explaining this, but because I sometimes call this function with -EA SilentlyContinue (which prevents the exception from terminating the call) this ensures that a $null is always returned.

---

*[Modules/xNetworking/Modules/NetworkingDsc.Common/NetworkingDsc.Common.psm1, line 241 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/210#-KlZVOZ1Lp4vCPIQ_Hrm:-KlfAb5c2cD-2pK2dwGL:bf5g07t) ([raw file](https://github.com/powershell/xnetworking/blob/9802c784dd3b74b263c8599d82fced479c8c73bd/Modules/xNetworking/Modules/NetworkingDsc.Common/NetworkingDsc.Common.psm1#L241)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Same as above (just mark so I know where to verify)
</blockquote></details>

I've added a comment explaining this, but because I sometimes call this function with -EA SilentlyContinue (which prevents the exception from terminating the call) this ensures that a $null is always returned.

---

*[Modules/xNetworking/Modules/NetworkingDsc.Common/NetworkingDsc.Common.psm1, line 249 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/210#-KlZVP5pMKSBIX0yy0OR:-KlfAcRf6VgP1-musEyt:bf5g07t) ([raw file](https://github.com/powershell/xnetworking/blob/9802c784dd3b74b263c8599d82fced479c8c73bd/Modules/xNetworking/Modules/NetworkingDsc.Common/NetworkingDsc.Common.psm1#L249)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Same as above (just mark so I know where to verify)
</blockquote></details>

I've added a comment explaining this, but because I sometimes call this function with -EA SilentlyContinue (which prevents the exception from terminating the call) this ensures that a $null is always returned.

---

*[Modules/xNetworking/Modules/NetworkingDsc.Common/en-us/NetworkingDsc.Common.strings.psd1, line 3 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/210#-KlZW4VFyy-JpeDgz3aC:-KlfAlNTIRFUU0eX_uDF:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/9802c784dd3b74b263c8599d82fced479c8c73bd/Modules/xNetworking/Modules/NetworkingDsc.Common/en-us/NetworkingDsc.Common.strings.psd1#L3)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> Found all Network Adapters because no filter parameters provided.

'network adapters' with lower-case?
</blockquote></details>

Done.

---

*[Tests/Integration/MSFT_xNetAdapterName.Integration.Tests.ps1, line 103 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/210#-KlZWWTZN6BGruxT64ea:-KlfBUvLO_7_NNvFNjhd:b45wd2v) ([raw file](https://github.com/powershell/xnetworking/blob/9802c784dd3b74b263c8599d82fced479c8c73bd/Tests/Integration/MSFT_xNetAdapterName.Integration.Tests.ps1#L103)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Should with upper 'S' (to match the one above) - and all the rest. TestsGuideline says 'Should' with upper 'S'.
</blockquote></details>

Great catch! I've fixed the ones in this resource, but I'll do a global fix when I work on finishing bringing this up to HQRM (soon).

---

*[Tests/Integration/MSFT_xNetAdapterName.Integration.Tests.ps1, line 119 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/210#-KlZWPUVjp7HduPi77r_:-KlfBr2jjykxsFybPLzG:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/9802c784dd3b74b263c8599d82fced479c8c73bd/Tests/Integration/MSFT_xNetAdapterName.Integration.Tests.ps1#L119)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Blank row before this one.
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xNetAdapterName.Tests.ps1, line 99 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/210#-KlZXabCZuPyV3Uk2pJA:-KlfCGpjOyKp2QiCYm-U:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/9802c784dd3b74b263c8599d82fced479c8c73bd/Tests/Unit/MSFT_xNetAdapterName.Tests.ps1#L99)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> Assert-MockCalled -commandName Find-NetworkAdapter -Exactly 1

I think this should be `-Exactly -Times 1`

Also a bunch of them. :)
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xNetAdapterName.Tests.ps1, line 110 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/210#-KlZXryuG-QM6zMvOrrv:-KlfCLb0_lB3TF_KaIj5:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/9802c784dd3b74b263c8599d82fced479c8c73bd/Tests/Unit/MSFT_xNetAdapterName.Tests.ps1#L110)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Upper 'S' in 'Should' (an all others)
</blockquote></details>

Done.

---

*[Tests/Unit/NetworkingDsc.Common.tests.ps1, line 380 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/210#-KlZZEpUAmFDDubsz6sO:-KlfDeHU8MeCait95HPz:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/9802c784dd3b74b263c8599d82fced479c8c73bd/Tests/Unit/NetworkingDsc.Common.tests.ps1#L380)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Should throw the correct error
(or exception)
</blockquote></details>

Done.

---

*[Tests/Unit/NetworkingDsc.Common.tests.ps1, line 397 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/210#-KlZZAX1EMdi9p6ixHCi:-KlfD0BrA5IJAz15q2Zf:b81yrdz) ([raw file](https://github.com/powershell/xnetworking/blob/9802c784dd3b74b263c8599d82fced479c8c73bd/Tests/Unit/NetworkingDsc.Common.tests.ps1#L397)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Should throw the correct error
(or exception)
</blockquote></details>

Done. And all the others too.

---

*[Tests/Unit/NetworkingDsc.Common.tests.ps1, line 411 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/210#-KlZZbcvgRBKet4Bb0ko:-KlfDVEJdgVr9H01HWS7:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/9802c784dd3b74b263c8599d82fced479c8c73bd/Tests/Unit/NetworkingDsc.Common.tests.ps1#L411)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Should not throw an error
(or exception)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/210#-:-KlfDgoNjWthvA1RDeYf:b-akes0a)*

**Comment by johlju** [comment]
Haha  :laughing:  Sound great that we can get more stuff into this resource :smiley: 

Two comments left, then this is good to go I think.

---

Reviewed 7 of 7 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[CHANGELOG.md, line 28 at r3](https://reviewable.io:443/reviews/powershell/xnetworking/210#-KljTbJEoB9wyuJc5nvE:-KljTbJEoB9wyuJc5nvF:bohkcr3) ([raw file](https://github.com/powershell/xnetworking/blob/fd4024d185b6e8feb9025c0bee7a4ac6ad9784e8/CHANGELOG.md#L28)):*
> ```Markdown
>   - Added Find-NetAdapter cmdlet to NetworkingDsc.Common.
> - Correct example parameters format to meet style guidelines.
> - Find-NetworkAdapter:
> ```

These should move to the unreleased section?  Line 28-33

---

*[Modules/xNetworking/Modules/NetworkingDsc.Common/en-us/NetworkingDsc.Common.strings.psd1, line 3 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/210#-KlZW4VFyy-JpeDgz3aC:-KljUWQMrZctFEo4QBvZ:b-1xgizj) ([raw file](https://github.com/powershell/xnetworking/blob/9802c784dd3b74b263c8599d82fced479c8c73bd/Modules/xNetworking/Modules/NetworkingDsc.Common/en-us/NetworkingDsc.Common.strings.psd1#L3)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The change was not done. And if you change that, change the rest of the strings appropriately as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/210#-:-KljVJ0yNHBilfgl7ncP:b7icc34)*

**Comment by PlagueHO** [comment]
All done! Thanks @Johlju - I also added a missing entry to README.MD.

---

Review status: 8 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[CHANGELOG.md, line 28 at r3](https://reviewable.io:443/reviews/powershell/xnetworking/210#-KljTbJEoB9wyuJc5nvE:-KlkKZ09Xy43VhTE36Fw:bek3jq1) ([raw file](https://github.com/powershell/xnetworking/blob/fd4024d185b6e8feb9025c0bee7a4ac6ad9784e8/CHANGELOG.md#L28)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

These should move to the unreleased section?  Line 28-33
</blockquote></details>

Doh - you're right - not sure how that happened... Fixed.

---

*[Modules/xNetworking/Modules/NetworkingDsc.Common/en-us/NetworkingDsc.Common.strings.psd1, line 3 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/210#-KlZW4VFyy-JpeDgz3aC:-KlkLG4Onn2YBZSTsfN-:b-xjedrp) ([raw file](https://github.com/powershell/xnetworking/blob/9802c784dd3b74b263c8599d82fced479c8c73bd/Modules/xNetworking/Modules/NetworkingDsc.Common/en-us/NetworkingDsc.Common.strings.psd1#L3)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

The change was not done. And if you change that, change the rest of the strings appropriately as well.
</blockquote></details>

Doh! Sorry - I only changed the MSFT_xNetAdapterName.strings.psd1 file.

Fixed now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/210#-:-KlkLMhI_LiCXpq90LRe:bk4py78)*

**Comment by johlju** [comment]
:lgtm:

Great work @PlagueHO! 

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/210#-:-KlmPj4P8LENxVVEDnzt:btz1iod)*

**Comment by PlagueHO** [comment]
Thanks @johlju !

**Pull request merged**
