### PR TITLE
Added .vscode\settings.json with default VS Code PowerShell extension  formatting settings - Fixes #182

### LINKED ISSUE #182: Add "powershell.codeFormatting.openBraceOnSameLine": false to VSCode Workspace
I think we should add a VSCode workspace file to the project and add the "powershell.codeFormatting.openBraceOnSameLine": false setting to it.

### PR DESCRIPTION
**Pull request by PlagueHO**
This PR adds the VS Code PowerShell extension formatting settings that cause PS files to be formatted as per the DSC Resource kit style guidelines.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xnetworking/220)

### CODE REVIEW

**Comment by johlju** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 22 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/220#-KmwKqCv0dBcWW2eW7rI:-KmwKqCv0dBcWW2eW7rJ:b-t7f1ky) ([raw file](https://github.com/powershell/xnetworking/blob/cec5f7a6a58d3f2b13e295a235c1db17f9571963/CHANGELOG.md#L22)):*
> ```Markdown
> - MSFT_xDhcpClient:
>   - Updated example to also cover setting DNS Client to DHCP.
> - Added .vscode\settings.json with default VS Code PowerShell extension formatting
> ```

Use the text in the PR description? It tells more; "... VS Code PowerShell extension formatting settings that cause PowerShell files to be formatted as per the DSC Resource kit style guidelines."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/220)*

**Comment by tysonjhayes** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/220#-:-KmxQuqfKafy4xHfZwLy:bnfp4nl)*

**Comment by PlagueHO** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 22 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/220#-KmwKqCv0dBcWW2eW7rI:-Kmz2UPES60Otc-K9kvY:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/cec5f7a6a58d3f2b13e295a235c1db17f9571963/CHANGELOG.md#L22)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Use the text in the PR description? It tells more; "... VS Code PowerShell extension formatting settings that cause PowerShell files to be formatted as per the DSC Resource kit style guidelines."
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/220)*

**Comment by johlju** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/220)*

**Comment by johlju** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/220#-:-Kn-QF8NxG-TWPfCjgy-:bnfp4nl)*

**Comment by bgelens** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[.vscode/settings.json, line 11 at r3](https://reviewable.io:443/reviews/powershell/xnetworking/220#-Kn0dZoOD6Ol3phrLBXx:-Kn0dZoOD6Ol3phrLBXy:bgcjd8w) ([raw file](https://github.com/powershell/xnetworking/blob/3d5f6973c4444cacb7d4a12ebeb4e6b7e7e5cee4/.vscode/settings.json#L11)):*
> ```JSON
>     "powershell.codeFormatting.whitespaceAfterSeparator": true,
>     "powershell.codeFormatting.ignoreOneLineBlock": false,
>     "powershell.codeFormatting.alignPropertyValuePairs": true,
> ```

I don't believe this is in the style guide?

---

*[.vscode/settings.json, line 13 at r3](https://reviewable.io:443/reviews/powershell/xnetworking/220#-Kn0dh293gx0j7Wtm7B2:-Kn0dh293gx0j7Wtm7B3:b-mg9qrl) ([raw file](https://github.com/powershell/xnetworking/blob/3d5f6973c4444cacb7d4a12ebeb4e6b7e7e5cee4/.vscode/settings.json#L13)):*
> ```JSON
>     "powershell.codeFormatting.alignPropertyValuePairs": true,
>     "files.trimTrailingWhitespace": true,
>     "files.insertFinalNewline": true
> ```

How about format on save? 
You'll have a higher rate of actual formatting being done if this is enabled I think and hopefully saves you/us from a lot of request to format.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/220)*

**Comment by johlju** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[.vscode/settings.json, line 11 at r3](https://reviewable.io:443/reviews/powershell/xnetworking/220#-Kn0dZoOD6Ol3phrLBXx:-Kn0ij7czkQLQde_VZaZ:bjwz5q6) ([raw file](https://github.com/powershell/xnetworking/blob/3d5f6973c4444cacb7d4a12ebeb4e6b7e7e5cee4/.vscode/settings.json#L11)):*
<details><summary><i>Previously, bgelens (Ben Gelens) wrote…</i></summary><blockquote>

I don't believe this is in the style guide?
</blockquote></details>

You are right. I totally missed that one! That is not in the style guideline.

---

*[.vscode/settings.json, line 13 at r3](https://reviewable.io:443/reviews/powershell/xnetworking/220#-Kn0dh293gx0j7Wtm7B2:-Kn0jLUUai5TpCyDikSC:b-f2b720) ([raw file](https://github.com/powershell/xnetworking/blob/3d5f6973c4444cacb7d4a12ebeb4e6b7e7e5cee4/.vscode/settings.json#L13)):*
<details><summary><i>Previously, bgelens (Ben Gelens) wrote…</i></summary><blockquote>

How about format on save? 
You'll have a higher rate of actual formatting being done if this is enabled I think and hopefully saves you/us from a lot of request to format.
</blockquote></details>

Would that format pester tests also? Those should not be formatted automatically. Because they use (must use?) another style. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/220)*

**Comment by johlju** [comment]
@bgelens always good that you comment on things that doesn't seem correct!  👍

**Comment by bgelens** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[.vscode/settings.json, line 13 at r3](https://reviewable.io:443/reviews/powershell/xnetworking/220#-Kn0dh293gx0j7Wtm7B2:-Kn0kNdrOHvBScUC2BjJ:b-7ortxq) ([raw file](https://github.com/powershell/xnetworking/blob/3d5f6973c4444cacb7d4a12ebeb4e6b7e7e5cee4/.vscode/settings.json#L13)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Would that format pester tests also? Those should not be formatted automatically. Because they use (must use?) another style. 
</blockquote></details>

OK

With the pester tests, the curleys that are needed on sameline are scriptblocks bound to a positional parameter (```it -name 'testing  somthing' -Test {scriptblock}```). Simular to ```Foreach-Object -Process``` This is (among other things) why I like K&R over any other style (you don't have to think about it that much) :)

To answer you question, yes I would impact those files if the user adjusts them so better left out.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/220)*

**Comment by PlagueHO** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[.vscode/settings.json, line 11 at r3](https://reviewable.io:443/reviews/powershell/xnetworking/220#-Kn0dZoOD6Ol3phrLBXx:-Kn0zS2GntjwsLzUUJ_6:b-gfzf27) ([raw file](https://github.com/powershell/xnetworking/blob/3d5f6973c4444cacb7d4a12ebeb4e6b7e7e5cee4/.vscode/settings.json#L11)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

You are right. I totally missed that one! That is not in the style guideline.
</blockquote></details>

You are correct. I have removed this one - and in my other repo PRs.

---

*[.vscode/settings.json, line 13 at r3](https://reviewable.io:443/reviews/powershell/xnetworking/220#-Kn0dh293gx0j7Wtm7B2:-Kn1-Sn1_5BkDBb6Q7lx:b-t3yz5u) ([raw file](https://github.com/powershell/xnetworking/blob/3d5f6973c4444cacb7d4a12ebeb4e6b7e7e5cee4/.vscode/settings.json#L13)):*
<details><summary><i>Previously, bgelens (Ben Gelens) wrote…</i></summary><blockquote>

OK

With the pester tests, the curleys that are needed on sameline are scriptblocks bound to a positional parameter (```it -name 'testing  somthing' -Test {scriptblock}```). Simular to ```Foreach-Object -Process``` This is (among other things) why I like K&R over any other style (you don't have to think about it that much) :)

To answer you question, yes I would impact those files if the user adjusts them so better left out.
</blockquote></details>

To clarify this: `It { ... }` is script parameter rather than a control block (like `if { ... }` or `function { ... }` ), which the VS Code extension is smart enough to know not to change. So I think all .PS1 files (tests or not) can be run through this formatting process. I adopted this using my new FileContentDsc resource module from the start and it has not caused problems on Tests or Modules or PSD1 files.

As for Format on Save, I'm ok with doing this personally - but probably better for a larger discussion and could be adopted separately.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/220)*

**Comment by johlju** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[.vscode/settings.json, line 13 at r3](https://reviewable.io:443/reviews/powershell/xnetworking/220#-Kn0dh293gx0j7Wtm7B2:-Kn11T9_CFZOP7nXZxFf:bbfu6c3) ([raw file](https://github.com/powershell/xnetworking/blob/3d5f6973c4444cacb7d4a12ebeb4e6b7e7e5cee4/.vscode/settings.json#L13)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

To clarify this: `It { ... }` is script parameter rather than a control block (like `if { ... }` or `function { ... }` ), which the VS Code extension is smart enough to know not to change. So I think all .PS1 files (tests or not) can be run through this formatting process. I adopted this using my new FileContentDsc resource module from the start and it has not caused problems on Tests or Modules or PSD1 files.

As for Format on Save, I'm ok with doing this personally - but probably better for a larger discussion and could be adopted separately.
</blockquote></details>

I'm all for it as well, if it as smart as you say. :smile: Not familiar with it, but would save a lot of time for style review comments if it was fixed on save. I will turn it on in xSQLServer (my local copy) and see how it goes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/220)*

**Comment by tysonjhayes** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/220)*

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/220#-:-Kn14ysb3NSPSjhU_5Zp:bnfp4nl)*

**Comment by PlagueHO** [comment]
Hi @bgelens - any chance you could sign this change off for me? Cheers sir!

**Comment by bgelens** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/220#-:-Kn3QBAiq5kqrnhfqT9W:bnfp4nl)*

**Pull request merged**
