### PR TITLE
Added MSFT_xNetworkTeamInterface resource

### PR DESCRIPTION
**Pull request by rakkhin**
* Added the following resources:
    * MSFT_xNetworkTeamInterface resource to add/remove network team interfaces
* Added conditional loading of LocalizedData to MSFT_xHostsFile and MSFT_xNetworkTeam to prevent failures while loading those resources on systems with $PSUICulture other than en-US

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xnetworking/128)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Are you able to create Unit tests as well for the xNetworkTeamInterface resource?

Are we able to add some examples of using this Resource (both in the Readme.md and in the Examples folder) - especially in conjunction with using the xNetworkTeam resource? 

This is a great job BTW and a very long needed resource! Thank you very much for submitting it!

---

Reviewed 6 of 6 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1, line 4 \[r2\]](https://reviewable.io:443/reviews/powershell/xnetworking/128#-KMGcTYCu4084U22cdJG:-KMGcTYDrUrIKow7HUJ4:1037288806) ([raw file](https://github.com/powershell/xnetworking/blob/fc8cadc3e4aca044a5c86ec9eff4c38083b51599/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1#L4)):*
> ```PowerShell
> if (Test-Path "${PSScriptRoot}\${PSUICulture}")
> {
>     Import-LocalizedData -BindingVariable LocalizedData -filename MSFT_xHostsFile.psd1 -BaseDirectory "${PSScriptRoot}\${PSUICulture}"
> ```

Is it possible to get this line down to less than 100 chars? Thank you! :smile:

---

*[DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1, line 9 \[r2\]](https://reviewable.io:443/reviews/powershell/xnetworking/128#-KMGcjS8RPspDWmycyUS:-KMGcjS8RPspDWmycyUT:1037288806) ([raw file](https://github.com/powershell/xnetworking/blob/fc8cadc3e4aca044a5c86ec9eff4c38083b51599/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1#L9)):*
> ```PowerShell
> {
>     #fallback to en-US
>     Import-LocalizedData -BindingVariable LocalizedData -filename MSFT_xHostsFile.psd1 -BaseDirectory "${PSScriptRoot}\en-US"
> ```

Is it possible to get this line down to less than 100 chars? Thank you! :smile:

---

*[DSCResources/MSFT_xNetworkTeam/MSFT_xNetworkTeam.psm1, line 4 \[r2\]](https://reviewable.io:443/reviews/powershell/xnetworking/128#-KMGcmTML63WN5e9D9wi:-KMGcmTN9BGSqN7n50kw:1037288806) ([raw file](https://github.com/powershell/xnetworking/blob/fc8cadc3e4aca044a5c86ec9eff4c38083b51599/DSCResources/MSFT_xNetworkTeam/MSFT_xNetworkTeam.psm1#L4)):*
> ```PowerShell
> if (Test-Path "${PSScriptRoot}\${PSUICulture}")
> {
>     Import-LocalizedData -BindingVariable LocalizedData -filename MSFT_xNetworkTeam.psd1 -BaseDirectory "${PSScriptRoot}\${PSUICulture}"
> ```

Is it possible to get this line down to less than 100 chars? Thank you! :smile:

---

*[DSCResources/MSFT_xNetworkTeam/MSFT_xNetworkTeam.psm1, line 9 \[r2\]](https://reviewable.io:443/reviews/powershell/xnetworking/128#-KMGcmtV4AYi6HsP-qe8:-KMGcmtV4AYi6HsP-qe9:1037288806) ([raw file](https://github.com/powershell/xnetworking/blob/fc8cadc3e4aca044a5c86ec9eff4c38083b51599/DSCResources/MSFT_xNetworkTeam/MSFT_xNetworkTeam.psm1#L9)):*
> ```PowerShell
> {
>     #fallback to en-US
>     Import-LocalizedData -BindingVariable LocalizedData -filename MSFT_xNetworkTeam.psd1 -BaseDirectory "${PSScriptRoot}\en-US"
> ```

Is it possible to get this line down to less than 100 chars? Thank you! :smile:

---

*[DSCResources/MSFT_xNetworkTeamInterface/MSFT_xNetworkTeamInterface.psm1, line 4 \[r2\]](https://reviewable.io:443/reviews/powershell/xnetworking/128#-KMGcul6AU6N1uOaBat1:-KMGcul6AU6N1uOaBat2:1037288806) ([raw file](https://github.com/powershell/xnetworking/blob/fc8cadc3e4aca044a5c86ec9eff4c38083b51599/DSCResources/MSFT_xNetworkTeamInterface/MSFT_xNetworkTeamInterface.psm1#L4)):*
> ```PowerShell
> if (Test-Path "${PSScriptRoot}\${PSUICulture}")
> {
>     Import-LocalizedData -BindingVariable LocalizedData -filename MSFT_xNetworkTeamInterface.psd1 -BaseDirectory "${PSScriptRoot}\${PSUICulture}"
> ```

Is it possible to get this line down to less than 100 chars? Thank you! :smile:

---

*[DSCResources/MSFT_xNetworkTeamInterface/MSFT_xNetworkTeamInterface.psm1, line 9 \[r2\]](https://reviewable.io:443/reviews/powershell/xnetworking/128#-KMGcvCZ-VLihSwfyDXh:-KMGcvCZ-VLihSwfyDXi:1037288806) ([raw file](https://github.com/powershell/xnetworking/blob/fc8cadc3e4aca044a5c86ec9eff4c38083b51599/DSCResources/MSFT_xNetworkTeamInterface/MSFT_xNetworkTeamInterface.psm1#L9)):*
> ```PowerShell
> {
>     #fallback to en-US
>     Import-LocalizedData -BindingVariable LocalizedData -filename MSFT_xNetworkTeamInterface.psd1 -BaseDirectory "${PSScriptRoot}\en-US"
> ```

Is it possible to get this line down to less than 100 chars? Thank you! :smile:

---

*[DSCResources/MSFT_xNetworkTeamInterface/MSFT_xNetworkTeamInterface.psm1, line 95 \[r2\]](https://reviewable.io:443/reviews/powershell/xnetworking/128#-KMGd4xEM8dYef9VlzMr:-KMGd4xEM8dYef9VlzMs:1037288806) ([raw file](https://github.com/powershell/xnetworking/blob/fc8cadc3e4aca044a5c86ec9eff4c38083b51599/DSCResources/MSFT_xNetworkTeamInterface/MSFT_xNetworkTeamInterface.psm1#L95)):*
> ```PowerShell
>                 else
>                 {
>                     Set-NetLbfoTeamNic -Name $Name -Team $TeamName -VlanID $VlanID -ErrorAction Stop -Confirm:$false -PassThru `
> ```

Is it possible to get this line down to less than 100 chars? Thank you! :smile:

---

*[DSCResources/MSFT_xNetworkTeamInterface/MSFT_xNetworkTeamInterface.psm1, line 107 \[r2\]](https://reviewable.io:443/reviews/powershell/xnetworking/128#-KMGgSgD2zxzANvEzYOZ:-KMGgSgD2zxzANvEzYO_:1037288806) ([raw file](https://github.com/powershell/xnetworking/blob/fc8cadc3e4aca044a5c86ec9eff4c38083b51599/DSCResources/MSFT_xNetworkTeamInterface/MSFT_xNetworkTeamInterface.psm1#L107)):*
> ```PowerShell
>                 if ($VlanID -ne 0)
>                 {
>                     $null = Add-NetLbfoTeamNic -Name $Name -Team $TeamName -VlanID $VlanID -ErrorAction Stop -Confirm:$false
> ```

Is it possible to get this line down to less than 100 chars? Thank you! :smile:

---

*[DSCResources/MSFT_xNetworkTeamInterface/MSFT_xNetworkTeamInterface.psm1, line 117 \[r2\]](https://reviewable.io:443/reviews/powershell/xnetworking/128#-KMGeNocwDpq7r9ykleJ:-KMGeNodLEqUzJuFYG15:523453781) ([raw file](https://github.com/powershell/xnetworking/blob/fc8cadc3e4aca044a5c86ec9eff4c38083b51599/DSCResources/MSFT_xNetworkTeamInterface/MSFT_xNetworkTeamInterface.psm1#L117)):*
> ```PowerShell
>             catch
>             {
>                 $errorId = "TeamNicCreateError"
> ```

Could we move this code into the else block above remove the try...catch block entirely? It seems like we might be obfuscating any other possible errors that might occur here while creating the team.

---

*[Tests/Integration/MSFT_xNetworkTeamInterface.Integration.Tests.ps1, line 8 \[r2\]](https://reviewable.io:443/reviews/powershell/xnetworking/128#-KMGg61EPbcGfS9Knw7e:-KMGg61EPbcGfS9Knw7f:1210147459) ([raw file](https://github.com/powershell/xnetworking/blob/fc8cadc3e4aca044a5c86ec9eff4c38083b51599/Tests/Integration/MSFT_xNetworkTeamInterface.Integration.Tests.ps1#L8)):*
> ```PowerShell
> $Global:teamMembers        = (Get-NetAdapter -Physical).Name
> 
> #region HEADER
> ```

Can you please update the header to the latest version from the template here https://github.com/PowerShell/DscResources/blob/master/Tests.Template/integration_template.ps1

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/128#-:-KMGeimJjUr4Rxn934P5:-1954326615)*

**Comment by rakkhin** [comment]
Review status: 4 of 9 files reviewed at latest revision, 10 unresolved discussions.

---

*[DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1, line 4 \[r2\]](https://reviewable.io:443/reviews/powershell/xnetworking/128#-KMGcTYCu4084U22cdJG:-KMJD_THUHvV9_NzeWVr:-499146009) ([raw file](https://github.com/powershell/xnetworking/blob/fc8cadc3e4aca044a5c86ec9eff4c38083b51599/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1#L4)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> Is it possible to get this line down to less than 100 chars? Thank you! :smile:
</details>
Done.

---

*[DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1, line 9 \[r2\]](https://reviewable.io:443/reviews/powershell/xnetworking/128#-KMGcjS8RPspDWmycyUS:-KMJDaix7fqwL2aLGBpJ:-499146009) ([raw file](https://github.com/powershell/xnetworking/blob/fc8cadc3e4aca044a5c86ec9eff4c38083b51599/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1#L9)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> Is it possible to get this line down to less than 100 chars? Thank you! :smile:
</details>
Done.

---

*[DSCResources/MSFT_xNetworkTeam/MSFT_xNetworkTeam.psm1, line 4 \[r2\]](https://reviewable.io:443/reviews/powershell/xnetworking/128#-KMGcmTML63WN5e9D9wi:-KMJDcINFlgCMZ80cnzP:-499146009) ([raw file](https://github.com/powershell/xnetworking/blob/fc8cadc3e4aca044a5c86ec9eff4c38083b51599/DSCResources/MSFT_xNetworkTeam/MSFT_xNetworkTeam.psm1#L4)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> Is it possible to get this line down to less than 100 chars? Thank you! :smile:
</details>
Done.

---

*[DSCResources/MSFT_xNetworkTeam/MSFT_xNetworkTeam.psm1, line 9 \[r2\]](https://reviewable.io:443/reviews/powershell/xnetworking/128#-KMGcmtV4AYi6HsP-qe8:-KMJDeWM_SRaIdJZAg-n:-499146009) ([raw file](https://github.com/powershell/xnetworking/blob/fc8cadc3e4aca044a5c86ec9eff4c38083b51599/DSCResources/MSFT_xNetworkTeam/MSFT_xNetworkTeam.psm1#L9)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> Is it possible to get this line down to less than 100 chars? Thank you! :smile:
</details>
Done.

---

*[DSCResources/MSFT_xNetworkTeamInterface/MSFT_xNetworkTeamInterface.psm1, line 4 \[r2\]](https://reviewable.io:443/reviews/powershell/xnetworking/128#-KMGcul6AU6N1uOaBat1:-KMJDft8CJzXF3iNnvvK:-499146009) ([raw file](https://github.com/powershell/xnetworking/blob/fc8cadc3e4aca044a5c86ec9eff4c38083b51599/DSCResources/MSFT_xNetworkTeamInterface/MSFT_xNetworkTeamInterface.psm1#L4)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> Is it possible to get this line down to less than 100 chars? Thank you! :smile:
</details>
Done.

---

*[DSCResources/MSFT_xNetworkTeamInterface/MSFT_xNetworkTeamInterface.psm1, line 9 \[r2\]](https://reviewable.io:443/reviews/powershell/xnetworking/128#-KMGcvCZ-VLihSwfyDXh:-KMJDgPraEjv-8eZHwAa:-499146009) ([raw file](https://github.com/powershell/xnetworking/blob/fc8cadc3e4aca044a5c86ec9eff4c38083b51599/DSCResources/MSFT_xNetworkTeamInterface/MSFT_xNetworkTeamInterface.psm1#L9)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> Is it possible to get this line down to less than 100 chars? Thank you! :smile:
</details>
Done.

---

*[DSCResources/MSFT_xNetworkTeamInterface/MSFT_xNetworkTeamInterface.psm1, line 95 \[r2\]](https://reviewable.io:443/reviews/powershell/xnetworking/128#-KMGd4xEM8dYef9VlzMr:-KMJDia-Pgl-ARSkkpu9:-499146009) ([raw file](https://github.com/powershell/xnetworking/blob/fc8cadc3e4aca044a5c86ec9eff4c38083b51599/DSCResources/MSFT_xNetworkTeamInterface/MSFT_xNetworkTeamInterface.psm1#L95)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> Is it possible to get this line down to less than 100 chars? Thank you! :smile:
</details>
Done.

---

*[DSCResources/MSFT_xNetworkTeamInterface/MSFT_xNetworkTeamInterface.psm1, line 107 \[r2\]](https://reviewable.io:443/reviews/powershell/xnetworking/128#-KMGgSgD2zxzANvEzYOZ:-KMJDlP0_t2Jvdg_FMY7:-499146009) ([raw file](https://github.com/powershell/xnetworking/blob/fc8cadc3e4aca044a5c86ec9eff4c38083b51599/DSCResources/MSFT_xNetworkTeamInterface/MSFT_xNetworkTeamInterface.psm1#L107)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> Is it possible to get this line down to less than 100 chars? Thank you! :smile:
</details>
Done.

---

*[DSCResources/MSFT_xNetworkTeamInterface/MSFT_xNetworkTeamInterface.psm1, line 117 \[r2\]](https://reviewable.io:443/reviews/powershell/xnetworking/128#-KMGeNocwDpq7r9ykleJ:-KMJDoeUTZk1pCls3RkW:-499146009) ([raw file](https://github.com/powershell/xnetworking/blob/fc8cadc3e4aca044a5c86ec9eff4c38083b51599/DSCResources/MSFT_xNetworkTeamInterface/MSFT_xNetworkTeamInterface.psm1#L117)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> Could we move this code into the else block above remove the try...catch block entirely? It seems like we might be obfuscating any other possible errors that might occur here while creating the team.
</details>
Done.

---

*[Tests/Integration/MSFT_xNetworkTeamInterface.Integration.Tests.ps1, line 8 \[r2\]](https://reviewable.io:443/reviews/powershell/xnetworking/128#-KMGg61EPbcGfS9Knw7e:-KMJDrXFBpGrYFCYCQWS:-499146009) ([raw file](https://github.com/powershell/xnetworking/blob/fc8cadc3e4aca044a5c86ec9eff4c38083b51599/Tests/Integration/MSFT_xNetworkTeamInterface.Integration.Tests.ps1#L8)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> Can you please update the header to the latest version from the template here https://github.com/PowerShell/DscResources/blob/master/Tests.Template/integration_template.ps1
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/128)*

**Comment by PlagueHO** [comment]
Nice work! Thanks @rakkhin! Really appreciate the work you put in here. @Tysonjhayes, this one is looking pretty good to me. Any chance you could give it a review when you get a moment and throw a merge our way? :smile:

---

Reviewed 9 of 9 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/128#-:-KNBYW3XqrGUwv_AgAsq:-1923552277)*

**Comment by PlagueHO** [comment]
Hi @rakkhin - there are some merge conflicts to fix on this PR before it can be merged. Are you able to resolve so I can get @tysonjhayes to look it over and merge it for you? Thanks!

**Comment by PlagueHO** [comment]
@rakkhin - are you able to take a look at the merge conflicts so someone can merge this for you?

**Comment by rakkhin** [comment]
Sorry it took me so long, should be ok now. Let me know if there's anything else I should do.

**Comment by PlagueHO** [comment]
No worries @rakkhin - thanks for submitting the change! @Tysonjhayes, are you able to give this a once over and merge? Thank you!

---

Reviewed 1 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/128#-:-KPMKO08omFz2wKuD3xB:b-dswdf0)*

**Comment by TravisEz13** [comment]
I reviewed the schema and it looks good.

---

Reviewed 1 of 6 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/128#-:-KPy686n4YmZyucQcWBR:be786ak)*

**Comment by PlagueHO** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/128#-:-KQ-YW1TYsVWiRYN6L9d:bnfp4nl)*

**Pull request merged**
