### PR TITLE
Add xNetAdapterBinding Resource - Fixes #116

### LINKED ISSUE #116: [New Resource] xNetAdapterBinding
Add a new resource for enabling/disabling Net Adapter binding on specific Adapters. This would be mainly used for disabling the "Client for Microsoft Networks" or other similar bindings.

It would use the:
```Get-NetAdapterBinding``` and ```Set-NetAdapterBinding``` cmdlets.

### PR DESCRIPTION
**Pull request by PlagueHO**
Fixes #116 

Adds xNetAdapterBinding resource.

This resource is just used to enable or disable components (e.g. IPv4, IPv6) from a network adapter.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xnetworking/120)

### CODE REVIEW

**Comment by tysonjhayes** [comment]
Reviewed 4 of 7 files at r1.
Review status: 4 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[DSCResources/MSFT_xNetAdapterBinding/MSFT_xNetAdapterBinding.psm1, line 31 \[r1\]](https://reviewable.io:443/reviews/powershell/xnetworking/120#-KIcl-A3AawBr4nh4fX8:-KIcl-A4WEQr7AoM3tzm:1731377067) ([raw file](https://github.com/powershell/xnetworking/blob/fb24dc865c75c9eb3b6f8c711862cf5ff99ba53a/DSCResources/MSFT_xNetAdapterBinding/MSFT_xNetAdapterBinding.psm1#L31)):*
> ```PowerShell
> 
>         [ValidateSet('Enabled', 'Disabled')]
>         [String]$EnsureEnabled = 'Enabled'
> ```

Kind of dislike this parameter name, just seems clunky, but I'm not coming up with any good suggestions. State maybe?

---

*[DSCResources/MSFT_xNetAdapterBinding/MSFT_xNetAdapterBinding.psm1, line 84 \[r1\]](https://reviewable.io:443/reviews/powershell/xnetworking/120#-KIclB7BqiHWD0nZYGaM:-KIclB7BqiHWD0nZYGaN:-303810295) ([raw file](https://github.com/powershell/xnetworking/blob/fb24dc865c75c9eb3b6f8c711862cf5ff99ba53a/DSCResources/MSFT_xNetAdapterBinding/MSFT_xNetAdapterBinding.psm1#L84)):*
> ```PowerShell
>     if ($EnsureEnabled -eq 'Enabled')
>     {
>         $CurrentNetAdapterBinding | Enable-NetAdapterBinding
> ```

I think best practice would be to use ````Enable-NetAdapterBinding```` then specify all the parameters instead of using the pipe or implied parameters.

---

*[DSCResources/MSFT_xNetAdapterBinding/MSFT_xNetAdapterBinding.psm1, line 143 \[r1\]](https://reviewable.io:443/reviews/powershell/xnetworking/120#-KIcrA8-fI5v6M3t4isS:-KIcrA80kteXpjzpMZ_w:2029162112) ([raw file](https://github.com/powershell/xnetworking/blob/fb24dc865c75c9eb3b6f8c711862cf5ff99ba53a/DSCResources/MSFT_xNetAdapterBinding/MSFT_xNetAdapterBinding.psm1#L143)):*
> ```PowerShell
>                 $InterfaceAlias,$ComponentId,$EnsureEnabled,$CurrentEnabled)
>             ) -join '' )
>         $desiredConfigurationMatch = $false
> ```

We could just do a return here (and in the else statement) which would remove the need for the $desiredConfigurationMatch variable

---

*[DSCResources/MSFT_xNetAdapterBinding/MSFT_xNetAdapterBinding.psm1, line 193 \[r1\]](https://reviewable.io:443/reviews/powershell/xnetworking/120#-KIclybzFj43SOdPN7-B:-KIclybzFj43SOdPN7-C:2066952062) ([raw file](https://github.com/powershell/xnetworking/blob/fb24dc865c75c9eb3b6f8c711862cf5ff99ba53a/DSCResources/MSFT_xNetAdapterBinding/MSFT_xNetAdapterBinding.psm1#L193)):*
> ```PowerShell
> 
>     return $Binding
> } # Test-ResourceProperty
> ```

Looks like you renamed the function, probably should change this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/120)*

**Comment by PlagueHO** [comment]
Review status: 4 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[DSCResources/MSFT_xNetAdapterBinding/MSFT_xNetAdapterBinding.psm1, line 31 \[r1\]](https://reviewable.io:443/reviews/powershell/xnetworking/120#-KIcl-A3AawBr4nh4fX8:-KIfnY1zDX-n1AYs0OsC:-425100176) ([raw file](https://github.com/powershell/xnetworking/blob/fb24dc865c75c9eb3b6f8c711862cf5ff99ba53a/DSCResources/MSFT_xNetAdapterBinding/MSFT_xNetAdapterBinding.psm1#L31)):*
<details><summary><i>Previously, tysonjhayes (Tyson J. Hayes) wrote…</i></summary>
> Kind of dislike this parameter name, just seems clunky, but I'm not coming up with any good suggestions. State maybe?
</details>
I fully agree. I just took a look at what we'd done with MSFT_xFirewall and we did this:
[Write, Description("Enable or disable the supplied configuration"), ValueMap{"True", "False"},Values{"True", "False"}] string Enabled;

Perhaps we could use that the same thing for consistency within the module? Will take your call on this one.

---

*[DSCResources/MSFT_xNetAdapterBinding/MSFT_xNetAdapterBinding.psm1, line 84 \[r1\]](https://reviewable.io:443/reviews/powershell/xnetworking/120#-KIclB7BqiHWD0nZYGaM:-KIfoEysa2EF9iqITawl:1695944835) ([raw file](https://github.com/powershell/xnetworking/blob/fb24dc865c75c9eb3b6f8c711862cf5ff99ba53a/DSCResources/MSFT_xNetAdapterBinding/MSFT_xNetAdapterBinding.psm1#L84)):*
<details><summary><i>Previously, tysonjhayes (Tyson J. Hayes) wrote…</i></summary>
> I think best practice would be to use ````Enable-NetAdapterBinding```` then specify all the parameters instead of using the pipe or implied parameters.
</details>
Cool! Done - simplifies the Unit test code too :smile:

---

*[DSCResources/MSFT_xNetAdapterBinding/MSFT_xNetAdapterBinding.psm1, line 143 \[r1\]](https://reviewable.io:443/reviews/powershell/xnetworking/120#-KIcrA8-fI5v6M3t4isS:-KIfrLCwre3N4Pve9q-J:-499146009) ([raw file](https://github.com/powershell/xnetworking/blob/fb24dc865c75c9eb3b6f8c711862cf5ff99ba53a/DSCResources/MSFT_xNetAdapterBinding/MSFT_xNetAdapterBinding.psm1#L143)):*
<details><summary><i>Previously, tysonjhayes (Tyson J. Hayes) wrote…</i></summary>
> We could just do a return here (and in the else statement) which would remove the need for the $desiredConfigurationMatch variable
</details>
Done.

---

*[DSCResources/MSFT_xNetAdapterBinding/MSFT_xNetAdapterBinding.psm1, line 193 \[r1\]](https://reviewable.io:443/reviews/powershell/xnetworking/120#-KIclybzFj43SOdPN7-B:-KIfroqZ2ZNcqHSuJJlU:701194249) ([raw file](https://github.com/powershell/xnetworking/blob/fb24dc865c75c9eb3b6f8c711862cf5ff99ba53a/DSCResources/MSFT_xNetAdapterBinding/MSFT_xNetAdapterBinding.psm1#L193)):*
<details><summary><i>Previously, tysonjhayes (Tyson J. Hayes) wrote…</i></summary>
> Looks like you renamed the function, probably should change this.
</details>
Excellent catch there! Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/120)*

**Comment by PlagueHO** [comment]
Review status: 4 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[DSCResources/MSFT_xNetAdapterBinding/MSFT_xNetAdapterBinding.psm1, line 31 \[r1\]](https://reviewable.io:443/reviews/powershell/xnetworking/120#-KIcl-A3AawBr4nh4fX8:-KJ4rj8VNyEMUc-lmnxJ:-2135806006) ([raw file](https://github.com/powershell/xnetworking/blob/fb24dc865c75c9eb3b6f8c711862cf5ff99ba53a/DSCResources/MSFT_xNetAdapterBinding/MSFT_xNetAdapterBinding.psm1#L31)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> I fully agree. I just took a look at what we'd done with MSFT_xFirewall and we did this:
> [Write, Description("Enable or disable the supplied configuration"), ValueMap{"True", "False"},Values{"True", "False"}] string Enabled;
> 
> Perhaps we could use that the same thing for consistency within the module? Will take your call on this one.
</details>
@Tysonjhayes- any thoughts on if I should change this over to the xFirewall style or use your proposed "State" parameter?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/120)*

**Comment by PlagueHO** [comment]
Review status: 0 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[DSCResources/MSFT_xNetAdapterBinding/MSFT_xNetAdapterBinding.psm1, line 31 \[r1\]](https://reviewable.io:443/reviews/powershell/xnetworking/120#-KIcl-A3AawBr4nh4fX8:-KJSkn1o2VJTAEyGkGjO:1317522999) ([raw file](https://github.com/powershell/xnetworking/blob/fb24dc865c75c9eb3b6f8c711862cf5ff99ba53a/DSCResources/MSFT_xNetAdapterBinding/MSFT_xNetAdapterBinding.psm1#L31)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> @Tysonjhayes- any thoughts on if I should change this over to the xFirewall style or use your proposed "State" parameter?
</details>
Hi @tysonjhayes - I reckon resource module consistency is probably best so I've renamed this parameter to "State" to keep t consistent with the xFirewall resource. All other changes should be complete now. Cheers sir!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/120)*

**Comment by tysonjhayes** [comment]
Reviewed 7 of 7 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/120)*

**Pull request merged**
