### PR TITLE
Created new xProxySettings resource configuring proxy settings - Fixes #158

### LINKED ISSUE #158: [New Resource] Proxy Server management
This has come up in a few places on the internet, but we don't have a complete solution on the gallery today. (http://stackoverflow.com/questions/29600767/setting-the-machine-proxy-via-dsc , https://p0w3rsh3ll.wordpress.com/2015/01/29/dsc-configuring-a-proxy/, https://p0w3rsh3ll.wordpress.com/2015/02/16/follow-up-configuring-a-proxy-with-dsc/)
This has come up as a request for Nano Server as well. 

I should be able to manage proxy server settings on Nano Server using DSC.

### PR DESCRIPTION
**Pull request by PlagueHO**
**Pull Request (PR) description**
Created new xProxySettings resource configuring proxy settings

**This Pull Request (PR) fixes the following issues:**
Fixes #158

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [x] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [x] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xnetworking/270)

### CODE REVIEW

**Comment by PlagueHO** [comment]
@Johlju - I don't suppose you could review this one if you get a chance at some point? It is a bit of a large one, so no rush at all. Thanks sir!

**Comment by johlju** [comment]
Reviewed 13 of 14 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[Modules/xNetworking/DSCResources/MSFT_xProxySettings/MSFT_xProxySettings.psm1, line 27 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/270#-KwPYgHi8qyFVkjF1n2p:-KwPYgHi8qyFVkjF1n2q:b-rmk1e) ([raw file](https://github.com/powershell/xnetworking/blob/d82db55c4f9e98524fa57c72bff449bdde8d28c4/Modules/xNetworking/DSCResources/MSFT_xProxySettings/MSFT_xProxySettings.psm1#L27)):*
> ```PowerShell
>         the computer.
> 
>     .PARAMETER IsSingleInstance
> ```

Not thought of it before, for the single instance resources, but think we should add 'Not used in Get-TargetResource' as of https://github.com/PowerShell/DscResources/blob/master/BestPractices.md#any-unused-parameters-that-must-be-included-in-a-function-definition-should-include-not-used-in-function_name-in-the-help-comment-for-that-parameter-in-the-comment-based-help

---

*[Modules/xNetworking/DSCResources/MSFT_xProxySettings/MSFT_xProxySettings.psm1, line 214 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/270#-KwPXdULLbTWaiuOnbUQ:-KwPXdUMUFy-XqH0CAZM:bmnm42a) ([raw file](https://github.com/powershell/xnetworking/blob/d82db55c4f9e98524fa57c72bff449bdde8d28c4/Modules/xNetworking/DSCResources/MSFT_xProxySettings/MSFT_xProxySettings.psm1#L214)):*
> ```PowerShell
> 
>         # Generate the Proxy Settings binary value
>         $null = $PSBoundParameters.Remove('IsSingleInstance')
> ```

Nitpick. Non-blocking. :smile: 
Wouldn't it be better if we would clone `$PSBoundParameters` into a new variable `$convertToProxySettingsBinaryParameters` and remove the unnecessary parameters in that variable. Preserving `$PSBoundParameters` to be potentially evaluated later in the code.

---

*[Modules/xNetworking/DSCResources/MSFT_xProxySettings/MSFT_xProxySettings.psm1, line 345 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/270#-KwPZ6lyrK-6IH6NhG5m:-KwPZ6lyrK-6IH6NhG5n:b-xsnnni) ([raw file](https://github.com/powershell/xnetworking/blob/d82db55c4f9e98524fa57c72bff449bdde8d28c4/Modules/xNetworking/DSCResources/MSFT_xProxySettings/MSFT_xProxySettings.psm1#L345)):*
> [Boolean]

[System.Boolean]

---

*[Modules/xNetworking/DSCResources/MSFT_xProxySettings/MSFT_xProxySettings.psm1, line 383 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/270#-KwPZLRixf2pgl6iPenE:-KwPZLRixf2pgl6iPenF:b-9psso7) ([raw file](https://github.com/powershell/xnetworking/blob/d82db55c4f9e98524fa57c72bff449bdde8d28c4/Modules/xNetworking/DSCResources/MSFT_xProxySettings/MSFT_xProxySettings.psm1#L383)):*
> ```PowerShell
>     else
>     {
>         $desiredValues = $PSBoundParameters
> ```

We should clone here to preserve the values in `$PSBoundParameters`. This is one time where PowerShell jumps over to use "pointers". I think this current method will remove the keys from `$PSBoundParameters` even when the keys are removed from the `$desiredValues`.

```powershell
PS > $a = @{}
PS > $a['Name1'] = 'Denise'
PS > $a['Name2'] = 'John'
PS > $b = $a
PS > $b.Remove('Name2')
PS > $a

Name                           Value
----                           -----
Name1                          Denise
```

---

*[Modules/xNetworking/DSCResources/MSFT_xProxySettings/MSFT_xProxySettings.psm1, line 384 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/270#-KwPaX9cZ_dK5wkoCN8X:-KwPaX9cZ_dK5wkoCN8Y:b-xxiuxb) ([raw file](https://github.com/powershell/xnetworking/blob/d82db55c4f9e98524fa57c72bff449bdde8d28c4/Modules/xNetworking/DSCResources/MSFT_xProxySettings/MSFT_xProxySettings.psm1#L384)):*
> $null 

Can we remove `$null` from these?

---

*[Modules/xNetworking/DSCResources/MSFT_xProxySettings/MSFT_xProxySettings.psm1, line 484 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/270#-KwPbOa6nCu94eG9ON1l:-KwPbOa6nCu94eG9ON1m:b-3nin3h) ([raw file](https://github.com/powershell/xnetworking/blob/d82db55c4f9e98524fa57c72bff449bdde8d28c4/Modules/xNetworking/DSCResources/MSFT_xProxySettings/MSFT_xProxySettings.psm1#L484)):*
> Current

current (lower-case 'c')

---

*[Modules/xNetworking/DSCResources/MSFT_xProxySettings/en-US/MSFT_xProxySettings.strings.psd1, line 12 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/270#-KwPc7DWo3LlM4Ofnv_o:-KwPc7DWo3LlM4Ofnv_p:bqrv89c) ([raw file](https://github.com/powershell/xnetworking/blob/d82db55c4f9e98524fa57c72bff449bdde8d28c4/Modules/xNetworking/DSCResources/MSFT_xProxySettings/en-US/MSFT_xProxySettings.strings.psd1#L12)):*
> proxy setting '{0}'

Some uses  tick (') around the value, some don't. We should be consequent.

---

*[Tests/Integration/MSFT_xProxySettings.Integration.Tests.ps1, line 53 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/270#-KwPdCnkQCWFppNOteUn:-KwPdCnkQCWFppNOteUo:b-iqa19c) ([raw file](https://github.com/powershell/xnetworking/blob/d82db55c4f9e98524fa57c72bff449bdde8d28c4/Tests/Integration/MSFT_xProxySettings.Integration.Tests.ps1#L53)):*
> ```PowerShell
>                     -OutputPath $TestDrive `
>                     -ConfigurationData $configData
>                 Start-DscConfiguration `
> ```

Blank row before this one.

---

*[Tests/Integration/MSFT_xProxySettings.Integration.Tests.ps1, line 60 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/270#-KwPdK_RegnhODrEw9sr:-KwPdK_RegnhODrEw9ss:b9kxk7s) ([raw file](https://github.com/powershell/xnetworking/blob/d82db55c4f9e98524fa57c72bff449bdde8d28c4/Tests/Integration/MSFT_xProxySettings.Integration.Tests.ps1#L60)):*
> not throw

`Not Throw`. Thorughout.

---

*[Tests/Integration/MSFT_xProxySettings.Integration.Tests.ps1, line 64 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/270#-KwPdHD0iut_qn99YECL:-KwPdHD0iut_qn99YECM:b-u9zm84) ([raw file](https://github.com/powershell/xnetworking/blob/d82db55c4f9e98524fa57c72bff449bdde8d28c4/Tests/Integration/MSFT_xProxySettings.Integration.Tests.ps1#L64)):*
> throw

Throw (upper 'T')

---

*[Tests/Unit/MSFT_xProxySettings.Tests.ps1, line 125 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/270#-KwPe50CxO8UGt2MhgkJ:-KwPe50CxO8UGt2MhgkK:beifpad) ([raw file](https://github.com/powershell/xnetworking/blob/d82db55c4f9e98524fa57c72bff449bdde8d28c4/Tests/Unit/MSFT_xProxySettings.Tests.ps1#L125)):*
> ```PowerShell
>                     } `
>                     -Verifiable
>                 Mock `
> ```

Blank row before this one. Throughout.

---

*[Tests/Unit/MSFT_xProxySettings.Tests.ps1, line 351 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/270#-KwPeToqc5ZAR4bFbh4Q:-KwPeToqc5ZAR4bFbh4R:by5tsis) ([raw file](https://github.com/powershell/xnetworking/blob/d82db55c4f9e98524fa57c72bff449bdde8d28c4/Tests/Unit/MSFT_xProxySettings.Tests.ps1#L351)):*
> throw exception

throw an exception

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/270)*

**Comment by PlagueHO** [comment]
All change done! Thanks @Johlju

---

Review status: 10 of 14 files reviewed at latest revision, 12 unresolved discussions.

---

*[Modules/xNetworking/DSCResources/MSFT_xProxySettings/MSFT_xProxySettings.psm1, line 27 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/270#-KwPYgHi8qyFVkjF1n2p:-KwsaYfAO2eNlKyTQj2J:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/d82db55c4f9e98524fa57c72bff449bdde8d28c4/Modules/xNetworking/DSCResources/MSFT_xProxySettings/MSFT_xProxySettings.psm1#L27)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Not thought of it before, for the single instance resources, but think we should add 'Not used in Get-TargetResource' as of https://github.com/PowerShell/DscResources/blob/master/BestPractices.md#any-unused-parameters-that-must-be-included-in-a-function-definition-should-include-not-used-in-function_name-in-the-help-comment-for-that-parameter-in-the-comment-based-help
</blockquote></details>

Done.

---

*[Modules/xNetworking/DSCResources/MSFT_xProxySettings/MSFT_xProxySettings.psm1, line 214 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/270#-KwPXdULLbTWaiuOnbUQ:-KwsbHGUqZvUK-b4elSY:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/d82db55c4f9e98524fa57c72bff449bdde8d28c4/Modules/xNetworking/DSCResources/MSFT_xProxySettings/MSFT_xProxySettings.psm1#L214)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Nitpick. Non-blocking. :smile: 
Wouldn't it be better if we would clone `$PSBoundParameters` into a new variable `$convertToProxySettingsBinaryParameters` and remove the unnecessary parameters in that variable. Preserving `$PSBoundParameters` to be potentially evaluated later in the code.
</blockquote></details>

Done.

---

*[Modules/xNetworking/DSCResources/MSFT_xProxySettings/MSFT_xProxySettings.psm1, line 345 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/270#-KwPZ6lyrK-6IH6NhG5m:-KwsbMRf9RJfeKbFmjeu:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/d82db55c4f9e98524fa57c72bff449bdde8d28c4/Modules/xNetworking/DSCResources/MSFT_xProxySettings/MSFT_xProxySettings.psm1#L345)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> [Boolean]

[System.Boolean]
</blockquote></details>

Done.

---

*[Modules/xNetworking/DSCResources/MSFT_xProxySettings/MSFT_xProxySettings.psm1, line 383 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/270#-KwPZLRixf2pgl6iPenE:-KwsbOrirovWbXzkg0wx:b-k9mbib) ([raw file](https://github.com/powershell/xnetworking/blob/d82db55c4f9e98524fa57c72bff449bdde8d28c4/Modules/xNetworking/DSCResources/MSFT_xProxySettings/MSFT_xProxySettings.psm1#L383)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We should clone here to preserve the values in `$PSBoundParameters`. This is one time where PowerShell jumps over to use "pointers". I think this current method will remove the keys from `$PSBoundParameters` even when the keys are removed from the `$desiredValues`.

```powershell
PS > $a = @{}
PS > $a['Name1'] = 'Denise'
PS > $a['Name2'] = 'John'
PS > $b = $a
PS > $b.Remove('Name2')
PS > $a

Name                           Value
----                           -----
Name1                          Denise
```
</blockquote></details>

My bad! Good catch - I forgot about this.

---

*[Modules/xNetworking/DSCResources/MSFT_xProxySettings/MSFT_xProxySettings.psm1, line 384 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/270#-KwPaX9cZ_dK5wkoCN8X:-KwsbsdS_2u_8xpxcoBF:b3krt) ([raw file](https://github.com/powershell/xnetworking/blob/d82db55c4f9e98524fa57c72bff449bdde8d28c4/Modules/xNetworking/DSCResources/MSFT_xProxySettings/MSFT_xProxySettings.psm1#L384)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> $null 

Can we remove `$null` from these?
</blockquote></details>

N

---

*[Modules/xNetworking/DSCResources/MSFT_xProxySettings/MSFT_xProxySettings.psm1, line 484 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/270#-KwPbOa6nCu94eG9ON1l:-KwseC608lQZ8eanahE0:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/d82db55c4f9e98524fa57c72bff449bdde8d28c4/Modules/xNetworking/DSCResources/MSFT_xProxySettings/MSFT_xProxySettings.psm1#L484)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> Current

current (lower-case 'c')
</blockquote></details>

Done.

---

*[Modules/xNetworking/DSCResources/MSFT_xProxySettings/en-US/MSFT_xProxySettings.strings.psd1, line 12 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/270#-KwPc7DWo3LlM4Ofnv_o:-KwseRhho97L89NzyePh:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/d82db55c4f9e98524fa57c72bff449bdde8d28c4/Modules/xNetworking/DSCResources/MSFT_xProxySettings/en-US/MSFT_xProxySettings.strings.psd1#L12)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> proxy setting '{0}'

Some uses  tick (') around the value, some don't. We should be consequent.
</blockquote></details>

Done.

---

*[Tests/Integration/MSFT_xProxySettings.Integration.Tests.ps1, line 53 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/270#-KwPdCnkQCWFppNOteUn:-Kwsf8MeY9tip40fpess:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/d82db55c4f9e98524fa57c72bff449bdde8d28c4/Tests/Integration/MSFT_xProxySettings.Integration.Tests.ps1#L53)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Blank row before this one.
</blockquote></details>

Done.

---

*[Tests/Integration/MSFT_xProxySettings.Integration.Tests.ps1, line 60 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/270#-KwPdK_RegnhODrEw9sr:-KwsfF0U9FMViS9qGh4k:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/d82db55c4f9e98524fa57c72bff449bdde8d28c4/Tests/Integration/MSFT_xProxySettings.Integration.Tests.ps1#L60)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> not throw

`Not Throw`. Thorughout.
</blockquote></details>

Done.

---

*[Tests/Integration/MSFT_xProxySettings.Integration.Tests.ps1, line 64 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/270#-KwPdHD0iut_qn99YECL:-Kwsf_cVMxZqLkbchnZW:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/d82db55c4f9e98524fa57c72bff449bdde8d28c4/Tests/Integration/MSFT_xProxySettings.Integration.Tests.ps1#L64)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> throw

Throw (upper 'T')
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xProxySettings.Tests.ps1, line 125 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/270#-KwPe50CxO8UGt2MhgkJ:-Kwsft1smeTK7mVAVw3-:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/d82db55c4f9e98524fa57c72bff449bdde8d28c4/Tests/Unit/MSFT_xProxySettings.Tests.ps1#L125)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Blank row before this one. Throughout.
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xProxySettings.Tests.ps1, line 351 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/270#-KwPeToqc5ZAR4bFbh4Q:-Kwsg1dpHWDFY7ne91Hc:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/d82db55c4f9e98524fa57c72bff449bdde8d28c4/Tests/Unit/MSFT_xProxySettings.Tests.ps1#L351)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> throw exception

throw an exception
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/270#-:-KwskaLJkxPraa4-r-0C:b8j1lje)*

**Comment by johlju** [comment]
Just two more comments :)

---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Modules/xNetworking/DSCResources/MSFT_xProxySettings/MSFT_xProxySettings.psm1, line 25 at r3](https://reviewable.io:443/reviews/powershell/xnetworking/270#-KwuNtcXji5BXXR-lr0-:-KwuNtcXji5BXXR-lr00:b-4j78fv) ([raw file](https://github.com/powershell/xnetworking/blob/6cb8015803acfcd81a4a18185498e4bde45451a6/Modules/xNetworking/DSCResources/MSFT_xProxySettings/MSFT_xProxySettings.psm1#L25)):*
> ```PowerShell
>     .SYNOPSIS
>         Returns the current state of the proxy settings for
>         the computer. Not used in Get-TargetResource.
> ```

Don't think `Not used in Get-TargetResource.` should be there, should it? Or have I misunderstood the guideline? :thinking: 

---

*[Tests/Integration/MSFT_xProxySettings.Integration.Tests.ps1, line 64 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/270#-KwPdHD0iut_qn99YECL:-KwuObCnNiLO-zh8I6Vs:b-cdfzsn) ([raw file](https://github.com/powershell/xnetworking/blob/d82db55c4f9e98524fa57c72bff449bdde8d28c4/Tests/Integration/MSFT_xProxySettings.Integration.Tests.ps1#L64)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This one didn't stick. :smile: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/270#-:-KwuOo7H8bC3Ve7yrvSH:b8mldeb)*

**Comment by PlagueHO** [comment]
All done hopefully. Thanks again @Johlju

---

Review status: 12 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[Modules/xNetworking/DSCResources/MSFT_xProxySettings/MSFT_xProxySettings.psm1, line 25 at r3](https://reviewable.io:443/reviews/powershell/xnetworking/270#-KwuNtcXji5BXXR-lr0-:-KwvahAUyq0bkduHPPvA:b-la78sw) ([raw file](https://github.com/powershell/xnetworking/blob/6cb8015803acfcd81a4a18185498e4bde45451a6/Modules/xNetworking/DSCResources/MSFT_xProxySettings/MSFT_xProxySettings.psm1#L25)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Don't think `Not used in Get-TargetResource.` should be there, should it? Or have I misunderstood the guideline? :thinking: 
</blockquote></details>

Doh! I think my eyes must have been a bit blurry! :grin: Fixed

---

*[Tests/Integration/MSFT_xProxySettings.Integration.Tests.ps1, line 64 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/270#-KwPdHD0iut_qn99YECL:-Kwvb0u7W3rfTYmdClU7:b6nx0d1) ([raw file](https://github.com/powershell/xnetworking/blob/d82db55c4f9e98524fa57c72bff449bdde8d28c4/Tests/Integration/MSFT_xProxySettings.Integration.Tests.ps1#L64)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

This one didn't stick. :smile: 
</blockquote></details>

Doh! Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/270#-:-Kwvb2WILa3dvkHytS3c:b-e0e44d)*

**Comment by tysonjhayes** [comment]
Reviewed 7 of 14 files at r1, 2 of 4 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[Modules/xNetworking/DSCResources/MSFT_xProxySettings/en-US/MSFT_xProxySettings.strings.psd1, line 1 at r4](https://reviewable.io:443/reviews/powershell/xnetworking/270#-KxA1WUmLo8v1GQsjXcH:-KxA1WUmLo8v1GQsjXcI:b-dh7sbo) ([raw file](https://github.com/powershell/xnetworking/blob/bccb7f22642f2d1bba2c19b893ac34e45ba1da0f/Modules/xNetworking/DSCResources/MSFT_xProxySettings/en-US/MSFT_xProxySettings.strings.psd1#L1)):*
> ```PowerShell
> # Localized resources for MSFT_xDhcpClient
> ```

Should probably be MSFT_xProxySettings

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/270)*

**Comment by tysonjhayes** [comment]
Reviewed 1 of 14 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/270)*

**Comment by tysonjhayes** [comment]
Minor tweak then we should be good to merge.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/270#-:-KxA2aV2UuMqDE2LBS_P:b-tc9mcl)*

**Comment by johlju** [comment]
:lgtm:

Just review comments left from @tysonjhayes.

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/270#-:-KxC8Pb7cZRyn8xMO0i7:b-ic5wyv)*

**Comment by PlagueHO** [comment]
All done! Thanks @tysonjhayes and @johlju.

Hopefully you can sign off if all looks good? Cheers gents!

---

Review status: 13 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[Modules/xNetworking/DSCResources/MSFT_xProxySettings/en-US/MSFT_xProxySettings.strings.psd1, line 1 at r4](https://reviewable.io:443/reviews/powershell/xnetworking/270#-KxA1WUmLo8v1GQsjXcH:-KxHPia_Pba5TJdlSShs:b2141iz) ([raw file](https://github.com/powershell/xnetworking/blob/bccb7f22642f2d1bba2c19b893ac34e45ba1da0f/Modules/xNetworking/DSCResources/MSFT_xProxySettings/en-US/MSFT_xProxySettings.strings.psd1#L1)):*
<details><summary><i>Previously, tysonjhayes (Tyson J. Hayes) wrote…</i></summary><blockquote>

Should probably be MSFT_xProxySettings
</blockquote></details>

Great catch @Tysonjhayes ! Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/270#-:-KxHPzNlJ-0FOKGmrBD2:b-ph1aof)*

**Comment by johlju** [comment]
:lgtm:

Can't acknowledge @tysonjhayes comment. 

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/270#-:-KxHpfTbjMmXeop29nAG:b89k7wa)*

**Pull request merged**
