### PR TITLE
Added Documentation and Examples section to README.MD - Fixes #259

### LINKED ISSUE #259: Link Readme.md to Wiki Entries
**Details of the scenario you tried and the problem that is occurring:**
It is not obvious from the README.MD that there is a Wiki containing the full documentation.

**The DSC configuration that is using the resource (as detailed as possible):**
N/A

**Version of the Operating System and PowerShell the DSC Target Node is running:**
N/A

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
N/A

### PR DESCRIPTION
**Pull request by PlagueHO**
**Pull Request (PR) description**
Added Documentation and Examples section to README.MD. Wording mostly copied from SharePointDsc.

**This Pull Request (PR) fixes the following issues:**
Fixes #259 

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [ ] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [ ] Examples appropriately updated?
- [ ] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [ ] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xnetworking/260)

### CODE REVIEW

**Comment by johlju** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[README.md, line 39 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/260#-KsYm6S4lFocf2CTmgWe:-KsYm6S4lFocf2CTmgWf:b2rku6e) ([raw file](https://github.com/powershell/xnetworking/blob/219d70335a7cc41a5b18da1306da21a5c841fe86/README.md#L39)):*
> ... the `en-US` directory in the contains...

Seems phrasing is missing a word. I think I missed this in the other PR's in the other repos. :/ Was to quick, and only read the changed text there. I hadn't maard this one as reviewed so here I read the whole text again.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/260)*

**Comment by tysonjhayes** [comment]
any idea why the examples are failing to compile?

**Comment by PlagueHO** [comment]
Hi @tysonjhayes - that is a good point. I hadn't noticed that. I'm not sure what may have changed to make this occur but I'm looking into it. It is quite possible that something in DSCResource.Tests has been changed to cause this - there have been a few changes going through over there. I'll investigate further.

**Comment by PlagueHO** [comment]
@tysonjhayes - I kicked the CI on this again and it came right. Go figure!

**Comment by PlagueHO** [comment]
But we still need to figure out what we're going to do about this: https://github.com/PowerShell/DscResources/issues/315#issuecomment-325313827

It looks like there are some extra manual steps that are performed when releasing SharePointDsc that we're not using in xNetworking - so this results in the en-US folder from not being included in the package.

**Comment by PlagueHO** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 39 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/260#-KsYm6S4lFocf2CTmgWe:-Ksm5W78USqtvQQn9DvS:b-4n6zeb) ([raw file](https://github.com/powershell/xnetworking/blob/219d70335a7cc41a5b18da1306da21a5c841fe86/README.md#L39)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ... the `en-US` directory in the contains...

Seems phrasing is missing a word. I think I missed this in the other PR's in the other repos. :/ Was to quick, and only read the changed text there. I hadn't maard this one as reviewed so here I read the whole text again.
</blockquote></details>

I've removed this whole paragraph until I can implement a process to ensure this info is all being copied into the Resource Module during release.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/260)*

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/260#-:-KsnDQIFmlldGQFaaLt8:bnfp4nl)*

**Review by nourashraf202411-wq — COMMENTED** [review]
G

**Pull request merged**
