### PR TITLE
Resource for enabling/disabling LSO for a network adapter (issue #202)

### PR DESCRIPTION
**Pull request by gammalost**
New resource for enabling/disabling of LSO for different protocols on a network adapter.

Probably gone a bit overboard on testing, so I would appreciate some feedback on the amount :slightly_smiling_face: 

The integration test is failing because of a **Get-NetAdapterLso** call. I've tried using the commands in **IntegrationHelper.ps1**, but with no success. Do anybody know if the network adapter can handle the call mentioned above?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xnetworking/204)

### CODE REVIEW

**Comment by gammalost** [comment]
The integration test is failing because of a **Get-NetAdapterLso** call. I've tried using the commands in **IntegrationHelper.ps1**, but with no success. Do anybody know if the network adapter can handle the call mentioned above?

**Comment by PlagueHO** [comment]
Hi @gammalost - it looks like the Microsoft KM-TEST Loopback Adapter doesn't work with the `Get-NetAdapterLso` cmdet:
image
It does look like it will work on a standard Ethernet adapter though. So you don't have to use the Loopback Adapter to perform integration tests as long as the integration tests won't disrupt network connectivity. Loopback adapter usage is only required where running the integration tests will disconnect the network on the AppVeyor machine.

**Comment by gammalost** [comment]
Hi @PlagueHO! I was just about to update the PR about it not being able to handle **Get-NetAdapterLso**. I think it might drop the network connection for a bit, for when I'm using the resource on a server I have a RDP connection to I need to reconnect. 
Without the loopback adapter the problem still persists.

**Comment by gammalost** [comment]
Got it to work after some extensive Googling and trial and error. 
I had to find an adapter which had a [NDIS driver version above 6](https://msdn.microsoft.com/en-us/windows/hardware/drivers/network/offloading-the-segmentation-of-large-tcp-packets?f=255&MSPPError=-2147217396) to ensure that LSO could be fiddled with.
```powershell
$NetAdapter = Get-NetAdapter | Where-Object {$_.NdisVersion -ge 6} | Select-Object -First 1
```

**Comment by PlagueHO** [comment]
Amazing job @gammalost ! Fantastic work on the unit tests and getting the integration tests going!

Just some some tweaks to the examples need to be made because the original ones didn't actually meet style guidelines (so I went through them all last week and fixed them up). So once that is done I'll merge.

Thanks again for all your work on these - you're doing some great stuff on all the repos.

---

Reviewed 4 of 8 files at r1, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[Modules/xNetworking/Examples/Resources/xNetAdapterLso/1-DisableLsoIPv6.ps1, line 1 at r3](https://reviewable.io:443/reviews/powershell/xnetworking/204#-KirSjCLvBCfiZ0g_RR3:-KirSjCLvBCfiZ0g_RR4:b-pg43p0) ([raw file](https://github.com/powershell/xnetworking/blob/9284e68b629b812b6cbe405253145c5ba3355df7/Modules/xNetworking/Examples/Resources/xNetAdapterLso/1-DisableLsoIPv6.ps1#L1)):*
> ```PowerShell
> <#
> ```

I know this is pretty obvious, but is it worth adding an example for disabling LSO on IPv4 as well? IPv4 still is ubiquitous (even though I wish IPv6 was instead).

---

*[Modules/xNetworking/Examples/Resources/xNetAdapterLso/1-DisableLsoIPv6.ps1, line 9 at r3](https://reviewable.io:443/reviews/powershell/xnetworking/204#-KirR3IQcKWzOOrb8X9R:-KirR3IQcKWzOOrb8X9S:b-qsop77) ([raw file](https://github.com/powershell/xnetworking/blob/9284e68b629b812b6cbe405253145c5ba3355df7/Modules/xNetworking/Examples/Resources/xNetAdapterLso/1-DisableLsoIPv6.ps1#L9)):*
> ```PowerShell
>     param
>     (
>         [string[]] $NodeName = 'localhost'
> ```

Can you please move the $NodeName to the next line. I went through all the other Examples and made the same changes last week :grin:

---

*[Modules/xNetworking/Examples/Resources/xNetAdapterLso/1-DisableLsoIPv6.ps1, line 9 at r3](https://reviewable.io:443/reviews/powershell/xnetworking/204#-KirR7cuVpmEO51TjlLr:-KirR7cvbDzp0fVsgS37:bgmlbur) ([raw file](https://github.com/powershell/xnetworking/blob/9284e68b629b812b6cbe405253145c5ba3355df7/Modules/xNetworking/Examples/Resources/xNetAdapterLso/1-DisableLsoIPv6.ps1#L9)):*
> ```PowerShell
>     param
>     (
>         [string[]] $NodeName = 'localhost'
> ```

Can you please add `[Parameter()]` above. I went through all the other Examples and made the same changes last week :grin:

---

*[Modules/xNetworking/Examples/Resources/xNetAdapterLso/1-DisableLsoIPv6.ps1, line 9 at r3](https://reviewable.io:443/reviews/powershell/xnetworking/204#-KirRET86S-7w4Di5Aki:-KirRET86S-7w4Di5Akj:bkisjzz) ([raw file](https://github.com/powershell/xnetworking/blob/9284e68b629b812b6cbe405253145c5ba3355df7/Modules/xNetworking/Examples/Resources/xNetAdapterLso/1-DisableLsoIPv6.ps1#L9)):*
> ```PowerShell
>     param
>     (
>         [string[]] $NodeName = 'localhost'
> ```

Can you please change string to System.String - it looks like we're advising against using Type Accelerators - see https://github.com/PowerShell/DscResources/issues/259

 I went through all the other Examples and made the same changes last week :grin:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/204#-:-KirTpKqKBH1C3wp8IjA:b-ybfiql)*

**Comment by gammalost** [comment]
No problem @PlagueHO ! It should be in order now. One more thing since this resource uses wiki; what it the course of action to update it?

**Comment by PlagueHO** [comment]
At the moment we have to update it manually when the PS Team releases the DSC Resource Kit - they'll merge the changes to the resource to master branch. This will cause AppVeyor to produce an artefact that we can publish to the Wiki. But it is a manual process for now - but we're working on it. The plan is to update the central build process in DSCResource.tests to detect a push to master and then cause the Doc artefact to be uploaded automatically. Haven't had time to complete it yet.

Anyway, thanks again for adding another awesome new resource! :LGTM:

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/204#-:-KitCOI3wNojy9-zu1M0:b2qtzvg)*

**Comment by PlagueHO** [comment]
@gammalost - doh! Just noticed a test is failing - it's just the line added to Readme.md is too long. 

Change it to be something like this and the tests should pass:
```
- **xNetAdapterLso**: Enable or disable Lso for different protocols on a
  network adapter.
```

**Comment by gammalost** [comment]
So i understand it correctly that a wiki page will be created at the next resource kit update? :slightly_smiling_face: 
Corrected the README now, just waiting for the tests to complete :+1:

**Comment by PlagueHO** [comment]
@gammalost - yep - that is correct. I'll merge once the tests are complete.

**Comment by PlagueHO** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/204)*

**Comment by PlagueHO** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/204#-:-KitKut9iG5C31pmYpov:bnfp4nl)*

**Pull request merged**
