### PR TITLE
xFirewall pester tests

### PR DESCRIPTION
**Pull request by PlagueHO**
Relates to Issue #14.
Possibly got a bit test happy here, but you can't have too many tests right? :)

### CODE REVIEW

**Comment by tysonjhayes** [comment]
I added a bunch of tests in #15 and was planning on working on it today. I'll look between the two of these and figure out if we can combine the two.

**Comment by PlagueHO** [comment]
I should have paid attention to your work in #15. I am taking a look at it now and it is looking pretty good so far. I'll post any comments in that thread.

Just a heads up, I've also made the changes to the xDNSServerAddress, xDefaultGatewayAddress and xIPAddress to break up the logic as per your suggestion in #26. But I'll wait till these existing PRs are sorted before throwing that into the mix :)

**Comment by tysonjhayes** [comment]
Sounds good to me lets get some of #15 in and then we can start burning down the other ones. :+1:

**Comment by PlagueHO** [comment]
I'll close this pull request and re-issue it if there are any tests I can add to the xFirewall tests.

**Pull request closed without merging**
