### PR TITLE
Added repository to enable/disable network adapter power management. 

### PR DESCRIPTION
**Pull request by edycus**
Added repository to enable/disable network adapter power management.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xnetworking/195)

### CODE REVIEW

**Comment by edycus** [comment]
I finally go a PR submitted. It seems to have failed some checks. Should I fix them and resubmit?

**Comment by PlagueHO** [comment]
Hi @edycus - it looks like you've submitted this PR to the _master_ branch rather than the _dev_ branch. All PRs need to go to the _dev_ branch. Can you recreate the PR against the _dev_ branch?

**Comment by PlagueHO** [comment]
Hi @edycus , is this one still active? It looks like the PR needs to be recreated against the dev branch. Happy to help out on getting this one through as I think this would be a great addition!

**Comment by PlagueHO** [comment]
Hi @edycus - is there anything you are waiting on for me? Do you think you'll get a chance to rebase this change against the dev branch? If not I can mark this as abandoned and someone may try to pick it up later on?

**Comment by edycus** [comment]
No, I dropped the ball. Let me work in it.

Eric Dycus

________________________________

**Comment by PlagueHO** [comment]
No problem @edycus - glad to have your help! :grin:

**Comment by edycus** [comment]
I submitted the pull. It's gave me a bunch of stuff I don't know what to do with. Lol. I'm a little lost on how this works.

Eric Dycus

________________________________

**Comment by PlagueHO** [comment]
I'll close this one because it has been replaced by #219

**Pull request closed without merging**
