### PR TITLE
Added support for setting DNS for both IPv4 and IPv6 on the same Interface

### PR DESCRIPTION
**Pull request by PlagueHO**
This pull request relates to issue #20. This allows DNS server settings to be set for both IPv4 and IPv6 on the same interface. The change to allow this was the MSFT_xDNSServerAddress/MSFT_xDNSServerAddress.schema.mof by adding a Key attribute to the Address Family:

    [Key,Write,ValueMap{"IPv4", "IPv6"},Values{"IPv4", "IPv6"}] string AddressFamily;

I also added Pester Tests for xDNSServerAddress.

### CODE REVIEW

**Comment by tysonjhayes** [comment]
@PlagueHO your change seems pretty good, obviously we'll need to pass the unit tests before I can merge so if you want to fix those up I think we can get this merged.

**Comment by PlagueHO** [comment]
Hi @tysonjhayes ,
Aside from the UTF-8 build issue (didn't load my fork into AppVeyor - sorry my bad), I actually realized there is another issue with this change:
If the AddressFamily is made a [key], it will require the AddressFamily parameter to be changed to mandatory. It isn't currently but it does have a default value. I'm not sure what the policy would be to make such a change as it would mean that anyone upgrading to this new resource would require changes to configs. Is there some other solution to this problem? It does seem likely that assigning IPv4 and IPv6 DNS addresses on the same adapter would need to be supported. Any thoughts on this?

**Comment by tysonjhayes** [comment]
I think I broke the Firewall in PR #15 so, I guess we'll just be breaking a ton of our stuff this release? :grin: 

To your point I'm not sure there is a better way to approach fixing the problem. Fortunately it should find the problem when they go to generate new mof files indicating the key needs to be changed. So it'll throw an error "on compile" (or whatever it's called to make a mof file...) I think it's an acceptable change to support better functionality.

**Comment by PlagueHO** [comment]
Increased functionally is probably the way to go. You're right, an error does occur at Config compile time if AddressFamily is missing so they should be able to resolve the issue then. Cheers.

**Comment by tysonjhayes** [comment]
This looks great, if I could make one suggestion, could we remove the default value from AddressFamily in Get-TargetResource? I could be persuaded to think that we could leave it, just a thought.

Also could you add some notes to README.MD under Version (Create an UNRELEASED header) and note some of the changes. We use that to track the changes we're making until we actually get it released.

**Comment by PlagueHO** [comment]
Hi @tysonjhayes, Absolutely agree about the AddressFamily default - have remove it. Just updating the readme.md now.

**Comment by tysonjhayes** [comment]
@PlagueHO these look good, I see you were changing the outputs to some failure (I can't see what happened in the test pass) and reverted it back, do you want me to merge or do you want to make some more modifications (I'm really good with either).

**Comment by PlagueHO** [comment]
I added the OutputType() attrib to the Test-TargetResource and Get-TargetResource as the DSCHelperTools suggested (to get rid of the warnings), but it cause the tests to fail. I have resolved this in my fork, just testing now. I'll push a new version to this RP in about 10 minutes and you can merge that if you like. Tx

**Comment by tysonjhayes** [comment]
Looks good! Thanks for the work!

**Comment by PlagueHO** [comment]
:+1:

**Pull request merged**
