### PR TITLE
Created xNetAdapterRsc & xNetAdapterRss

### PR DESCRIPTION
**Pull request by atdhe18**
**Pull Request (PR) description**
Created Ressource xNetAdapterRsc for enablind or disabling Recv Segment Coalescing (RSC)

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [x] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [x] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines]
- [x] [Unit and (optional) Integration tests]

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xnetworking/261)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Hi @atdhe18 - really awesome to have your contribution! It looks like your tests are failing in AppVeyor though. Any chance you could have a look at this? We'll review once these are passing, although I won't be able to get to this till after the 7th of Sept (unless @tysonjhayes gets to it first :grin: )

**Comment by tysonjhayes** [comment]
Reviewed 2 of 10 files at r1, 1 of 2 files at r2, 6 of 12 files at r3.
Review status: 9 of 12 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[Modules/xNetworking/DSCResources/MSFT_xNetAdapterRsc/MSFT_xNetAdapterRsc.psm1, line 74 at r3](https://reviewable.io:443/reviews/powershell/xnetworking/261#-Ksj6yu8HS8a4zwhmlRd:-Ksj6yu8HS8a4zwhmlRe:b-hu35gw) ([raw file](https://github.com/powershell/xnetworking/blob/b52c34843dc1f9aa371718843006c514afcbe4e6/Modules/xNetworking/DSCResources/MSFT_xNetAdapterRsc/MSFT_xNetAdapterRsc.psm1#L74)):*
> ```PowerShell
>                 "IPv4"   { $result.add('State', $netAdapter.IPv4Enabled) }
>                 "IPv6"   { $result.add('State', $netAdapter.IPv6Enabled) }
>                 Default {"Should not be called."}
> ```

nit: I'd change this to a comment so we don't actually return anything to the pipe.

````powershell
Default {
    # nothing to see here move along
}
````

---

*[Modules/xNetworking/DSCResources/MSFT_xNetAdapterRsc/MSFT_xNetAdapterRsc.psm1, line 125 at r3](https://reviewable.io:443/reviews/powershell/xnetworking/261#-Ksj8Uaj_AG4ZwnsoE_U:-Ksj8Uaj_AG4ZwnsoE_V:b-ppz4b8) ([raw file](https://github.com/powershell/xnetworking/blob/b52c34843dc1f9aa371718843006c514afcbe4e6/Modules/xNetworking/DSCResources/MSFT_xNetAdapterRsc/MSFT_xNetAdapterRsc.psm1#L125)):*
> ```PowerShell
>         ) -join '')
> 
>         $netAdapter = Get-NetAdapterRsc -Name $Name -ErrorAction Stop
> ```

We seem to be making an assumption that RSC is enabled for the network adapter. yet there is an enable-netadapterrsc, is that out of scope for this dsc module?

---

*[Modules/xNetworking/DSCResources/MSFT_xNetAdapterRsc/MSFT_xNetAdapterRsc.psm1, line 134 at r3](https://reviewable.io:443/reviews/powershell/xnetworking/261#-Ksj7jN8y2NLtGhXUwNm:-Ksj7jN8y2NLtGhXUwNn:b2debhc) ([raw file](https://github.com/powershell/xnetworking/blob/b52c34843dc1f9aa371718843006c514afcbe4e6/Modules/xNetworking/DSCResources/MSFT_xNetAdapterRsc/MSFT_xNetAdapterRsc.psm1#L134)):*
> ```PowerShell
>             ) -join '')
> 
>             if ($Protocol -eq "IPv4" -and $State -ne $netAdapter.IPv4Enabled) 
> ```

Ignorant question here.

According to the examples we can set both IPv4 and IPv6 at the same time.

````powershell
    Set-NetAdapterRsc –Name "MyAdapter"-IPv4Enabled $True -IPv6Enabled $True
````

So wouldn't we want to be able to do the same in DSC? If we change protocal to a string array we can just set true/false in a go.

---

*[Modules/xNetworking/DSCResources/MSFT_xNetAdapterRss/MSFT_xNetAdapterRss.psm1, line 60 at r3](https://reviewable.io:443/reviews/powershell/xnetworking/261#-KsjVKoZ5qW_hN1egJGJ:-KsjVKoZ5qW_hN1egJGK:b-4kof2l) ([raw file](https://github.com/powershell/xnetworking/blob/b52c34843dc1f9aa371718843006c514afcbe4e6/Modules/xNetworking/DSCResources/MSFT_xNetAdapterRss/MSFT_xNetAdapterRss.psm1#L60)):*
> $result.add('State', $netAdapter.Enabled)

This could just be
````powershell
return @{
  Name = $name
  State = $netAdapter.Enabled
}
````

---

*[Modules/xNetworking/DSCResources/MSFT_xNetAdapterRss/en-US/MSFT_xNetAdapterRss.strings.psd1, line 9 at r3](https://reviewable.io:443/reviews/powershell/xnetworking/261#-KsjXZcC63PSJE5bIdb4:-KsjXZcC63PSJE5bIdb5:b-ze358n) ([raw file](https://github.com/powershell/xnetworking/blob/b52c34843dc1f9aa371718843006c514afcbe4e6/Modules/xNetworking/DSCResources/MSFT_xNetAdapterRss/en-US/MSFT_xNetAdapterRss.strings.psd1#L9)):*
> ```PowerShell
>     NetAdapterIsInDesiredStateMessage = Network adapter {0} {1} is in desired state {2}.
>     NetAdapterApplyingChangesMessage = Network adapter {0} {1} was {2}, should be {3}, applying changes.
> '@
> ```

Need a new line at the end of the file here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/261)*

**Comment by atdhe18** [comment]
Review status: 7 of 12 files reviewed at latest revision, 5 unresolved discussions.

---

*[Modules/xNetworking/DSCResources/MSFT_xNetAdapterRsc/MSFT_xNetAdapterRsc.psm1, line 74 at r3](https://reviewable.io:443/reviews/powershell/xnetworking/261#-Ksj6yu8HS8a4zwhmlRd:-KsjgHeayqZ-gGiI0jeg:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/b52c34843dc1f9aa371718843006c514afcbe4e6/Modules/xNetworking/DSCResources/MSFT_xNetAdapterRsc/MSFT_xNetAdapterRsc.psm1#L74)):*
<details><summary><i>Previously, tysonjhayes (Tyson J. Hayes) wrote…</i></summary><blockquote>

nit: I'd change this to a comment so we don't actually return anything to the pipe.

````powershell
Default {
    # nothing to see here move along
}
````
</blockquote></details>

Done.

---

*[Modules/xNetworking/DSCResources/MSFT_xNetAdapterRsc/MSFT_xNetAdapterRsc.psm1, line 125 at r3](https://reviewable.io:443/reviews/powershell/xnetworking/261#-Ksj8Uaj_AG4ZwnsoE_U:-KsjhCjZ0ju1bYzbdsNy:b-11rdvw) ([raw file](https://github.com/powershell/xnetworking/blob/b52c34843dc1f9aa371718843006c514afcbe4e6/Modules/xNetworking/DSCResources/MSFT_xNetAdapterRsc/MSFT_xNetAdapterRsc.psm1#L125)):*
<details><summary><i>Previously, tysonjhayes (Tyson J. Hayes) wrote…</i></summary><blockquote>

We seem to be making an assumption that RSC is enabled for the network adapter. yet there is an enable-netadapterrsc, is that out of scope for this dsc module?
</blockquote></details>

I'm sorry i didn't understand what you mean

---

*[Modules/xNetworking/DSCResources/MSFT_xNetAdapterRsc/MSFT_xNetAdapterRsc.psm1, line 134 at r3](https://reviewable.io:443/reviews/powershell/xnetworking/261#-Ksj7jN8y2NLtGhXUwNm:-KsjgJMYMyftFYzpwrtM:bek29z2) ([raw file](https://github.com/powershell/xnetworking/blob/b52c34843dc1f9aa371718843006c514afcbe4e6/Modules/xNetworking/DSCResources/MSFT_xNetAdapterRsc/MSFT_xNetAdapterRsc.psm1#L134)):*
<details><summary><i>Previously, tysonjhayes (Tyson J. Hayes) wrote…</i></summary><blockquote>

Ignorant question here.

According to the examples we can set both IPv4 and IPv6 at the same time.

````powershell
    Set-NetAdapterRsc –Name "MyAdapter"-IPv4Enabled $True -IPv6Enabled $True
````

So wouldn't we want to be able to do the same in DSC? If we change protocal to a string array we can just set true/false in a go.
</blockquote></details>

I went after xNetAdapterLso , i thought that changing both would be better but did it like the other. For my Company i did that we could change both. So if you want to i can change it.

---

*[Modules/xNetworking/DSCResources/MSFT_xNetAdapterRss/MSFT_xNetAdapterRss.psm1, line 60 at r3](https://reviewable.io:443/reviews/powershell/xnetworking/261#-KsjVKoZ5qW_hN1egJGJ:-KsjgnvBTukAol5Za-qj:bjqyx3t) ([raw file](https://github.com/powershell/xnetworking/blob/b52c34843dc1f9aa371718843006c514afcbe4e6/Modules/xNetworking/DSCResources/MSFT_xNetAdapterRss/MSFT_xNetAdapterRss.psm1#L60)):*
<details><summary><i>Previously, tysonjhayes (Tyson J. Hayes) wrote…</i></summary><blockquote>

> $result.add('State', $netAdapter.Enabled)

This could just be
````powershell
return @{
  Name = $name
  State = $netAdapter.Enabled
}
````
</blockquote></details>

Changed it back , i had it like this but the Test had errors 

---

*[Modules/xNetworking/DSCResources/MSFT_xNetAdapterRss/en-US/MSFT_xNetAdapterRss.strings.psd1, line 9 at r3](https://reviewable.io:443/reviews/powershell/xnetworking/261#-KsjXZcC63PSJE5bIdb4:-Ksjgj5CEe17VvByRw1x:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/b52c34843dc1f9aa371718843006c514afcbe4e6/Modules/xNetworking/DSCResources/MSFT_xNetAdapterRss/en-US/MSFT_xNetAdapterRss.strings.psd1#L9)):*
<details><summary><i>Previously, tysonjhayes (Tyson J. Hayes) wrote…</i></summary><blockquote>

Need a new line at the end of the file here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/261)*

**Comment by atdhe18** [comment]
Can you close this Pull Request

**Pull request closed without merging**
