### PR TITLE
MSFT_xNetAdapterAdvancedProperty enable multi setting - Fixed #324

### LINKED ISSUE #324: xNetAdapterAdvancedProperty: Conflict when configuring more than 1 NetAdapter
**Details of the scenario you tried and the problem that is occurring:**

When a configuration contains the following:
                xNetAdapterAdvancedProperty JumboPacket9014SMB1
                {
                    NetworkAdapterName  = 'vEthernet (SMB_1)'
                    RegistryKeyword     = "*JumboPacket"
                    RegistryValue       = 9014
                    DependsOn = '[xVMNetworkAdapter]SMB1'
                }

                xNetAdapterAdvancedProperty JumboPacket9014SMB2
                {
                    NetworkAdapterName  = 'vEthernet (SMB_2)'
                    RegistryKeyword     = "*JumboPacket"
                    RegistryValue       = 9014
                    DependsOn = '[xVMNetworkAdapter]SMB2'
                }

Compile fails with the following error:
Test-ConflictingResources : A conflict was detected between resources '[xNetAdapterAdvancedProperty]JumboPacket9014SMB1(C:\NR\S2D_Configuration.ps1::166::17::xNetAdapterAdvancedProperty)' and 
'[xNetAdapterAdvancedProperty]JumboPacket9014SMB2 (C:\NR\S2D_Configuration.ps1::174::17::xNetAdapterAdvancedProperty)' in node 'Node1'. Resources have identical key properties but there are differences in the following non-key properties: 
'NetworkAdapterName'. Values 'vEthernet (SMB_1)' don't match values 'vEthernet (SMB_2)'. Please update these property values so that they are identical in both cases.
At line:289 char:9
+         Test-ConflictingResources $keywordName $canonicalizedValue $k ...

Shouldn't it be possible to configure a property such as JumboPackets on several NetAdapters?

**The DSC configuration that is using the resource (as detailed as possible):**

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows Server 2016 with PowerShell 5.1

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
xNetworking 5.6.0.0

### PR DESCRIPTION
**Pull request by PlagueHO**
**Pull Request (PR) description**
BREAKING CHANGE: Enabled setting the same advanced adapter property on multiple network adapters.

This is a breaking change because it changes the key properties of the MOF.

**This Pull Request (PR) fixes the following issues:**
#324

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [x] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [ ] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [ ] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xnetworking/326)

### CODE REVIEW

**Comment by johlju** [comment]
:lgtm: to me too

@PlagueHO I wouldn't consider this a breaking change since it will not break any existing configurations.

---

Reviewed 4 of 4 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/powershell/xnetworking/326#-:-LAS33sID6ZCn9hlTgOZ:b-bkb4vw)*

**Comment by PlagueHO** [comment]
Thanks @Warryz and @johlju - you're right, this shouldn't be a breaking change. I've removed the breaking change. Can you two sign it off again for me please? Thank you!

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/powershell/xnetworking/326#-:-LAX3Qq62c3Dlh0iEnDw:bnfp4nl)*

**Comment by Warryz** [comment]
As you anyway rely on the adapter name to identify the targeted adapter this should not be breaking change as @johlju mentioned. 👍

**Pull request merged**
