### PR TITLE
Add DHCP support to xDNSServerAddress - Fixes #113

### LINKED ISSUE #113: xDhcpClient doesn't set DNS servers back to DHCP
It would be great if xDhcpClient checked if DNS settings for an adapter were set to "Obtain DNS server address automatically".  Right now it only checks for IP settings and I'd like to switch DNS settings back to DCHP as well.  Let me know if this is a reasonable request.

Greg

### PR DESCRIPTION
**Pull request by PlagueHO**
This PR adds support to use the xDNSServerAddress cmdlet to set DNS Server Addresses to be obtained from a DHCP server.

This PR also improves integration tests and should meet HQRM style guidelines. It also makes changes to support #176.

The changes in detail are:
- Added Get-DnsClientServerStaticAddress to NetworkingDsc.Common to return statically
  assigned DNS server addresses to support fix for [issue 113](https://github.com/PowerShell/xNetworking/issues/113).
- MSFT_xDNSserverAddress:
  - Added support for setting DNS Client to DHCP for [issue 113](https://github.com/PowerShell/xNetworking/issues/113).
  - Added new examples to show how to enable DHCP on DNS Client.
  - Improved integration test coverage to enable testing of multiple addresses and DHCP.
  - Converted exception creation to use common exception functions.
- MSFT_xDhcpClient:
  - Updated example to also cover setting DNS Client to DHCP.

This will resolve #113 and #211

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xnetworking/216)

### CODE REVIEW

**Comment by tysonjhayes** [comment]
Reviewed 11 of 15 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[Modules/xNetworking/DSCResources/MSFT_xDNSServerAddress/MSFT_xDNSServerAddress.psm1, line 118 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/216#-KlylOUObXlvxz913Jk0:-KlylOUObXlvxz913Jk1:bho52dw) ([raw file](https://github.com/powershell/xnetworking/blob/a5099dbc6c07314cb068457b55bdb21e099771c6/Modules/xNetworking/DSCResources/MSFT_xDNSServerAddress/MSFT_xDNSServerAddress.psm1#L118)):*
> ```PowerShell
>         ) -join '')
> 
>     # If address not passed, set to an empty array
> ```

Feeling kind of forgetful at the moment. We have a validatenotnullorempty, basically we expect this code to be hit if the parameter is not used at all correct?

---

*[Modules/xNetworking/Examples/Resources/xDhcpClient/1-xDHCPClient_EnableDHCP.ps1, line 30 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/216#-KlylkxEjtvkbNenl6BM:-KlylkxEjtvkbNenl6BN:b-e2cmhn) ([raw file](https://github.com/powershell/xnetworking/blob/a5099dbc6c07314cb068457b55bdb21e099771c6/Modules/xNetworking/Examples/Resources/xDhcpClient/1-xDHCPClient_EnableDHCP.ps1#L30)):*
> ```PowerShell
>             AddressFamily  = 'IPv4'
>         }
>         
> ```

Looks like we have some blank spaces here.

---

*[Modules/xNetworking/Modules/NetworkingDsc.Common/NetworkingDsc.Common.psm1, line 324 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/216#-Klylx3yT4kZJOvGVIPt:-Klylx3yT4kZJOvGVIPu:b-ttq6cb) ([raw file](https://github.com/powershell/xnetworking/blob/a5099dbc6c07314cb068457b55bdb21e099771c6/Modules/xNetworking/Modules/NetworkingDsc.Common/NetworkingDsc.Common.psm1#L324)):*
> ```PowerShell
>                 -f $InterfaceAlias)
> 
>         # Return null to support ErrorAction Silently Continue
> ```

I haven't seen this before, so if we don't return something SilentlyContinue doesn't work?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/216)*

**Comment by PlagueHO** [comment]
Thank you so much for reviewing @tysonjhayes! :grin:

---

Review status: 13 of 14 files reviewed at latest revision, 3 unresolved discussions.

---

*[Modules/xNetworking/DSCResources/MSFT_xDNSServerAddress/MSFT_xDNSServerAddress.psm1, line 118 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/216#-KlylOUObXlvxz913Jk0:-Km0bQG2uHvgzY1gmn0-:b-st1c6z) ([raw file](https://github.com/powershell/xnetworking/blob/a5099dbc6c07314cb068457b55bdb21e099771c6/Modules/xNetworking/DSCResources/MSFT_xDNSServerAddress/MSFT_xDNSServerAddress.psm1#L118)):*
<details><summary><i>Previously, tysonjhayes (Tyson J. Hayes) wrote…</i></summary><blockquote>

Feeling kind of forgetful at the moment. We have a validatenotnullorempty, basically we expect this code to be hit if the parameter is not used at all correct?
</blockquote></details>

That is correct. I originally had the parameter defaulted to an empty array, but this results in a $null rather than empty array object and also throws because of the ValidateNotnulOrEmpty() I also wanted to ensure that a blank string or array wasn't passed through - instead the parameter should be left out entirely if DHCP should be enabled on DNS.

---

*[Modules/xNetworking/Examples/Resources/xDhcpClient/1-xDHCPClient_EnableDHCP.ps1, line 30 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/216#-KlylkxEjtvkbNenl6BM:-Km0c8Ynp3VLJQYdbJe7:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/a5099dbc6c07314cb068457b55bdb21e099771c6/Modules/xNetworking/Examples/Resources/xDhcpClient/1-xDHCPClient_EnableDHCP.ps1#L30)):*
<details><summary><i>Previously, tysonjhayes (Tyson J. Hayes) wrote…</i></summary><blockquote>

Looks like we have some blank spaces here.
</blockquote></details>

Done.

---

*[Modules/xNetworking/Modules/NetworkingDsc.Common/NetworkingDsc.Common.psm1, line 324 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/216#-Klylx3yT4kZJOvGVIPt:-Km0cEWTwAYw9U2pgP1R:b-e4ohbw) ([raw file](https://github.com/powershell/xnetworking/blob/a5099dbc6c07314cb068457b55bdb21e099771c6/Modules/xNetworking/Modules/NetworkingDsc.Common/NetworkingDsc.Common.psm1#L324)):*
<details><summary><i>Previously, tysonjhayes (Tyson J. Hayes) wrote…</i></summary><blockquote>

I haven't seen this before, so if we don't return something SilentlyContinue doesn't work?
</blockquote></details>

This is because if you call Get-DnsClientServerStaticAddress with -EA SilentlyContinue with an adapter that does not exist then what actually happens is New-InvalidOperationException is called which throws an exception, but the exception is suppressed and control returns to the line after New-InvalidOperationException. The return $null prevents the cmdlet from continuing past this point. The New-InvalidOperationException cmdlet comes from over in PSDscResources.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/216#-:-Km0bJkKvftqQ1YoRskp:b-ctv9ns)*

**Comment by PlagueHO** [comment]
Hi @tysonjhayes - I've completed the changes as per your comments :grin: Any chance you could look them over if you get a chance?

**Comment by tysonjhayes** [comment]
:lgtm:

---

Review status: 13 of 14 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/216#-:-KmmubBKGjOsDWwQJTBN:bnfp4nl)*

**Comment by tysonjhayes** [comment]
Reviewed 1 of 15 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/216)*

**Comment by PlagueHO** [comment]
@tysonjhayes - thank you heaps sir! Appreciate it :+1:

**Pull request merged**
