### PR TITLE
BREAKING CHANGE: Add xNetAdapterName Resource - Fixes #187

### LINKED ISSUE #187: Need a wildcard or query for InterfaceAlias property in resources like xIPAddress, xDNSServerAddress, etc.
If I am applying a config to an existing server I have no idea what the interface alias has been named. There is no practical way to know that at the time the MOF is generated from a remote server at scale. (You could remotely query 1000 servers for this, but it is not practical.) For example, need a way built into the resources to apply to all interfaces that are connected except isatap and loopback. Perhaps a WQL string or some other technique.

### PR DESCRIPTION
**Pull request by PlagueHO**
This adds a new resource xNetAdapterName.

It is a breaking change because the functionality for renaming adapters from the xNetworkAdapter module was moved into NetworkingDsc.Common module. The xNetworkAdapter module was removed because it was no longer needed.

The xNetworkAdapter module was marked as "in preview" and had not yet been used by any other resources, so although this is not likely to be a breaking change, it is marked as such in case someone did choose to use this preview module for something.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xnetworking/203)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Hi @tysonjhayes - if you're about and have time, would you mind take a look over this PR for me? No worries if not though! :+1:

**Comment by tysonjhayes** [comment]
:lgtm:

---

Reviewed 18 of 18 files at r1.
Review status: 17 of 18 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/203#-:-Kj4gJRDlo2ZcBI9YJYG:bnfp4nl)*

**Comment by PlagueHO** [comment]
Awesome! Thank you @tysonjhayes ! Although one of the files (CHANGELOG.MD) wasn't marked as reviewed - are you able to mark that one off for me? Cheers sir!

---

Review status: 17 of 18 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/203#-:-Kj6vT_O_OiDB00b6zDM:b-81fz0r)*

**Comment by tysonjhayes** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/203)*

**Comment by PlagueHO** [comment]
Cool! Cheers @tysonjhayes !

**Pull request merged**
