### PR TITLE
Corrected style and formatting of xNetAdapterName to meet HQRM guidelines - Fixes #296

### LINKED ISSUE #296: Convert xNetAdapterName to HQRM and convert Exceptions to use Common Code
Work on issues:

 - #135
 - #176

### PR DESCRIPTION
**Pull request by PlagueHO**
**Pull Request (PR) description**
Corrected style and formatting to meet HQRM guidelines for xNetAdapterName. Updated tests for xNetAdapterName to Pester v4 standard.

**This Pull Request (PR) fixes the following issues:**
#296

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [x] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [x] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xnetworking/297)

### CODE REVIEW

**Comment by PlagueHO** [comment]
@Johlju - another one moved to HQRM for xNetworking - nearly there!

**Comment by johlju** [comment]
Just a few minor comments.

Merry Christmas my friend! :christmas_tree: 

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Tests/Unit/MSFT_xNetAdapterName.Tests.ps1, line 194 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/297#-L17CCxFm2_PNFVIgo1R:-L17CCxFm2_PNFVIgo1S:b-e38c07) ([raw file](https://github.com/powershell/xnetworking/blob/ecbfac19e220eb2c44cf07bb830e97168b24487f/Tests/Unit/MSFT_xNetAdapterName.Tests.ps1#L194)):*
> {$

Should have a space after open brace and before closing brace? No guideline on that I think, but mostly for consistency? If, so Throughout. 

---

*[Tests/Unit/MSFT_xNetAdapterName.Tests.ps1, line 230 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/297#-L17C0yHjFBWw31kTP0t:-L17C0yHjFBWw31kTP0u:b-d823p5) ([raw file](https://github.com/powershell/xnetworking/blob/ecbfac19e220eb2c44cf07bb830e97168b24487f/Tests/Unit/MSFT_xNetAdapterName.Tests.ps1#L230)):*
> $True

Lower-case `$true`. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/297#-:-L17Cg4UKJqPdE2kQ_Hc:b-2pa5hc)*

**Comment by PlagueHO** [comment]
And a merry xmas to you too sir! Thank you so much for code reviewing on Xmas eve (it's now Xmas day here :grin:)

I hope you have a great day - and don't spend it reviewing code!

---

Review status: 4 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[Tests/Unit/MSFT_xNetAdapterName.Tests.ps1, line 194 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/297#-L17CCxFm2_PNFVIgo1R:-L18yq06Zxbi2-vPUCeP:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/ecbfac19e220eb2c44cf07bb830e97168b24487f/Tests/Unit/MSFT_xNetAdapterName.Tests.ps1#L194)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> {$

Should have a space after open brace and before closing brace? No guideline on that I think, but mostly for consistency? If, so Throughout. 
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xNetAdapterName.Tests.ps1, line 230 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/297#-L17C0yHjFBWw31kTP0t:-L18yqhjUlHgwQxT7E7a:b9pqpgm) ([raw file](https://github.com/powershell/xnetworking/blob/ecbfac19e220eb2c44cf07bb830e97168b24487f/Tests/Unit/MSFT_xNetAdapterName.Tests.ps1#L230)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> $True

Lower-case `$true`. 
</blockquote></details>

Done.

I actually noticed that I had a bunch more of these in some of the other unit tests that had gone through HQRM, so I fixed those too. I should so add some new style tests in DSCResource.Tests for this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/297#-:-L18y3h_NMQQ4Ul9GuNL:b-nlqgvc)*

**Comment by johlju** [comment]
:lgtm:

Ignoring the tests not using the new Pester format. Let's get this PR thur and fix all those next. :)

I'm having a great day - girlfriend and I playing computer games and eating to much food and candy, and review code a couple of minutes between "breaks" ;) But now I'm off for the night.

---

Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Tests/Unit/MSFT_xNetAdapterName.Tests.ps1, line 230 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/297#-L17C0yHjFBWw31kTP0t:-L19F6yCtDYLCU_qF56V:b-6u5nsw) ([raw file](https://github.com/powershell/xnetworking/blob/ecbfac19e220eb2c44cf07bb830e97168b24487f/Tests/Unit/MSFT_xNetAdapterName.Tests.ps1#L230)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Done.

I actually noticed that I had a bunch more of these in some of the other unit tests that had gone through HQRM, so I fixed those too. I should so add some new style tests in DSCResource.Tests for this.
</blockquote></details>

Yes new style test for these would be good. Want to do more there to but there is that time constraint. ;) 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/297#-:-L19FFcZ4XOYiz5w5EEk:b-odgucy)*

**Comment by johlju** [comment]
Hmm.. I thought I acknowledge the last comment, guess I needed to start my comment with 'OK.' for it to stay resolved.

**Comment by PlagueHO** [comment]
Thanks @Johlju! Games and food with the girlfriend does seem like an excellent way to spend the evening! :) Thank you for taking the time to review this.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/297#-:-L1AckOfJa9yMBn3FFM6:bb502i9)*

**Comment by PlagueHO** [comment]
@johlju - no rush on this, are you able to tick off the last unresolved item so the PR goes green and I can merge it? Please, no rush at all :grin:

**Comment by johlju** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Tests/Unit/MSFT_xNetAdapterName.Tests.ps1, line 230 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/297#-L17C0yHjFBWw31kTP0t:-L1BmCx1-0BsSql2RaRN:b8k37v5) ([raw file](https://github.com/powershell/xnetworking/blob/ecbfac19e220eb2c44cf07bb830e97168b24487f/Tests/Unit/MSFT_xNetAdapterName.Tests.ps1#L230)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Yes new style test for these would be good. Want to do more there to but there is that time constraint. ;) 
</blockquote></details>

LGTM. I can't acknowledge this one, but marked it as satisfied both with the LGTM and tick on the right. Hope you can acknowledge this one, else you need to say 'Done' on it I hopefully I can acknowledge it again.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/297)*

**Comment by johlju** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/297#-:-L1BmkJZsjngcoh73Jb3:bnfp4nl)*

**Comment by johlju** [comment]
Okay, seemed it worked, it resolved once I pressed Publish.

**Pull request merged**
