### PR TITLE
xNetworkTeamInterface: Issue 248 - Fixed Test-TargetResource failing on VLANID 0

### PR DESCRIPTION
**Pull request by matthitchcock**
This is my first DSC Resource contribution, hopefully I covered everything.

The Test method currently fails when using a default VLANID value of 0 because the cmdlet returns $null for that property. My update to Test-TargetResource ensures that if 0 is used for the VLAN ID, it is substituted for a $null to compare to the output of Get-NetLBFOTeamNic.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xnetworking/262)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Really great job @matthitchcock ! Thank you very much for submitting this. Just some minor queries - great job with the tests too BTW!

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Modules/xNetworking/DSCResources/MSFT_xNetworkTeamInterface/MSFT_xNetworkTeamInterface.psm1, line 208 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/262#-Ksgpj7kdHng9def91b8:-Ksgpj7lmykcZ3EIW2IO:b-idqpqh) ([raw file](https://github.com/powershell/xnetworking/blob/76a71d1b4c81968d891b89c6b81dc3061acfa220/Modules/xNetworking/DSCResources/MSFT_xNetworkTeamInterface/MSFT_xNetworkTeamInterface.psm1#L208)):*
> ```PowerShell
>     $teamNic = Get-NetLbfoTeamNic -Name $Name -Team $TeamName -ErrorAction SilentlyContinue
> 
>     switch ($VlanID)
> ```

How come you used a `switch` here instead of an `if...else` ?

---

*[Modules/xNetworking/DSCResources/MSFT_xNetworkTeamInterface/MSFT_xNetworkTeamInterface.psm1, line 210 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/262#-Ksgq45qcGKQKP7mYFpv:-Ksgq45qcGKQKP7mYFpw:b-yijsxm) ([raw file](https://github.com/powershell/xnetworking/blob/76a71d1b4c81968d891b89c6b81dc3061acfa220/Modules/xNetworking/DSCResources/MSFT_xNetworkTeamInterface/MSFT_xNetworkTeamInterface.psm1#L210)):*
> ```PowerShell
>     switch ($VlanID)
>     {
>         '0' {$VLANValue = $null}
> ```

Nitpick: For consistency perhaps use `$VlanValue` (lower case lan)

This doesn't quite meet these style guidelines: https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#two-newlines-after-closing-brace

E.g.
```powershell
'0'
{
  $VlanValue = $null
}

default
{
  $VlanValue = $VlanID
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/262#-:-Ksgqa4epFng82zpa8wc:b410v20)*

**Comment by matthitchcock** [comment]
Hi

Not sure how to make my reply format as fancy as yours (new to this side of GitHub) but to answer the questions:
1. I used a switch because it seemed a bit more concise, it's personal style I suppose, I don't mind changing to if...else if that is viewed to be better
2. Happy to change the case to $VlanValue
3. The styling is again habit and preference, the ISE Snippet always laid it out like that which is where I learned switches :) If there is more than one line of activity I do lay it out as you suggest but if its only one line I leave everything on one line. Happy to make this change also.

By the way, I see there are some Code Coverage notifications, was there something I missed?
Also, the Tests were all fine? They passed but I wasn't sure if I needed some more?

**Comment by matthitchcock** [comment]
Code updated to reflect feedback

**Comment by matthitchcock** [comment]
Hi, just wanted to check if there is anything else I need to do at this stage?

**Comment by PlagueHO** [comment]
Hi @matthitchcock - can you just resolve the merge conflicts above and I'll get this reviewed for you this weekend (I've been traveling the last 2 weeks so haven't had much time to work on DSC stuff).

**Comment by PlagueHO** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/262#-:-KtcFOGQd-tUVqN_Pn_F:bg7igkv)*

**Pull request merged**
