### PR TITLE
Corrected style and formatting to meet HQRM guidelines - Fixes #287

### LINKED ISSUE #287: Convert xRoute to HQRM and convert Exceptions to use Common Code
Work on issues:

- #135
- #176

### PR DESCRIPTION
**Pull request by PlagueHO**
**Pull Request (PR) description**
Corrected style and formatting to meet HQRM guidelines for xRoute.

**This Pull Request (PR) fixes the following issues:**
- Fixes #287

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [x] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [ ] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xnetworking/288)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Hi @tysonjhayes or @johlju - would either of you have the time to review this? Once I've completed making all modules HQRM I'll being the process to convert the resource module to NetworkingDsc.

**Comment by johlju** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Modules/xNetworking/DSCResources/MSFT_xRoute/en-US/MSFT_xRoute.strings.psd1, line 4 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/288#-L0ZLESyod61gd-ouxAw:-L0ZLESz-Y43twjwXFEP:bufqsod) ([raw file](https://github.com/powershell/xnetworking/blob/ee31511133792c5be07ad987386e892d97b1ea38/Modules/xNetworking/DSCResources/MSFT_xRoute/en-US/MSFT_xRoute.strings.psd1#L4)):*
> destinationination

Typo

---

*[Tests/Unit/MSFT_xRoute.Tests.ps1, line 27 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/288#-L0ZLwDm_iVoNiu9g0Fm:-L0ZLwDm_iVoNiu9g0Fn:b-df8sez) ([raw file](https://github.com/powershell/xnetworking/blob/ee31511133792c5be07ad987386e892d97b1ea38/Tests/Unit/MSFT_xRoute.Tests.ps1#L27)):*
> -CommandName 

Was incorrectly added to the comment in a search/replace operation I think.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/288)*

**Comment by PlagueHO** [comment]
Thanks @Johlju - all done!

---

Review status: 8 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[Modules/xNetworking/DSCResources/MSFT_xRoute/en-US/MSFT_xRoute.strings.psd1, line 4 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/288#-L0ZLESyod61gd-ouxAw:-L0hIA6nffHIuhjGf00j:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/ee31511133792c5be07ad987386e892d97b1ea38/Modules/xNetworking/DSCResources/MSFT_xRoute/en-US/MSFT_xRoute.strings.psd1#L4)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> destinationination

Typo
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xRoute.Tests.ps1, line 27 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/288#-L0ZLwDm_iVoNiu9g0Fm:-L0hIBCcwldwxNNF3_Iq:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/ee31511133792c5be07ad987386e892d97b1ea38/Tests/Unit/MSFT_xRoute.Tests.ps1#L27)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> -CommandName 

Was incorrectly added to the comment in a search/replace operation I think.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/288#-:-L0hIFysZ-0bTP7SbF5T:b-e9ztwx)*

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/288#-:-L0hrUvXz0J3wnnLNKTI:bnfp4nl)*

**Comment by PlagueHO** [comment]
Thanks @Johlju!

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/288#-:-L0i1LuF-NCpjqlPRWmA:b-cn2syp)*

**Pull request merged**
