### PR TITLE
Fixes xRoute route removal failure - Fixes #134

### LINKED ISSUE #134: application bug in powershell DSCResource XNetworking - XRoute
When I am using the module to remove a specific route, The script delete all routes from the list what ever route assigned.               

It all works fine when delete below scripts from the function Test-TargetResource in  MSFT_xRoute.psm1

            # The Route exists - remove it
            $null = $PSBoundParameters.Remove('InterfaceAlias')
            $null = $PSBoundParameters.Remove('AddressFamily')
            $null = $PSBoundParameters.Remove('DestinationPrefix')
            $null = $PSBoundParameters.Remove('NextHop')

### PR DESCRIPTION
**Pull request by PlagueHO**
This PR fixes the Route Removal failure in xRoute as reported in #134.

I have included better unit tests for this to prevent regression.

Sorry about all the removal of end of line spaces - I have VS Code set to trim lines.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xnetworking/137)

### CODE REVIEW

**Comment by tysonjhayes** [comment]
Unit tests look good, should we add anything to the integration tests to catch this behavior?

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[DSCResources/MSFT_xRoute/MSFT_xRoute.psm1, line 178 \[r1\]](https://reviewable.io:443/reviews/powershell/xnetworking/137#-KOJ4WqQWXC82hLEpE8l:-KOJ4WqQWXC82hLEpE8m:-1506200859) ([raw file](https://github.com/powershell/xnetworking/blob/a04b15bf69a3b5fddc8f746a95d6ee9d59a0abd9/DSCResources/MSFT_xRoute/MSFT_xRoute.psm1#L178)):*
> ```PowerShell
>         if ($Route)
>         {
>             # The Route exists - remove it
> ```

Could we put some notes in for our future selves as to why we are doing it this way vs the previous method so we don't accidentally go and "fix" this again?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/137#-:-KOJ4sY0hYYgt4iTmrhs:100846676)*

**Comment by narrieta** [comment]
@PlagueHO Could you check whether the test failure is related to this change?

Thanks

**Comment by PlagueHO** [comment]
Hi @narrieta - I've run accross this intermittent glitch before. It appears to be caused by the LCM reapplying the previous configuration when another integration test runs. 

I'm fairly certain this isn't caused by this change. But I will make 100% sure today/tonight. It would actually be really good to solve this glitch though because at the moment the only way to fix it is to kick off another build,  which means I need to push a dummy commit. 

@tysonjhayes - awesome suggestions as always. I'll get on to them today/tonight.

**Comment by PlagueHO** [comment]
Sorry @narrieta and @tysonjhayes - I haven't finished this (too busy trying to reduce the tech debt on xCertificate). I'll get to it this week.

**Comment by PlagueHO** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[DSCResources/MSFT_xRoute/MSFT_xRoute.psm1, line 178 \[r1\]](https://reviewable.io:443/reviews/powershell/xnetworking/137#-KOJ4WqQWXC82hLEpE8l:-KOi8hWdUVGnQEgsgAsA:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/a04b15bf69a3b5fddc8f746a95d6ee9d59a0abd9/DSCResources/MSFT_xRoute/MSFT_xRoute.psm1#L178)):*
<details><summary><i>Previously, tysonjhayes (Tyson J. Hayes) wrote…</i></summary>
> Could we put some notes in for our future selves as to why we are doing it this way vs the previous method so we don't accidentally go and "fix" this again?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/137)*

**Comment by PlagueHO** [comment]
@tysonjhayes - I've finished all your suggested changes so should be good to go.

@narrieta - I've done a bit of digging on the very intermittent test issue occurring when integration testing. This is difficult to replicate as it is appears to be a timing issue. It is not specific to this resource and I think it needs to be fixed by adjusting the test templates/test helper code. So I've raised an issue on DSCResources for this.

**Comment by narrieta** [comment]
@PlagueHO Thanks for the investigation

**Pull request merged**
