### PR TITLE
Fix xFirewall if CIDR notation used for LocalAddress/RemoteAddress - Fixes #169

### LINKED ISSUE #169: xFirewall RemoteAddress fails test if CIDR notation is used.
xNetworking version 3.0.0.0
RemoteAddress test fails if CIDR notation is used in the configuration. The rule is created, but the test fails.

Recommendations: 
1.  Update documentation providing only currently supported formats.
2.  Provide an example.
3.  Provide intellisense option showing a subnet mask notation. 
4.  Update code to translate CIDR notation to subnet mask.

----- This firewall will get created successfully but the test will FAIL.
        xFirewall myNagiosFw
        {
            Name  = "DSC-Nagios"
            Enabled = $true
            Action = 'Allow'
            LocalPort = 5666
            Direction = 'Inbound'
            Protocol = 'TCP'
            Ensure = 'Present'
            RemoteAddress = '10.10.0.0/16' # CAUSE OF TEST FAILURE
        }

----- This firewall will get created successfully and the test will PASS.
        xFirewall myNagiosFw
        {
            Name  = "DSC-Nagios"
            Enabled = $true
            Action = 'Allow'
            LocalPort = 5666
            Direction = 'Inbound'
            Protocol = 'TCP'
            Ensure = 'Present'
            RemoteAddress = '10.10.0.0/255.255.0.0' # CAUSE OF TEST FAILURE
        }

We managed to inject some verbose statements into the function Test-RuleProperties
File: C:\Program Files\WindowsPowerShell\Modules\xNetworking\3.0.0.0\DSCResources\MSFT_xFirewall\MSFT_xFirewall.psm1
... code added ....
Write-Verbose "array-----:$ParameterSource----:$ParameterNew -----"
.... output from code .... 
VERBOSE: [localhost]:  [[xFirewall]myNagiosFw] Test-RuleProperties: RemoteAddress property value '10.10.0.0/255.255.0.0' does not match desired state '10.10.0.0/16'.

### PR DESCRIPTION
**Pull request by PlagueHO**
The primary purpose for this PR is to fix issue #169. In fixing this I also uncovered a bug in the Integration tests for xFirewall that resulted in the firewall rule properties not actually being tested after the rule was set. Fixing this didn't actually identify any test failures.

However, I've also begun work on the resource to bring it up to HQRM (issue #135) and added the CommonResourceHelper.psm1 module (issue #152).

The detailed list of changes are as follows:
- Added CommonResourceHelper.psm1 based on copy from [PSDscResources](https://github.com/PowerShell/PSDscResources/blob/dev/DscResources/CommonResourceHelper.psm1).
- MSFT_xFirewall:
  - Cleaned up ParameterList table layout and moved into a new file (MSFT_xFirewall.data.psd1).
  - Separated Localization strings into strings file.
  - Added standard help blocks to all functions to meet HQRM standards.
  - Added CmdletBinding attribute to all functions to meet HQRM standards.
  - Style changes to meet HQRM standards.
  - Fixed issue using CIDR notation for LocalAddress or RemoteAddress. See [GitHub issue](https://github.com/PowerShell/xNetworking/issues/169).
  - Fixed integration tests so that values being set are correctly tested.
  - Added integration tests for Removal of Firewall rule.
- Resolved final markdown errors (MD*) in Readmd.md.
- Added NetworkingCommon module to contain shared networking functions.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xnetworking/173)

### CODE REVIEW

**Comment by PlagueHO** [comment]
@tysonjhayes - I'm thinking this one will need some fixing up before it can be merged once your PR #174 goes through. So no need to rush out a review on this till after then.

**Comment by tysonjhayes** [comment]
Reviewed 3 of 14 files at r1, 1 of 1 files at r2.
Review status: 4 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[Tests/Unit/MSFT_xFirewall.Tests.ps1, line 622 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/173#-Ka58GIJfS2JEFc8zFp2:-Ka58GIJfS2JEFc8zFp3:bqu3q9y) ([raw file](https://github.com/powershell/xnetworking/blob/e7f3ff5e1c8fc8941a47a99dddb7be525c0abd2d/Tests/Unit/MSFT_xFirewall.Tests.ps1#L622)):*
> ```PowerShell
>             foreach ($parameter in $ParameterList)
>             {
>                 $parameterSource = (Invoke-Expression -Command "`$($($parameter.source))")
> ```

This will need an override at the top of the file as we're not supposed to use invoke-expression, however, I'm not really sure how else to get around that rule.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/173)*

**Comment by tysonjhayes** [comment]
Review status: 4 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[Tests/Integration/MSFT_xFirewall_add.config.ps1, line 45 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/173#-Ka58Wnd7rBAof-39z54:-Ka58Wnd7rBAof-39z55:b-h16n2n) ([raw file](https://github.com/powershell/xnetworking/blob/e7f3ff5e1c8fc8941a47a99dddb7be525c0abd2d/Tests/Integration/MSFT_xFirewall_add.config.ps1#L45)):*
> ```PowerShell
>     node localhost {
>        xFirewall Integration_Test {
>             Name                  = $Node.RuleName
> ```

I might be missing something but where is the node variable defined?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/173)*

**Comment by tysonjhayes** [comment]
Review status: 4 of 13 files reviewed at latest revision, 4 unresolved discussions.

---

*[DSCResources/MSFT_xFirewall/MSFT_xFirewall.psm1, line 6 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/173#-Ka58kJgMfOLpOzAER_u:-Ka58kJgMfOLpOzAER_v:brbmzt5) ([raw file](https://github.com/powershell/xnetworking/blob/e7f3ff5e1c8fc8941a47a99dddb7be525c0abd2d/DSCResources/MSFT_xFirewall/MSFT_xFirewall.psm1#L6)):*
> ```PowerShell
>     -Parent
> $script:commonResourceHelperFilePath = Join-Path `
>     -Path $script:dscResourcesFolderFilePath `
> ```

I know we're holding off on final paths until I merge in my thing, but I noted SharePoint has a [\SharepointDsc\Modules](https://github.com/PowerShell/SharePointDsc/tree/dev/Modules/SharePointDsc/Modules) directory that I think this would be a better fit under, so it kind of cleanly encapsulates everything.

---

*[DSCResources/MSFT_xFirewall/MSFT_xFirewall.psm1, line 16 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/173#-Ka593mFpm8kf9NUMUWc:-Ka593mFpm8kf9NUMUWd:b-vtjfj7) ([raw file](https://github.com/powershell/xnetworking/blob/e7f3ff5e1c8fc8941a47a99dddb7be525c0abd2d/DSCResources/MSFT_xFirewall/MSFT_xFirewall.psm1#L16)):*
> ```PowerShell
> Import-Module -Name ( Join-Path `
>     -Path (Split-Path -Path $PSScriptRoot -Parent) `
>     -ChildPath '\NetworkingCommon\NetworkingCommon.psm1' )
> ```

See above on path.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/173)*

**Comment by PlagueHO** [comment]
Review status: 0 of 15 files reviewed at latest revision, 4 unresolved discussions.

---

*[Tests/Integration/MSFT_xFirewall_add.config.ps1, line 45 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/173#-Ka58Wnd7rBAof-39z54:-KaBjRVV7R1r1SKCIp-w:b-enbzno) ([raw file](https://github.com/powershell/xnetworking/blob/e7f3ff5e1c8fc8941a47a99dddb7be525c0abd2d/Tests/Integration/MSFT_xFirewall_add.config.ps1#L45)):*
<details><summary><i>Previously, tysonjhayes (Tyson J. Hayes) wrote…</i></summary><blockquote>

I might be missing something but where is the node variable defined?
</blockquote></details>

$Node is a variable that automatically gets exposed by the ```node``` block if a ```ConfigurationData``` parameter was passed to the DSC Configuration when it is compiled. You'll see that the a ```$ConfigData``` object is defined and passed in the integration test. This is a little more elegant than the older solution so it's used more often now (but I haven't updated everything to use it yet).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/173)*

**Comment by PlagueHO** [comment]
Review status: 0 of 15 files reviewed at latest revision, 4 unresolved discussions.

---

*[Tests/Unit/MSFT_xFirewall.Tests.ps1, line 622 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/173#-Ka58GIJfS2JEFc8zFp2:-KaGd-6RPe-uGZlx0rJf:btpoyes) ([raw file](https://github.com/powershell/xnetworking/blob/e7f3ff5e1c8fc8941a47a99dddb7be525c0abd2d/Tests/Unit/MSFT_xFirewall.Tests.ps1#L622)):*
<details><summary><i>Previously, tysonjhayes (Tyson J. Hayes) wrote…</i></summary><blockquote>

This will need an override at the top of the file as we're not supposed to use invoke-expression, however, I'm not really sure how else to get around that rule.
</blockquote></details>

I gave this a try, but unfortunately, suppressing the rule actually violates some of the standard tests. We can only suppress certain rules and this isn't one of them :cry:

So, we might have to leave the warning here and figure out a way to address rewrite the code as part of issue #166.

---

*[DSCResources/MSFT_xFirewall/MSFT_xFirewall.psm1, line 6 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/173#-Ka58kJgMfOLpOzAER_u:-KaGdfbghh3-EDpj4I05:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/e7f3ff5e1c8fc8941a47a99dddb7be525c0abd2d/DSCResources/MSFT_xFirewall/MSFT_xFirewall.psm1#L6)):*
<details><summary><i>Previously, tysonjhayes (Tyson J. Hayes) wrote…</i></summary><blockquote>

I know we're holding off on final paths until I merge in my thing, but I noted SharePoint has a [\SharepointDsc\Modules](https://github.com/PowerShell/SharePointDsc/tree/dev/Modules/SharePointDsc/Modules) directory that I think this would be a better fit under, so it kind of cleanly encapsulates everything.
</blockquote></details>

Done.

---

*[DSCResources/MSFT_xFirewall/MSFT_xFirewall.psm1, line 16 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/173#-Ka593mFpm8kf9NUMUWc:-KaGdg1xEc6IKCada6fu:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/e7f3ff5e1c8fc8941a47a99dddb7be525c0abd2d/DSCResources/MSFT_xFirewall/MSFT_xFirewall.psm1#L16)):*
<details><summary><i>Previously, tysonjhayes (Tyson J. Hayes) wrote…</i></summary><blockquote>

See above on path.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/173)*

**Comment by PlagueHO** [comment]
@tysonjhayes - this is what happens when I try and suppress the rule:
image

**Comment by tysonjhayes** [comment]
I get the intent of that test but I'm not sure I agree with it. I guess we just take the warning for now...

---

Reviewed 3 of 23 files at r1, 11 of 22 files at r3, 12 of 12 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[DSCResource.Tests, line 1 at r4](https://reviewable.io:443/reviews/powershell/xnetworking/173#-KaJvcQmWHnMXASoESUK:-KaJvcQmWHnMXASoESUL:b-l6qf3) ([raw file](https://github.com/powershell/xnetworking/blob/1c03d48db4e6d3f42e3026fa0fca10d75856612c/DSCResource.Tests#L1)):*
> ```
> Subproject commit e7c0dc5a29a3cc23c2ce84ad23ff02353a799280
> ```

What's the deal with this?

---

*[Modules/xNetworking/DSCResources/MSFT_xFirewall/MSFT_xFirewall.psm1, line 120 at r4](https://reviewable.io:443/reviews/powershell/xnetworking/173#-KaJvs2U_D0mUnxxl6lk:-KaJvs2U_D0mUnxxl6ll:bjsaec4) ([raw file](https://github.com/powershell/xnetworking/blob/1c03d48db4e6d3f42e3026fa0fca10d75856612c/Modules/xNetworking/DSCResources/MSFT_xFirewall/MSFT_xFirewall.psm1#L120)):*
> ```PowerShell
> 
> <#
>     .SYNOPSIS
> ```

So because of the merge we took with my changes I believe the help is auto generated from the mof files, do we still need this here?

---

*[Modules/xNetworking/DSCResources/MSFT_xFirewall/en-US/MSFT_xFirewall.strings.psd1, line 4 at r4](https://reviewable.io:443/reviews/powershell/xnetworking/173#-KaJwQbRfh2skf5lQ5yW:-KaJwQbRfh2skf5lQ5yX:b-lov5tr) ([raw file](https://github.com/powershell/xnetworking/blob/1c03d48db4e6d3f42e3026fa0fca10d75856612c/Modules/xNetworking/DSCResources/MSFT_xFirewall/en-US/MSFT_xFirewall.strings.psd1#L4)):*
> ```PowerShell
> 
> ConvertFrom-StringData @'
> GettingFirewallRuleMessage = Getting firewall rule with Name '{0}'.
> ```

Should all of these be tabed over?

---

*[Modules/xNetworking/Examples/Resources/xFirewall/2-xFirewall_AddFirewallRule_AllParameters.ps1, line 20 at r4](https://reviewable.io:443/reviews/powershell/xnetworking/173#-KaJwHqq4928sz9UnU9G:-KaJwHqq4928sz9UnU9H:bji3l8i) ([raw file](https://github.com/powershell/xnetworking/blob/1c03d48db4e6d3f42e3026fa0fca10d75856612c/Modules/xNetworking/Examples/Resources/xFirewall/2-xFirewall_AddFirewallRule_AllParameters.ps1#L20)):*
> ```PowerShell
>         xFirewall Firewall
>         {
>             Name                  = "NotePadFirewallRule"
> ```

Any reason we're going back to double quotes?

---

*[Tests/Integration/MSFT_xFirewall_remove.config.ps1, line 2 at r4](https://reviewable.io:443/reviews/powershell/xnetworking/173#-KaJwj2E6zksU2djG3X3:-KaJwj2E6zksU2djG3X4:b-8mih75) ([raw file](https://github.com/powershell/xnetworking/blob/1c03d48db4e6d3f42e3026fa0fca10d75856612c/Tests/Integration/MSFT_xFirewall_remove.config.ps1#L2)):*
> ```PowerShell
> <#
>   This file exists so we can load the test file without necessarily having xNetworking in
> ```

Just curious, are we creating .ps1 for every config rule? I always figured one file with all of the rules made sense, and allowed us to load the file once instead of before every rule.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/173#-:-KaJulIEgQBgAnkPh4dA:bw1hfws)*

**Comment by PlagueHO** [comment]
I know what you mean. I guess there are going to have to be exceptions to this test though - unless we can find a different way of writing the code. 

@KwirkyKat - does your team have any thoughts on this?

The issue is that we're using Invoke-Expression to allow the large number of parameters in the Firewall to be stored in a PSD1 data structure and processed by various loops instead of writing a whole lot of code. We haven't got an alternative to using Invoke-Expression for this code. But we can't suppress the message. Perhaps you guys have got some ideas on what we might replace it with?

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[DSCResource.Tests, line 1 at r4](https://reviewable.io:443/reviews/powershell/xnetworking/173#-KaJvcQmWHnMXASoESUK:-KaLtKEqtnpQDcddy4dN:btxrqo9) ([raw file](https://github.com/powershell/xnetworking/blob/1c03d48db4e6d3f42e3026fa0fca10d75856612c/DSCResource.Tests#L1)):*
<details><summary><i>Previously, tysonjhayes (Tyson J. Hayes) wrote…</i></summary><blockquote>

What's the deal with this?
</blockquote></details>

Er um. I'm not sure how that got there? Possibly turned up when I was working on fixing the merge conflicts and figuring out how to test the repo with the new layout. It shouldn't be there though - good catch. Removed.

---

*[Modules/xNetworking/DSCResources/MSFT_xFirewall/MSFT_xFirewall.psm1, line 120 at r4](https://reviewable.io:443/reviews/powershell/xnetworking/173#-KaJvs2U_D0mUnxxl6lk:-KaLu6iU1aNjj-VakXx8:blp29l0) ([raw file](https://github.com/powershell/xnetworking/blob/1c03d48db4e6d3f42e3026fa0fca10d75856612c/Modules/xNetworking/DSCResources/MSFT_xFirewall/MSFT_xFirewall.psm1#L120)):*
<details><summary><i>Previously, tysonjhayes (Tyson J. Hayes) wrote…</i></summary><blockquote>

So because of the merge we took with my changes I believe the help is auto generated from the mof files, do we still need this here?
</blockquote></details>

This is one of the many requirements of HQRM :grin:

I think it does help though because it does enable a bit of extra detail in intellisense when writing DSC Configs.

---

*[Modules/xNetworking/DSCResources/MSFT_xFirewall/en-US/MSFT_xFirewall.strings.psd1, line 4 at r4](https://reviewable.io:443/reviews/powershell/xnetworking/173#-KaJwQbRfh2skf5lQ5yW:-KaLuTtmnI1tTJbIO_3U:bwo0u03) ([raw file](https://github.com/powershell/xnetworking/blob/1c03d48db4e6d3f42e3026fa0fca10d75856612c/Modules/xNetworking/DSCResources/MSFT_xFirewall/en-US/MSFT_xFirewall.strings.psd1#L4)):*
<details><summary><i>Previously, tysonjhayes (Tyson J. Hayes) wrote…</i></summary><blockquote>

Should all of these be tabed over?
</blockquote></details>

Yes - it should. Done.

---

*[Modules/xNetworking/Examples/Resources/xFirewall/2-xFirewall_AddFirewallRule_AllParameters.ps1, line 20 at r4](https://reviewable.io:443/reviews/powershell/xnetworking/173#-KaJwHqq4928sz9UnU9G:-KaLvAqnUulkL5fxTeFy:brzxw6v) ([raw file](https://github.com/powershell/xnetworking/blob/1c03d48db4e6d3f42e3026fa0fca10d75856612c/Modules/xNetworking/Examples/Resources/xFirewall/2-xFirewall_AddFirewallRule_AllParameters.ps1#L20)):*
<details><summary><i>Previously, tysonjhayes (Tyson J. Hayes) wrote…</i></summary><blockquote>

Any reason we're going back to double quotes?
</blockquote></details>

Nope. I fixed it. Sorry about that!

---

*[Tests/Integration/MSFT_xFirewall_remove.config.ps1, line 2 at r4](https://reviewable.io:443/reviews/powershell/xnetworking/173#-KaJwj2E6zksU2djG3X3:-KaLwnq1-Z6YAdC8aggP:b-8wyupa) ([raw file](https://github.com/powershell/xnetworking/blob/1c03d48db4e6d3f42e3026fa0fca10d75856612c/Tests/Integration/MSFT_xFirewall_remove.config.ps1#L2)):*
<details><summary><i>Previously, tysonjhayes (Tyson J. Hayes) wrote…</i></summary><blockquote>

Just curious, are we creating .ps1 for every config rule? I always figured one file with all of the rules made sense, and allowed us to load the file once instead of before every rule.
</blockquote></details>

I've tweaked this a bit by moving the $Rule into the $ConfigData object which gets passed to the Configs. I probably could have just used a single config and just passed a $ConfigData with different node properties. I just felt it was cleaner separating them (and that was the design pattern I'd used elsewhere - see xPSDesiredStateConfiguration). But happy to change it if you think it's better that way?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/173#-:-KaLrvEd-bX9dgdC6uaE:b-kwsmpt)*

**Comment by tysonjhayes** [comment]
Reviewed 1 of 23 files at r1, 1 of 22 files at r3, 6 of 6 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Modules/xNetworking/DSCResources/MSFT_xFirewall/MSFT_xFirewall.psm1, line 120 at r4](https://reviewable.io:443/reviews/powershell/xnetworking/173#-KaJvs2U_D0mUnxxl6lk:-KaVsJaFq_b7fVPjhwYG:b8blwb0) ([raw file](https://github.com/powershell/xnetworking/blob/1c03d48db4e6d3f42e3026fa0fca10d75856612c/Modules/xNetworking/DSCResources/MSFT_xFirewall/MSFT_xFirewall.psm1#L120)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

This is one of the many requirements of HQRM :grin:

I think it does help though because it does enable a bit of extra detail in intellisense when writing DSC Configs.
</blockquote></details>

I'm more thinking I'm not seeing that on [SharePointDsc](https://github.com/PowerShell/SharePointDsc/blob/dev/Modules/SharePointDsc/DSCResources/MSFT_SPAccessServiceApp/MSFT_SPAccessServiceApp.psm1) for example, and it would mean we have documentation for the functions in two different places (mof file and the ps1) which could lead to discrepancies on the documentation. I'm not sure IN THE FILE is necessary, as long as the help is present (which we do on build).

---

*[Tests/Integration/MSFT_xFirewall_remove.config.ps1, line 2 at r4](https://reviewable.io:443/reviews/powershell/xnetworking/173#-KaJwj2E6zksU2djG3X3:-KaVt0-LNErZ9Emkkl6A:byxvuru) ([raw file](https://github.com/powershell/xnetworking/blob/1c03d48db4e6d3f42e3026fa0fca10d75856612c/Tests/Integration/MSFT_xFirewall_remove.config.ps1#L2)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

I've tweaked this a bit by moving the $Rule into the $ConfigData object which gets passed to the Configs. I probably could have just used a single config and just passed a $ConfigData with different node properties. I just felt it was cleaner separating them (and that was the design pattern I'd used elsewhere - see xPSDesiredStateConfiguration). But happy to change it if you think it's better that way?
</blockquote></details>

Honestly I'm not sure which I would prefer, let's leave it this way for now. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/173)*

**Pull request merged**
