### PR TITLE
Added xWinsSetting resource - Fixes #302

### LINKED ISSUE #302: Create Single Instance Resource for Enabling/Disabling LMHosts Lookup
Setting LMHosts lookup is done at the system level, not on a per-adapter basis. So this should be done separately from NetBios settings.

See #193 for more information.

### PR DESCRIPTION
**Pull request by PlagueHO**
**Pull Request (PR) description**
This PR adds the xWinsSetting resource for configuring global WINS settings. It specifically allows enabling of LMHOSTS lookups and enabling/disabling of DNS resolution using WINS.

**This Pull Request (PR) fixes the following issues:**
- Fixes #302 
- Relates to #199 but does not fully complete it (another resource xWinsServer is required).

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [x] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [x] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

@johlju - would you mind reviewing when you get a chance? I based this around the code you pasted in #199. I'll plan to implement a WINS server resource at some point, but to be honest it is a low priority (I'm a little bit surprised anyone is still using WINS at all :wink:).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xnetworking/304)

### CODE REVIEW

**Comment by johlju** [comment]
@PlagueHO Awesome! I will review this tonight. WINS is a legacy we are trying to move away from... wish it could go less slowly though 😄 The script in issue #199 was used to move away from it on new deployments.

**Comment by johlju** [comment]
Looking good! Mostly non-blocking nitpicks. 

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[Modules/xNetworking/DSCResources/MSFT_xWinsSetting/MSFT_xWINSSetting.schema.mof, line 5 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/304#-L4aKGf7vAR9WmQYFtk9:-L4aKGf7vAR9WmQYFtkA:b8xc0tt) ([raw file](https://github.com/powershell/xnetworking/blob/d8191715c968147074a53f51277c6555a11bf8f3/Modules/xNetworking/DSCResources/MSFT_xWinsSetting/MSFT_xWINSSetting.schema.mof#L5)):*
> EnableLMHOSTS

I think we need to use pascal case on this (`EnableLmHosts`), even if that might look uglier. :smile:  Throughout.

---

*[Modules/xNetworking/DSCResources/MSFT_xWinsSetting/MSFT_xWINSSetting.schema.mof, line 6 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/304#-L4aKVYk-7MywgbtEpYk:-L4aKVYk-7MywgbtEpYl:b-8ggwc1) ([raw file](https://github.com/powershell/xnetworking/blob/d8191715c968147074a53f51277c6555a11bf8f3/Modules/xNetworking/DSCResources/MSFT_xWinsSetting/MSFT_xWINSSetting.schema.mof#L6)):*
> EnableDNS

I think we need to use pascal case on this (`EnableDns`), even if that might look uglier. :smile:  Throughout.

---

*[Modules/xNetworking/DSCResources/MSFT_xWinsSetting/en-US/MSFT_xWINSSetting.strings.psd1, line 8 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/304#-L4aMs3BUgRxf_1DEPV_:-L4aMs3BUgRxf_1DEPVa:b-jo6p3s) ([raw file](https://github.com/powershell/xnetworking/blob/d8191715c968147074a53f51277c6555a11bf8f3/Modules/xNetworking/DSCResources/MSFT_xWinsSetting/en-US/MSFT_xWINSSetting.strings.psd1#L8)):*
> An error result of

Does this return an error code? Using 'result' sounds to me that we get something (a result) that we expect. Not sure, but wouldn't `An error code of`, or `Error code '{0'} was returned...`, sound better?

---

*[Tests/Integration/MSFT_xWinsSetting.Integration.Tests.ps1, line 88 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/304#-L4aOSHftfwzbtcBIYB6:-L4aOSHftfwzbtcBIYB7:bfftemn) ([raw file](https://github.com/powershell/xnetworking/blob/d8191715c968147074a53f51277c6555a11bf8f3/Tests/Integration/MSFT_xWinsSetting.Integration.Tests.ps1#L88)):*
> $configData

Nitpick, non-blocking: `$configurationData`. Throughout.

---

*[Tests/Unit/MSFT_xWinsSetting.Tests.ps1, line 117 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/304#-L4aPI-xz_6rQEXxH4f3:-L4aPI-xz_6rQEXxH4f4:b57pk6a) ([raw file](https://github.com/powershell/xnetworking/blob/d8191715c968147074a53f51277c6555a11bf8f3/Tests/Unit/MSFT_xWinsSetting.Tests.ps1#L117)):*
> ```PowerShell
> 
>                 It 'Should call the expected mocks' {
>                     Assert-MockCalled -CommandName Get-ItemProperty -Exactly -Times 2
> ```

Non-blocking: You could add the ParameterFilter scriptblock on the mock to a variable, then you can reuse it on the Assert-MockCalled to verify that it actually calls the mock once for each filter.

``` 
$getItemProperty_EnableDns_ParameterFilter = {
    $Path -eq 'HKLM:\SYSTEM\CurrentControlSet\Services\NetBT\Parameters' -and $Name -eq 'EnableDNS'
}
```

---

*[Tests/Unit/MSFT_xWinsSetting.Tests.ps1, line 128 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/304#-L4aQAbXol6tn3F19sWU:-L4aQAbXol6tn3F19sWV:b-h2xxul) ([raw file](https://github.com/powershell/xnetworking/blob/d8191715c968147074a53f51277c6555a11bf8f3/Tests/Unit/MSFT_xWinsSetting.Tests.ps1#L128)):*
> ```PowerShell
> 
>             Context 'Set EnableLMHosts to enabled and EnableDNS to enabled' {
>                 Mock -CommandName Invoke-CimMethod -MockWith { @{ ReturnValue = 0 } }
> ```

Hash table braces should be on separate row. Throughout. Non-blocking since I don't know if this is the way it's made for the rest of the module.

Maybe:
```
Mock -CommandName Invoke-CimMethod -MockWith {
    @{
         ReturnValue = 0
    } 
}
```

---

*[Tests/Unit/MSFT_xWinsSetting.Tests.ps1, line 137 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/304#-L4aLUczJDIv693YZUwK:-L4aLUczJDIv693YZUwL:b-x8n34u) ([raw file](https://github.com/powershell/xnetworking/blob/d8191715c968147074a53f51277c6555a11bf8f3/Tests/Unit/MSFT_xWinsSetting.Tests.ps1#L137)):*
> ```PowerShell
> 
>                 It 'Should call expected Mocks' {
>                     Assert-MockCalled -commandName Invoke-CimMethod -Exactly -Times 1
> ```

Non-blocking:  There could be a `-ParameterFilter` on the `Assert-MockCalled` that verifies that the mock was called with the right values.

---

*[Tests/Unit/MSFT_xWinsSetting.Tests.ps1, line 137 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/304#-L4aLc2Uk1OMraXNgkb_:-L4aLc2Uk1OMraXNgkba:b-fpyqfi) ([raw file](https://github.com/powershell/xnetworking/blob/d8191715c968147074a53f51277c6555a11bf8f3/Tests/Unit/MSFT_xWinsSetting.Tests.ps1#L137)):*
> -commandName

`-CommandName` - upper 'C'. Throughout.

---

*[Tests/Unit/MSFT_xWinsSetting.Tests.ps1, line 151 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/304#-L4aLyggXX7Wnm2f-O_1:-L4aLyggXX7Wnm2f-O_2:b-x8n34u) ([raw file](https://github.com/powershell/xnetworking/blob/d8191715c968147074a53f51277c6555a11bf8f3/Tests/Unit/MSFT_xWinsSetting.Tests.ps1#L151)):*
> ```PowerShell
> 
>                 It 'Should call expected Mocks' {
>                     Assert-MockCalled -commandName Invoke-CimMethod -Exactly -Times 1
> ```

Non-blocking:  There could be a `-ParameterFilter` on the `Assert-MockCalled` that verifies that the mock was called with the right values.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/304#-:-L4aRC5D7EmAIlDoKykP:b-kmu2ak)*

**Comment by PlagueHO** [comment]
All done! Great catches all round. I hoped WINS was going away - but I know the reality of large enterprise :grin: So I might still end up implementing an xWinsServerAddress resource using CIM. Just so I can say it's done and forever forget it :grin:

---

Review status: 4 of 10 files reviewed at latest revision, 9 unresolved discussions.

---

*[Modules/xNetworking/DSCResources/MSFT_xWinsSetting/MSFT_xWINSSetting.schema.mof, line 5 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/304#-L4aKGf7vAR9WmQYFtk9:-L4cMm08rnCcH4dyrtIe:b-dzdn6t) ([raw file](https://github.com/powershell/xnetworking/blob/d8191715c968147074a53f51277c6555a11bf8f3/Modules/xNetworking/DSCResources/MSFT_xWinsSetting/MSFT_xWINSSetting.schema.mof#L5)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> EnableLMHOSTS

I think we need to use pascal case on this (`EnableLmHosts`), even if that might look uglier. :smile:  Throughout.
</blockquote></details>

Done. Although I left the ones the Registry Key names to match the case as they appear in the Registry as I felt this was appropriate.

---

*[Modules/xNetworking/DSCResources/MSFT_xWinsSetting/MSFT_xWINSSetting.schema.mof, line 6 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/304#-L4aKVYk-7MywgbtEpYk:-L4cMwb8X71NCBgot_lm:b-dzdn6t) ([raw file](https://github.com/powershell/xnetworking/blob/d8191715c968147074a53f51277c6555a11bf8f3/Modules/xNetworking/DSCResources/MSFT_xWinsSetting/MSFT_xWINSSetting.schema.mof#L6)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> EnableDNS

I think we need to use pascal case on this (`EnableDns`), even if that might look uglier. :smile:  Throughout.
</blockquote></details>

Done. Although I left the ones the Registry Key names to match the case as they appear in the Registry as I felt this was appropriate.

---

*[Modules/xNetworking/DSCResources/MSFT_xWinsSetting/en-US/MSFT_xWINSSetting.strings.psd1, line 8 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/304#-L4aMs3BUgRxf_1DEPV_:-L4cN7dliGNBmLabqPgL:b-yy3yq3) ([raw file](https://github.com/powershell/xnetworking/blob/d8191715c968147074a53f51277c6555a11bf8f3/Modules/xNetworking/DSCResources/MSFT_xWinsSetting/en-US/MSFT_xWINSSetting.strings.psd1#L8)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> An error result of

Does this return an error code? Using 'result' sounds to me that we get something (a result) that we expect. Not sure, but wouldn't `An error code of`, or `Error code '{0'} was returned...`, sound better?
</blockquote></details>

Good call - done.

---

*[Tests/Integration/MSFT_xWinsSetting.Integration.Tests.ps1, line 88 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/304#-L4aOSHftfwzbtcBIYB6:-L4cN8vrawbPn6KHqVT-:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/d8191715c968147074a53f51277c6555a11bf8f3/Tests/Integration/MSFT_xWinsSetting.Integration.Tests.ps1#L88)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> $configData

Nitpick, non-blocking: `$configurationData`. Throughout.
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xWinsSetting.Tests.ps1, line 117 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/304#-L4aPI-xz_6rQEXxH4f3:-L4cOJcwuQBLBQROjedC:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/d8191715c968147074a53f51277c6555a11bf8f3/Tests/Unit/MSFT_xWinsSetting.Tests.ps1#L117)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Non-blocking: You could add the ParameterFilter scriptblock on the mock to a variable, then you can reuse it on the Assert-MockCalled to verify that it actually calls the mock once for each filter.

``` 
$getItemProperty_EnableDns_ParameterFilter = {
    $Path -eq 'HKLM:\SYSTEM\CurrentControlSet\Services\NetBT\Parameters' -and $Name -eq 'EnableDNS'
}
```
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xWinsSetting.Tests.ps1, line 128 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/304#-L4aQAbXol6tn3F19sWU:-L4cP2f8Ce8F-E2iM0M9:bna8tk5) ([raw file](https://github.com/powershell/xnetworking/blob/d8191715c968147074a53f51277c6555a11bf8f3/Tests/Unit/MSFT_xWinsSetting.Tests.ps1#L128)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Hash table braces should be on separate row. Throughout. Non-blocking since I don't know if this is the way it's made for the rest of the module.

Maybe:
```
Mock -CommandName Invoke-CimMethod -MockWith {
    @{
         ReturnValue = 0
    } 
}
```
</blockquote></details>

Doh! Good catch - I also cleaned up the other mocks a bit.

---

*[Tests/Unit/MSFT_xWinsSetting.Tests.ps1, line 137 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/304#-L4aLUczJDIv693YZUwK:-L4cQiRo1lXNmy_j-Pnm:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/d8191715c968147074a53f51277c6555a11bf8f3/Tests/Unit/MSFT_xWinsSetting.Tests.ps1#L137)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Non-blocking:  There could be a `-ParameterFilter` on the `Assert-MockCalled` that verifies that the mock was called with the right values.
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xWinsSetting.Tests.ps1, line 137 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/304#-L4aLc2Uk1OMraXNgkb_:-L4cQinJow_tpCrxsOmE:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/d8191715c968147074a53f51277c6555a11bf8f3/Tests/Unit/MSFT_xWinsSetting.Tests.ps1#L137)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> -commandName

`-CommandName` - upper 'C'. Throughout.
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xWinsSetting.Tests.ps1, line 151 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/304#-L4aLyggXX7Wnm2f-O_1:-L4cQm9WTrEK1odo_mk6:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/d8191715c968147074a53f51277c6555a11bf8f3/Tests/Unit/MSFT_xWinsSetting.Tests.ps1#L151)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Non-blocking:  There could be a `-ParameterFilter` on the `Assert-MockCalled` that verifies that the mock was called with the right values.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/304#-:-L4cQqN1ABX8bMD_gbGg:b3m70cn)*

**Comment by johlju** [comment]
:lgtm: 

Haha. Yes, it would be good to have that xWinsServerAddress resource, at least as long as there is a Windows Server version that support WINS and are in extended support :smile: So probably throughout this decade :)

---

Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/304#-:-L4dqd5Gzi72x081XT7p:b-l19c8l)*

**Comment by PlagueHO** [comment]
Thanks @johlju

**Pull request merged**
