### PR TITLE
Adding xNetAdapterRDMA

### PR DESCRIPTION
**Pull request by rchaganti**
Adding xNetAdapterRDMA resource for configuring RDMA on network adapters.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xnetworking/165)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Thanks for resubmitting this @rchaganti - really appreciate all your work on this! Just one tiny little change if you don't mind? Then it :LGTM:

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[DSCResources/MSFT_xNetAdapterRDMA/MSFT_xNetAdapterRDMA.schema.mof, line 4 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/165#-KYMpJFk9GK0qAB3RUyw:-KYMpJFkBXpTn05eu2Ql:b-ogycdh) ([raw file](https://github.com/powershell/xnetworking/blob/95ff64dea2c664b8eae1d7b3dc9f7b81b3e34bb2/DSCResources/MSFT_xNetAdapterRDMA/MSFT_xNetAdapterRDMA.schema.mof#L4)):*
> ```
> class MSFT_xNetAdapterRDMA : OMI_BaseResource
> {
>     [Key] String Name;
> ```

Sorry to be a complete pain, but could you add the Description (from the Readme.md if you like) to the MOF files here? I'm eventually hoping we can implement the code that xSharepoint uses which uses the description from the MOF to generate the documentation.

---

*[DSCResources/MSFT_xNetAdapterRDMA/MSFT_xNetAdapterRDMA.schema.mof, line 5 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/165#-KYMpjsrENkDjzNmseFt:-KYMpjss8rfwK3124iDA:bs4q9op) ([raw file](https://github.com/powershell/xnetworking/blob/95ff64dea2c664b8eae1d7b3dc9f7b81b3e34bb2/DSCResources/MSFT_xNetAdapterRDMA/MSFT_xNetAdapterRDMA.schema.mof#L5)):*
> ```
> {
>     [Key] String Name;
>     [Write] Boolean Enabled;
> ```

Ditto.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/165#-:-KYMq1RN2fX-nWnJ7w1n:b-8arbil)*

**Comment by rchaganti** [comment]
Review status: 8 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[DSCResources/MSFT_xNetAdapterRDMA/MSFT_xNetAdapterRDMA.schema.mof, line 4 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/165#-KYMpJFk9GK0qAB3RUyw:-KYMucegDg0NzLeSMAbN:brcjnfi) ([raw file](https://github.com/powershell/xnetworking/blob/95ff64dea2c664b8eae1d7b3dc9f7b81b3e34bb2/DSCResources/MSFT_xNetAdapterRDMA/MSFT_xNetAdapterRDMA.schema.mof#L4)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Sorry to be a complete pain, but could you add the Description (from the Readme.md if you like) to the MOF files here? I'm eventually hoping we can implement the code that xSharepoint uses which uses the description from the MOF to generate the documentation.
</blockquote></details>

Complete

---

*[DSCResources/MSFT_xNetAdapterRDMA/MSFT_xNetAdapterRDMA.schema.mof, line 5 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/165#-KYMpjsrENkDjzNmseFt:-KYMudQh39ob9nWIsAQw:brcjnfi) ([raw file](https://github.com/powershell/xnetworking/blob/95ff64dea2c664b8eae1d7b3dc9f7b81b3e34bb2/DSCResources/MSFT_xNetAdapterRDMA/MSFT_xNetAdapterRDMA.schema.mof#L5)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Ditto.
</blockquote></details>

Complete

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/165)*

**Comment by rchaganti** [comment]
Done!

**Comment by rchaganti** [comment]
@PlagueHO do you know why the build is failing? Especially for xFirewall?

**Comment by PlagueHO** [comment]
@rchaganti - Ok, I know why the integration tests are failing. A [change](https://github.com/PowerShell/DscResource.Tests/pull/79) was made to the DSCResources.Tests a few weeks back which caused this. Basically the tests were changed over to use the Pester $TestDrive as working storage.

The solution is to change the line:
```powershell
& "$($script:DSCResourceName)_Config" -OutputPath $TestEnvironment.WorkingFolder
```
in each MSFT_*.Integration.Tests.ps1 file to read:
```powershell
& "$($script:DSCResourceName)_Config" -OutputPath $TestDrive
```
Would you mind making this change for us?

The problem with xFirewall is actually caused by a bug in DSCResource.Tests. I'll actually submit a PR to DSCResource.Tests to fix this, but to work around the problem:

Change the filename of the xFirewall schema file ```MSFT_xFirewall.Schema.mof``` to be use a lower case .Schema (the capital S is the problem). E.g. rename it to ```MSFT_xFirewall.schema.mof```

Thanks again!

**Comment by PlagueHO** [comment]
@rchaganti - I've submitted a PR to DSCResources.Tests to fix the .schema issue:
https://github.com/PowerShell/DscResource.Tests/pull/82

**Comment by rchaganti** [comment]
I updated the integration test file based on your feedback.

**Comment by PlagueHO** [comment]
@rchaganti - hmm. Something else must be going on here. I'll take a look through this tonight and advise exactly what needs to be fixed. Sorry about all this.

The fix for the .Schema has gone through in DSCResources.Tests so that should be resolved.

**Comment by PlagueHO** [comment]
Hi @rchaganti - ok. Found the problem. There was another change to DSCResource.Tests that effected this. Maybe the best thing for me to do is submit a new PR with all the fixes to support the new tests in place and get that merged.

You can then merge that with your changes. Saves me having to explain all the fixes here. What do you reckon?

**Comment by PlagueHO** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r5.
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[Tests/Integration/MSFT_xNetAdapterRDMA.Integration.Tests.ps1, line 36 at r5](https://reviewable.io:443/reviews/powershell/xnetworking/165#-KYPTR_L3QZlLr0FAn1N:-KYPTR_LCRR6CCCGniF2:b-vwhypo) ([raw file](https://github.com/powershell/xnetworking/blob/4afaa5ede4b8b3fe4fb9873b361b0471e6491866/Tests/Integration/MSFT_xNetAdapterRDMA.Integration.Tests.ps1#L36)):*
> ```PowerShell
>             {
>                 & "$($script:DSCResourceName)_Config" -OutputPath $TestDrive
>                 Start-DscConfiguration -Path $TestEnvironment.WorkingFolder `
> ```

My bad - you'll also need to change ```$TestEnvironment.Working``` folder here to ```$TestDrive```.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/165)*

**Comment by rchaganti** [comment]
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[Tests/Integration/MSFT_xNetAdapterRDMA.Integration.Tests.ps1, line 36 at r5](https://reviewable.io:443/reviews/powershell/xnetworking/165#-KYPTR_L3QZlLr0FAn1N:-KYSBNRNM8iRgt5-V8e5:bb6un1j) ([raw file](https://github.com/powershell/xnetworking/blob/4afaa5ede4b8b3fe4fb9873b361b0471e6491866/Tests/Integration/MSFT_xNetAdapterRDMA.Integration.Tests.ps1#L36)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

My bad - you'll also need to change ```$TestEnvironment.Working``` folder here to ```$TestDrive```.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/165)*

**Comment by rchaganti** [comment]
readme conflict again!?

**Comment by PlagueHO** [comment]
@rchaganti - unfortunately, yes. This is because PR #168 had to go in so that your tests would not fail. PR #168 included a new entry in the Readme.md to identify the change. But the conflict should be easy to resolve I think. Sorry about that.

**Comment by PlagueHO** [comment]
@rchaganti - I didn't realize there was a new GitHub feature that allowed me to resolve the conflict for you. So it is resolved.

**Comment by PlagueHO** [comment]
Reviewed 1 of 1 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/165)*

**Pull request merged**
