### PR TITLE
Update All Resources to use CommonResourceHelper and HQRM Work - Fixes #152

### LINKED ISSUE #152: Add CommonResourceHelper.psm1 module and update to use it
The xPSDesiredStateConfiguration includes a [CommonResourceHelper.psm1](https://github.com/PowerShell/xPSDesiredStateConfiguration/blob/dev/DSCResources/CommonResourceHelper.psm1) that includes several common functions.

xNetworking has quite a lot of replicated code that is contained in the CommonResourceHelper.psm1 file. So there would be some benefit to changing xNetworking to use these patterns (including making the move to HQRM easier).

### PR DESCRIPTION
**Pull request by PlagueHO**
This PR Converts all resources to use the CommonResourceHelper.psm1 module to load localization files. This includes moving strings out of the resource and into .strings.psd1 files where they were still inside the resource.

Most of the HQRM work (#135) has now been completed. Note: I used many of the practices set out in PSDscResources as well as the feedback I received when working on getting my other resources up to HQRM. But as these changes are significant, I hopefully haven't missed too much stuff.

This also coincidentally fixes all the PSSA issues except the Invoke-Expression ones ( #166).

Sorry about the size of this @tysonjhayes - but hopefully once it is complete we're almost ready to move this to HQRM. The only things that I think may still need to be resolved are #177 and #176 as well as the remaining PSSA issue.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xnetworking/178)

### CODE REVIEW

**Comment by tysonjhayes** [comment]
Im thinking we move the assert-resourceproperty to common in a seperate PR. I reworked it in my branch to use the terminating error function but didmt get it completed.

I noted we can remove most of the imports with a change to xnetworking.psd1 i think it really would clean up some of these.

On a side note. A few get-targetresource functions seemed to be duplicating logic used in test-targetresource specifically evaluating ensure. What is the value of this? Honestly im thinking we could remove that (seperate PR) to differentiate the logic and make it a bit more of a get current state. Thoughts?

---

Reviewed 52 of 52 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[Modules/xNetworking/DSCResources/MSFT_xDefaultGatewayAddress/MSFT_xDefaultGatewayAddress.psm1, line 2 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/178#-KajK5NeQFqfRIxTgROy:-KajK5NeQFqfRIxTgROz:b-y04dsm) ([raw file](https://github.com/powershell/xnetworking/blob/2df2ffd6e3cab185c734e2ef6ab70a46a69db64c/Modules/xNetworking/DSCResources/MSFT_xDefaultGatewayAddress/MSFT_xDefaultGatewayAddress.psm1#L2)):*
> ```PowerShell
> # Get the path to the shared modules folder
> $script:ModulesFolderPath = Join-Path -Path (Split-Path -Path (Split-Path -Path $PSScriptRoot -Parent)) `
> ```

All of this is uncesessry if you take [this change](https://github.com/tysonjhayes/xNetworking/blob/pssa_warning/Modules/xNetworking/xNetworking.psd1#L29) to xNetworking.psd1 - it'll load all of the modules you are doing now on loading of xNetworking.

If we want to keep this style of logic I'd suggest loading Common first as it loads ResourceHelper at the start.

---

*[Modules/xNetworking/DSCResources/MSFT_xDhcpClient/MSFT_xDhcpClient.psm1, line 207 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/178#-KajKcWPjzvnQeCRUue1:-KajKcWPjzvnQeCRUue2:b86oqmx) ([raw file](https://github.com/powershell/xnetworking/blob/2df2ffd6e3cab185c734e2ef6ab70a46a69db64c/Modules/xNetworking/DSCResources/MSFT_xDhcpClient/MSFT_xDhcpClient.psm1#L207)):*
> ```PowerShell
>     The desired state of the DHCP Client.
> #>
> function Assert-ResourceProperty {
> ```

I believe this gets called in a couple of resources (reviewable is making it hard to tell) - we should just move it to the Common module and call it from there.

---

*[Modules/xNetworking/DSCResources/MSFT_xDnsConnectionSuffix/MSFT_xDnsConnectionSuffix.psm1, line 76 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/178#-KajL9CzrFHsiJG-Jilu:-KajL9CzrFHsiJG-Jilv:b-mxr50a) ([raw file](https://github.com/powershell/xnetworking/blob/2df2ffd6e3cab185c734e2ef6ab70a46a69db64c/Modules/xNetworking/DSCResources/MSFT_xDnsConnectionSuffix/MSFT_xDnsConnectionSuffix.psm1#L76)):*
> ```PowerShell
>         UseSuffixWhenRegistering = $dnsClient.UseSuffixWhenRegistering
>     }
>     if ($Ensure -eq 'Present')
> ```

This might just be an issue we open but looking at this code it doesn't really make a ton of sense. Why do we care about if it's currently Present/Absent or any of the logic for testing this? I kind of feel like we can just return $targetResource and chop everything below this line.

---

*[Modules/xNetworking/DSCResources/MSFT_xDnsConnectionSuffix/MSFT_xDnsConnectionSuffix.psm1, line 247 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/178#-KajLU-7CznEW0WPhxHP:-KajLU-7CznEW0WPhxHQ:b-4gbn98) ([raw file](https://github.com/powershell/xnetworking/blob/2df2ffd6e3cab185c734e2ef6ab70a46a69db64c/Modules/xNetworking/DSCResources/MSFT_xDnsConnectionSuffix/MSFT_xDnsConnectionSuffix.psm1#L247)):*
> ```PowerShell
>         Write-Verbose -Message $LocalizedData.ResourceInDesiredState
>     }
>     else {
> ```

I believe this curly brace should be on a new line.

---

*[Modules/xNetworking/DSCResources/MSFT_xDNSServerAddress/MSFT_xDNSServerAddress.psm1, line 254 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/178#-KajLfTkxfwSzLzw2IBj:-KajLfTkxfwSzLzw2IBk:b-txy9ut) ([raw file](https://github.com/powershell/xnetworking/blob/2df2ffd6e3cab185c734e2ef6ab70a46a69db64c/Modules/xNetworking/DSCResources/MSFT_xDNSServerAddress/MSFT_xDNSServerAddress.psm1#L254)):*
> ```PowerShell
> #>
> 
> function Assert-ResourceProperty
> ```

So now that I've seen this come up again I will say we should move it to the common resource.

---

*[Modules/xNetworking/DSCResources/MSFT_xNetAdapterBinding/MSFT_xNetAdapterBinding.psm1, line 241 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/178#-KajMKjEKP_PKgn1dIvZ:-KajMKjFWH82Es0y7qXq:bf5ovan) ([raw file](https://github.com/powershell/xnetworking/blob/2df2ffd6e3cab185c734e2ef6ab70a46a69db64c/Modules/xNetworking/DSCResources/MSFT_xNetAdapterBinding/MSFT_xNetAdapterBinding.psm1#L241)):*
> ```PowerShell
>     Specifies if the component ID for the Interface should be Enabled or Disabled.
> #>
> function Get-Binding {
> ```

Curly brace should be on a new line.

---

*[Modules/xNetworking/DSCResources/MSFT_xNetBIOS/MSFT_xNetBIOS.psm1, line 179 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/178#-KajPhU6SWoCh5UwRgA3:-KajPhU6SWoCh5UwRgA4:b-lq64kp) ([raw file](https://github.com/powershell/xnetworking/blob/2df2ffd6e3cab185c734e2ef6ab70a46a69db64c/Modules/xNetworking/DSCResources/MSFT_xNetBIOS/MSFT_xNetBIOS.psm1#L179)):*
> ```PowerShell
>     }
> 
>     $nicConfig = $NIC | Get-CimAssociatedInstance -ResultClassName Win32_NetworkAdapterConfiguration
> ```

nit: piping like this imo isn't really best practice, and kind of slow,

---

*[Modules/xNetworking/DSCResources/MSFT_xRoute/MSFT_xRoute.psm1, line 443 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/178#-KajRSoyaJDca3heYfA3:-KajRSoyaJDca3heYfA4:b-zgps4i) ([raw file](https://github.com/powershell/xnetworking/blob/2df2ffd6e3cab185c734e2ef6ab70a46a69db64c/Modules/xNetworking/DSCResources/MSFT_xRoute/MSFT_xRoute.psm1#L443)):*
> ```PowerShell
> 
> #>
> Function Get-Route {
> ```

Curly brace on new line.

---

*[Modules/xNetworking/DSCResources/MSFT_xRoute/MSFT_xRoute.psm1, line 530 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/178#-KajRZJ2-HFF40PFGthC:-KajRZJ2-HFF40PFGthD:b-zgps4i) ([raw file](https://github.com/powershell/xnetworking/blob/2df2ffd6e3cab185c734e2ef6ab70a46a69db64c/Modules/xNetworking/DSCResources/MSFT_xRoute/MSFT_xRoute.psm1#L530)):*
> ```PowerShell
>     Specifies a preferred lifetime in seconds of an IP route.
> #>
> Function Assert-ResourceProperty {
> ```

Curly brace on new line.

---

*[Tests/Integration/MSFT_xDnsClientGlobalSetting.Integration.Tests.ps1, line 83 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/178#-KajR-ZXgRYK_2gNfDTk:-KajR-ZY-oKqU6nBetOa:b-1emjdk) ([raw file](https://github.com/powershell/xnetworking/blob/2df2ffd6e3cab185c734e2ef6ab70a46a69db64c/Tests/Integration/MSFT_xDnsClientGlobalSetting.Integration.Tests.ps1#L83)):*
> ```PowerShell
>         foreach ($parameter in $parameterList)
>         {
>             $parameterSource = (Invoke-Expression -Command "`$DnsClientGlobalSettingNew.$($parameter.name)")
> ```

Considering this is considered bad practice should we be adding this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/178#-:-KajRbKDBsIbLfTkdDTK:b-mjuuf4)*

**Comment by tysonjhayes** [comment]
Review status: 32 of 48 files reviewed at latest revision, 5 unresolved discussions.

---

*[Modules/xNetworking/DSCResources/MSFT_xDefaultGatewayAddress/MSFT_xDefaultGatewayAddress.psm1, line 2 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/178#-KajK5NeQFqfRIxTgROy:-KakQR9icKr_nhBFgl3v:b7quaaw) ([raw file](https://github.com/powershell/xnetworking/blob/2df2ffd6e3cab185c734e2ef6ab70a46a69db64c/Modules/xNetworking/DSCResources/MSFT_xDefaultGatewayAddress/MSFT_xDefaultGatewayAddress.psm1#L2)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

I definitely love this method much better. However, I couldn't get it to work without actually importing xNetorking.psd1 first. But it is still a great improvement. Let me know if you can see what I'm doing wrong that is preventing xNetworking from automatically importing when the resource module is used when applying a config.
</blockquote></details>

I'll work on it, I know Sharepoint uses this style (which is where I got it from) and I didn't have a bunch of time to play with it. 

---

*[Modules/xNetworking/DSCResources/MSFT_xDhcpClient/MSFT_xDhcpClient.psm1, line 207 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/178#-KajKcWPjzvnQeCRUue1:-KakQmxBna2gJV0b-FSc:bahwhhr) ([raw file](https://github.com/powershell/xnetworking/blob/2df2ffd6e3cab185c734e2ef6ab70a46a69db64c/Modules/xNetworking/DSCResources/MSFT_xDhcpClient/MSFT_xDhcpClient.psm1#L207)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

This is actually different code for each resource - it is used to validate the parameters passed to a specific resource. I renamed it because it was suggested that Assert was the proper verb to use for this (when I was working on xStorage stuff recently).
</blockquote></details>

Ah well I wasn't looking at it to deeply, we could refactor them to use the new-invalidargumentexception though [right](https://github.com/tysonjhayes/xNetworking/blob/pssa_warning/Modules/xNetworking/Modules/NetworkingDsc.Common/NetworkingDsc.Common.psm1#L99)?

---

*[Modules/xNetworking/DSCResources/MSFT_xDnsConnectionSuffix/MSFT_xDnsConnectionSuffix.psm1, line 76 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/178#-KajL9CzrFHsiJG-Jilu:-KakR9_DgF7Zwm5ZM3q-:bdeyqme) ([raw file](https://github.com/powershell/xnetworking/blob/2df2ffd6e3cab185c734e2ef6ab70a46a69db64c/Modules/xNetworking/DSCResources/MSFT_xDnsConnectionSuffix/MSFT_xDnsConnectionSuffix.psm1#L76)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

You're completely right. I'm really scratching my head trying to work out the behaviour/purpose for this code. It does feel like we should be able to clear out the code like you say. I'll work on it.
</blockquote></details>

I'm fine with it being another PR I think it may be worth a review on all of our get-targetresource funcitons.

---

*[Modules/xNetworking/DSCResources/MSFT_xDnsConnectionSuffix/MSFT_xDnsConnectionSuffix.psm1, line 247 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/178#-KajLU-7CznEW0WPhxHP:-KakR1D_N_4vjIABMV-T:bufbo89) ([raw file](https://github.com/powershell/xnetworking/blob/2df2ffd6e3cab185c734e2ef6ab70a46a69db64c/Modules/xNetworking/DSCResources/MSFT_xDnsConnectionSuffix/MSFT_xDnsConnectionSuffix.psm1#L247)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Good catch! There were also some other style violations (in the param blocks) in this resource which I fixed. Plus the ; at the end of lines (removed for consistency).
</blockquote></details>

VS Powershell just took a merge to automatically change braces on new lines looking forward to that in the next release. :grin: 

---

*[Modules/xNetworking/DSCResources/MSFT_xNetBIOS/MSFT_xNetBIOS.psm1, line 179 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/178#-KajPhU6SWoCh5UwRgA3:-KakQBbwFqCj6F0n3fkv:b-1hgjw4) ([raw file](https://github.com/powershell/xnetworking/blob/2df2ffd6e3cab185c734e2ef6ab70a46a69db64c/Modules/xNetworking/DSCResources/MSFT_xNetBIOS/MSFT_xNetBIOS.psm1#L179)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

TBH: I'm not a fan of the style in this entire resource. It has all kinds of bad practices (but not violations). So I definitely think it needs a fix up. So 100% agree. I'll put some time into cleaning up this one (but have run out tonight).
</blockquote></details>

We can take them as separate pull requests too. This work is mostly to get the style up to snuff.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/178)*

**Comment by tysonjhayes** [comment]
Review status: 32 of 48 files reviewed at latest revision, 5 unresolved discussions.

---

*[Modules/xNetworking/DSCResources/MSFT_xDefaultGatewayAddress/MSFT_xDefaultGatewayAddress.psm1, line 2 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/178#-KajK5NeQFqfRIxTgROy:-KakRP4PSAiUC-LBXmMa:b-lngqdb) ([raw file](https://github.com/powershell/xnetworking/blob/2df2ffd6e3cab185c734e2ef6ab70a46a69db64c/Modules/xNetworking/DSCResources/MSFT_xDefaultGatewayAddress/MSFT_xDefaultGatewayAddress.psm1#L2)):*
<details><summary><i>Previously, tysonjhayes (Tyson J. Hayes) wrote…</i></summary><blockquote>

I'll work on it, I know Sharepoint uses this style (which is where I got it from) and I didn't have a bunch of time to play with it. 
</blockquote></details>

BTW [this](https://github.com/PowerShell/SharePointDsc/blob/dev/Modules/SharePointDsc/SharePointDsc.psd1#L66) is where I saw the code.  I was still deeply refactoring some things so I could be mislead on its intention.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/178)*

**Comment by tysonjhayes** [comment]
Review status: 32 of 48 files reviewed at latest revision, 5 unresolved discussions.

---

*[Modules/xNetworking/DSCResources/MSFT_xDefaultGatewayAddress/MSFT_xDefaultGatewayAddress.psm1, line 2 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/178#-KajK5NeQFqfRIxTgROy:-KakRv1aBthnW10wWD6q:b-qcxdsn) ([raw file](https://github.com/powershell/xnetworking/blob/2df2ffd6e3cab185c734e2ef6ab70a46a69db64c/Modules/xNetworking/DSCResources/MSFT_xDefaultGatewayAddress/MSFT_xDefaultGatewayAddress.psm1#L2)):*
<details><summary><i>Previously, tysonjhayes (Tyson J. Hayes) wrote…</i></summary><blockquote>

BTW [this](https://github.com/PowerShell/SharePointDsc/blob/dev/Modules/SharePointDsc/SharePointDsc.psd1#L66) is where I saw the code.  I was still deeply refactoring some things so I could be mislead on its intention.
</blockquote></details>

And I can see the use case of [Get-SPDscFarmVersionInfo defined in Util](https://github.com/PowerShell/SharePointDsc/blob/d2d0feddff13904f1910a0998e6e7818e2c42125/Modules/SharePointDsc/Modules/SharePointDsc.Util/SharePointDsc.Util.psm1#L42) and used in one of the [resources](https://github.com/PowerShell/SharePointDsc/blob/a10064754d3b7f1999add48e16815e73c1231f65/Modules/SharePointDsc/DSCResources/MSFT_SPProductUpdate/MSFT_SPProductUpdate.psm1#L139) so ¯\\_(ツ)_/¯

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/178)*

**Comment by PlagueHO** [comment]
Review status: 32 of 48 files reviewed at latest revision, 5 unresolved discussions.

---

*[Modules/xNetworking/DSCResources/MSFT_xDefaultGatewayAddress/MSFT_xDefaultGatewayAddress.psm1, line 2 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/178#-KajK5NeQFqfRIxTgROy:-KakXtyvMR5AwpPaq6w_:bm4qved) ([raw file](https://github.com/powershell/xnetworking/blob/2df2ffd6e3cab185c734e2ef6ab70a46a69db64c/Modules/xNetworking/DSCResources/MSFT_xDefaultGatewayAddress/MSFT_xDefaultGatewayAddress.psm1#L2)):*
<details><summary><i>Previously, tysonjhayes (Tyson J. Hayes) wrote…</i></summary><blockquote>

And I can see the use case of [Get-SPDscFarmVersionInfo defined in Util](https://github.com/PowerShell/SharePointDsc/blob/d2d0feddff13904f1910a0998e6e7818e2c42125/Modules/SharePointDsc/Modules/SharePointDsc.Util/SharePointDsc.Util.psm1#L42) and used in one of the [resources](https://github.com/PowerShell/SharePointDsc/blob/a10064754d3b7f1999add48e16815e73c1231f65/Modules/SharePointDsc/DSCResources/MSFT_SPProductUpdate/MSFT_SPProductUpdate.psm1#L139) so ¯\\_(ツ)_/¯
</blockquote></details>

Cool! I'll dig about. I've almost run out of time tonight, but I'll look further into it. I definitely want to try and get this Invoke-Expression checked out before I head to bed.

---

*[Modules/xNetworking/DSCResources/MSFT_xDhcpClient/MSFT_xDhcpClient.psm1, line 207 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/178#-KajKcWPjzvnQeCRUue1:-KakXV8evD3ElHh26EJU:b-l3cp2l) ([raw file](https://github.com/powershell/xnetworking/blob/2df2ffd6e3cab185c734e2ef6ab70a46a69db64c/Modules/xNetworking/DSCResources/MSFT_xDhcpClient/MSFT_xDhcpClient.psm1#L207)):*
<details><summary><i>Previously, tysonjhayes (Tyson J. Hayes) wrote…</i></summary><blockquote>

Ah well I wasn't looking at it to deeply, we could refactor them to use the new-invalidargumentexception though [right](https://github.com/tysonjhayes/xNetworking/blob/pssa_warning/Modules/xNetworking/Modules/NetworkingDsc.Common/NetworkingDsc.Common.psm1#L99)?
</blockquote></details>

Absolutely! I've already raised the issue: https://github.com/PowerShell/xNetworking/issues/176

---

*[Modules/xNetworking/DSCResources/MSFT_xDnsConnectionSuffix/MSFT_xDnsConnectionSuffix.psm1, line 76 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/178#-KajL9CzrFHsiJG-Jilu:-KakXHXwEhmJEDi5jOwE:b-kyf56z) ([raw file](https://github.com/powershell/xnetworking/blob/2df2ffd6e3cab185c734e2ef6ab70a46a69db64c/Modules/xNetworking/DSCResources/MSFT_xDnsConnectionSuffix/MSFT_xDnsConnectionSuffix.psm1#L76)):*
<details><summary><i>Previously, tysonjhayes (Tyson J. Hayes) wrote…</i></summary><blockquote>

I'm fine with it being another PR I think it may be worth a review on all of our get-targetresource funcitons.
</blockquote></details>

Get's my vote :grin:

---

*[Modules/xNetworking/DSCResources/MSFT_xDnsConnectionSuffix/MSFT_xDnsConnectionSuffix.psm1, line 247 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/178#-KajLU-7CznEW0WPhxHP:-KakXMlEin0uwCvNxoSS:b-42ydf7) ([raw file](https://github.com/powershell/xnetworking/blob/2df2ffd6e3cab185c734e2ef6ab70a46a69db64c/Modules/xNetworking/DSCResources/MSFT_xDnsConnectionSuffix/MSFT_xDnsConnectionSuffix.psm1#L247)):*
<details><summary><i>Previously, tysonjhayes (Tyson J. Hayes) wrote…</i></summary><blockquote>

VS Powershell just took a merge to automatically change braces on new lines looking forward to that in the next release. :grin: 
</blockquote></details>

I didn't know that! That will be awesome! ++

---

*[Modules/xNetworking/DSCResources/MSFT_xNetBIOS/MSFT_xNetBIOS.psm1, line 179 at r1](https://reviewable.io:443/reviews/powershell/xnetworking/178#-KajPhU6SWoCh5UwRgA3:-KakXSa4nlCTGmkZ2A59:byf291v) ([raw file](https://github.com/powershell/xnetworking/blob/2df2ffd6e3cab185c734e2ef6ab70a46a69db64c/Modules/xNetworking/DSCResources/MSFT_xNetBIOS/MSFT_xNetBIOS.psm1#L179)):*
<details><summary><i>Previously, tysonjhayes (Tyson J. Hayes) wrote…</i></summary><blockquote>

We can take them as separate pull requests too. This work is mostly to get the style up to snuff.
</blockquote></details>

Cool cool.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/178)*

**Comment by tysonjhayes** [comment]
Let's back out all of the invoke-expression changes for now and keep this to style changes. These changes are making my machine and reviewable weep every time I open it. So let's revert the failed changes for now and get a seperate (smaller) PR open for now. Let's start with Firewall until we can nail down what's going on.

---

Reviewed 14 of 16 files at r2, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[Modules/xNetworking/DSCResources/MSFT_xDnsClientGlobalSetting/MSFT_xDnsClientGlobalSetting.psm1, line 110 at r3](https://reviewable.io:443/reviews/powershell/xnetworking/178#-Kan5J0k9kOAazkdjA1l:-Kan5J0lWvRFS1nLjDk1:b-b45d22) ([raw file](https://github.com/powershell/xnetworking/blob/0c526b4d940dbe49609db8393823243b904e3b56/Modules/xNetworking/DSCResources/MSFT_xDnsClientGlobalSetting/MSFT_xDnsClientGlobalSetting.psm1#L110)):*
> ```PowerShell
>     {
>         $parameterSource = $dnsClientGlobalSetting.$($parameter.name)
>         $parameterNew = (Get-Variable -Name ($parameter.name)).Value
> ```

Interesting, it wouldn't have occurred to me to do this. Good idea.

---

*[Modules/xNetworking/DSCResources/MSFT_xFirewall/MSFT_xFirewall.data.psd1, line 3 at r3](https://reviewable.io:443/reviews/powershell/xnetworking/178#-Kan5r6c50HSevaeosWy:-Kan5r6c50HSevaeosWz:bxmcw16) ([raw file](https://github.com/powershell/xnetworking/blob/0c526b4d940dbe49609db8393823243b904e3b56/Modules/xNetworking/DSCResources/MSFT_xFirewall/MSFT_xFirewall.data.psd1#L3)):*
> ```PowerShell
> @{
>     ParameterList = @(
>         @{ Name = 'Name';                Source = 'Name';                               Variable = 'FirewallRule'; Type = 'String'                  }
> ```

Why is this change required? Does Source not work or are you trying to be clearer on intention?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/178#-:-KanN6dTX699mCSaNyQ4:b-916do6)*

**Comment by PlagueHO** [comment]
@TysonJHayes - cool. I'll back the last few commits out into a new branch. I actually know what the problem is, but I just didn't have time to finish the code (it was getting a bit late). I was committing as I went along because I've been having trouble running tests on my dev machine since the PR was made to move everything into a subfolder - probably some old versionof xNetworking I've got floating around on my machine somewhere.

Anyway, I'll put this change into a completely separate PR.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[Modules/xNetworking/DSCResources/MSFT_xDnsClientGlobalSetting/MSFT_xDnsClientGlobalSetting.psm1, line 110 at r3](https://reviewable.io:443/reviews/powershell/xnetworking/178#-Kan5J0k9kOAazkdjA1l:-KapBjFp9bJgs0A4RdxO:byhcxdk) ([raw file](https://github.com/powershell/xnetworking/blob/0c526b4d940dbe49609db8393823243b904e3b56/Modules/xNetworking/DSCResources/MSFT_xDnsClientGlobalSetting/MSFT_xDnsClientGlobalSetting.psm1#L110)):*
<details><summary><i>Previously, tysonjhayes (Tyson J. Hayes) wrote…</i></summary><blockquote>

Interesting, it wouldn't have occurred to me to do this. Good idea.
</blockquote></details>

I'm sure there is probably other ways to do this too.

---

*[Modules/xNetworking/DSCResources/MSFT_xFirewall/MSFT_xFirewall.data.psd1, line 3 at r3](https://reviewable.io:443/reviews/powershell/xnetworking/178#-Kan5r6c50HSevaeosWy:-KapBrHaq7tdI-FRZeKV:bnon4x4) ([raw file](https://github.com/powershell/xnetworking/blob/0c526b4d940dbe49609db8393823243b904e3b56/Modules/xNetworking/DSCResources/MSFT_xFirewall/MSFT_xFirewall.data.psd1#L3)):*
<details><summary><i>Previously, tysonjhayes (Tyson J. Hayes) wrote…</i></summary><blockquote>

Why is this change required? Does Source not work or are you trying to be clearer on intention?
</blockquote></details>

The reason is that the Get-Variable cmdlet can only be used to select the object ($properties or $firewallrule) to retrieve the properties from. Once we've got the object we have to get the named property (and actually properties of that property too). The only way to do this is to specify each property variable name seperately. Therefore separating the data elements made things alot simpler and the code quicker (otherwise I would have had to use a -split).

E.g:
This will not work:
```powershell
$source = 'MyObject.Property1.Property2'
Get-Variable -Name $source
```

This will not work either (which is actually what I'm currently doing - which is where the bug is):
```powershell
$source = 'MyObject.Property1.Property2'
$props = 'Property1.Property2'
(Get-Variable -Name $source).Value.$props
```

But this will work (which was is going to be my next change):
```powershell
$source = 'MyObject'
$prop1 = 'Property1'
$prop2 = 'Property2'
(Get-Variable -Name $source).Value.$prop1.$prop2
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/178#-:-KapAkWDIaLlHb8fmdox:b-npk67b)*

**Comment by PlagueHO** [comment]
@tysonjhayes - I've rolled back the Invoke-Expression commits. So hopefully this should be ready to merge. I'll work on the Invoke-Expression change in a separate branch and submit it with another PR.

**Pull request merged**
