### PR TITLE
Add xIPAddressOption resource

### PR DESCRIPTION
**Pull request by claudiospizzi**
**Pull Request (PR) description**
Add a new resource called xIPAddressOption to change IP address specific options. At the moment, only the SkipAsSource options is implemented.

**This Pull Request (PR) fixes the following issues:**
No issue, new feature.

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [x] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [x] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xnetworking/285)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Great job @claudiospizzi and thank you very much for submitting this.

I'm just wondering if it wouldn't be more straight forward to add this as a new parameter to the xIPAddress resource? This would also allow it to work in the case of DHCP or if the IP Address is not known by specifying only the InterfaceAlias and AddressFamily.

**Comment by claudiospizzi** [comment]
Hi @PlagueHO

The problem with xIPAddress is, that we can have multiple addresses, because the xIPAddress always configures the whole interface. There are options like SkipAsSource, which can be different for the ip addresses on the same interface. This is why I've decided to go with a dedicated resource.

SkipAsSource is normally used only on additional IP addresses, which are configured manually, not on the primary DHCP assigned address.

**Comment by PlagueHO** [comment]
Ah right - I see! Just wanted to make sure :grin:

I'll get onto the review first thing tomorrow (it's getting late here now). Thanks again!

**Comment by PlagueHO** [comment]
This is a superb submission @claudiospizzi - only some really minor tweaks! Great job and thank you very much for your work on this - it is greatly appreciated!

---

Reviewed 9 of 10 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[README.md, line 7 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/285#-KzB21cNEjnqVtfDTwqd:-KzB21cNEjnqVtfDTwqe:b-twomix) ([raw file](https://github.com/powershell/xnetworking/blob/896dc4758a0b83cc5385fa4223f52bad56347ba2/README.md#L7)):*
> ```Markdown
> - **xFirewall**: Sets a node's firewall rules.
> - **xIPAddress**: Sets a node's IP address(s).
> - **xIPAddressOption**: Sets a IP address option.
> ```

Nitpick:
Sets _an_ IP address option.

---

*[Modules/xNetworking/DSCResources/MSFT_xIPAddressOption/MSFT_xIPAddressOption.psm1, line 4 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/285#-KzB2BWS6PdAc1bjm2kU:-KzB2BWS6PdAc1bjm2kV:bo5zwer) ([raw file](https://github.com/powershell/xnetworking/blob/896dc4758a0b83cc5385fa4223f52bad56347ba2/Modules/xNetworking/DSCResources/MSFT_xIPAddressOption/MSFT_xIPAddressOption.psm1#L4)):*
> ```PowerShell
> 
> # Import the Networking Common Modules
> Import-Module -Name (Join-Path -Path $modulePath `
> ```

The alignment seems to be a bit out on this file. Can you correct using Visual Studio Code Format Document?

https://dscottraynsford.wordpress.com/2017/11/18/auto-formatting-powershell-in-visual-studio-code/

---

*[Modules/xNetworking/DSCResources/MSFT_xIPAddressOption/MSFT_xIPAddressOption.psm1, line 41 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/285#-KzB2X7qJjXsfrpFONIu:-KzB2X7qJjXsfrpFONIv:bthyeeg) ([raw file](https://github.com/powershell/xnetworking/blob/896dc4758a0b83cc5385fa4223f52bad56347ba2/Modules/xNetworking/DSCResources/MSFT_xIPAddressOption/MSFT_xIPAddressOption.psm1#L41)):*
> ```PowerShell
>         $IPAddress,
> 
>         [Parameter()]
> ```

You could have used a Boolean parameter type for this instead of a string. Is it possible to change to Boolean type?

See: https://github.com/PowerShell/xNetworking/blob/dev/Modules/xNetworking/DSCResources/MSFT_xFirewall/MSFT_xFirewall.schema.mof#L32

---

*[Modules/xNetworking/DSCResources/MSFT_xIPAddressOption/MSFT_xIPAddressOption.schema.mof, line 5 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/285#-KzB33vceTf75BK4tyEB:-KzB33vdZDQFO-Bjlswu:b-3akjhw) ([raw file](https://github.com/powershell/xnetworking/blob/896dc4758a0b83cc5385fa4223f52bad56347ba2/Modules/xNetworking/DSCResources/MSFT_xIPAddressOption/MSFT_xIPAddressOption.schema.mof#L5)):*
> ```
> {
>     [Key, Description("The target IP address, must already be configured on the system.")] string IPAddress;
>     [Write, Description("Skip as source option of the ip address."),ValueMap{"True", "False"},Values{"True", "False"}] string SkipAsSource;
> ```

Nitpick: You could have used a Boolean parameter type for this instead of a string. Is it possible to change to Boolean type?

See: https://github.com/PowerShell/xNetworking/blob/dev/Modules/xNetworking/DSCResources/MSFT_xFirewall/MSFT_xFirewall.schema.mof#L32

---

*[Modules/xNetworking/DSCResources/MSFT_xIPAddressOption/README.MD, line 4 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/285#-KzB3Wwqiwl_XT74HQzT:-KzB3WwrxSwm6l-zCt3A:b-a8h566) ([raw file](https://github.com/powershell/xnetworking/blob/896dc4758a0b83cc5385fa4223f52bad56347ba2/Modules/xNetworking/DSCResources/MSFT_xIPAddressOption/README.MD#L4)):*
> ```
> 
> This resource is used to control a node's IP address options. This can be used
> to enable or disable the SkipAsSource option if an IP address.
> ```

Change `if` to `of`.

---

*[Modules/xNetworking/DSCResources/MSFT_xIPAddressOption/README.MD, line 6 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/285#-KzB3cy6vzKepXmIXj7Z:-KzB3cy6vzKepXmIXj7_:b-9xz93u) ([raw file](https://github.com/powershell/xnetworking/blob/896dc4758a0b83cc5385fa4223f52bad56347ba2/Modules/xNetworking/DSCResources/MSFT_xIPAddressOption/README.MD#L6)):*
> ```
> to enable or disable the SkipAsSource option if an IP address.
> 
> This resource is an addition resource compared to xIPAddress, because with
> ```

Perhaps this could read something like:
This resource is used in addition to xIPAddress to set the SkipAsSource for a
single IP address when an adapter has more than one address assigned. When using
this resource it allows the options of a single IP address to be set.

---

*[Modules/xNetworking/DSCResources/MSFT_xIPAddressOption/en-US/MSFT_xIPAddressOption.strings.psd1, line 4 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/285#-KzB47H_G9n7RfITRz-s:-KzB47H_G9n7RfITRz-t:b55wzdx) ([raw file](https://github.com/powershell/xnetworking/blob/896dc4758a0b83cc5385fa4223f52bad56347ba2/Modules/xNetworking/DSCResources/MSFT_xIPAddressOption/en-US/MSFT_xIPAddressOption.strings.psd1#L4)):*
> ```PowerShell
> 
> ConvertFrom-StringData @'
>     GettingIPAddressOptionMessage = Getting the IP Address Options.
> ```

Is it possible just for clarity to include the IP address of the one being retrieved in this message?

---

*[Modules/xNetworking/DSCResources/MSFT_xIPAddressOption/en-US/MSFT_xIPAddressOption.strings.psd1, line 5 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/285#-KzB4GoNo4T_WuZGXLDf:-KzB4GoNo4T_WuZGXLDg:b-b5b4ze) ([raw file](https://github.com/powershell/xnetworking/blob/896dc4758a0b83cc5385fa4223f52bad56347ba2/Modules/xNetworking/DSCResources/MSFT_xIPAddressOption/en-US/MSFT_xIPAddressOption.strings.psd1#L5)):*
> ```PowerShell
> ConvertFrom-StringData @'
>     GettingIPAddressOptionMessage = Getting the IP Address Options.
>     ApplyingIPAddressOptionMessage = Applying the IP Address Options.
> ```

Is it possible just for clarity to include the IP address of the one being set as well as what it is being set to in this message?

---

*[Modules/xNetworking/DSCResources/MSFT_xIPAddressOption/en-US/MSFT_xIPAddressOption.strings.psd1, line 6 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/285#-KzB4FiPMn5IIrmg0L2V:-KzB4FiPMn5IIrmg0L2W:b9uoctc) ([raw file](https://github.com/powershell/xnetworking/blob/896dc4758a0b83cc5385fa4223f52bad56347ba2/Modules/xNetworking/DSCResources/MSFT_xIPAddressOption/en-US/MSFT_xIPAddressOption.strings.psd1#L6)):*
> ```PowerShell
>     GettingIPAddressOptionMessage = Getting the IP Address Options.
>     ApplyingIPAddressOptionMessage = Applying the IP Address Options.
>     CheckingIPAddressOptionMessage = Checking the IP Address Options.
> ```

Is it possible just for clarity to include the IP address of the one being tested in this message?

---

*[Tests/Unit/MSFT_xIPAddressOption.Tests.ps1, line 39 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/285#-KzB4f7tLdBKWNbNBLoN:-KzB4f7tLdBKWNbNBLoO:b-749uj6) ([raw file](https://github.com/powershell/xnetworking/blob/896dc4758a0b83cc5385fa4223f52bad56347ba2/Tests/Unit/MSFT_xIPAddressOption.Tests.ps1#L39)):*
> ```PowerShell
>                         SkipAsSource   = $true
>                     }
>                 }
> ```

Please add blank line here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/285#-:-KzB4rhQZx9ABD15dbKE:b8m3a4g)*

**Comment by claudiospizzi** [comment]
I somehow forgot, that boolean is a valid type in the mof schema specification. Thanks for this feedback, I've change the SkipAsSource type to boolean and fixed the other review issues.

**Comment by PlagueHO** [comment]
No worries @claudiospizzi - really appreciate your work on this and the contribution! Let me know when you're ready for me to review.

**Comment by claudiospizzi** [comment]
@PlagueHO I'm ready - you can review the PR.

**Comment by PlagueHO** [comment]
Doh! Sorry about that @claudiospizzi - I missed your commits! Anyway, really fantastic job and all your work is really appreciated!

:lgtm: 

---

Reviewed 8 of 8 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/285#-:-L-wsU-rQoUMWD2oJulD:b674tkf)*

**Pull request merged**
