### PR TITLE
Fixed bug with better handling of duplicate entries

### LINKED ISSUE #119: xHostFile doesn't update existing entries correctly
**Observed behavior**
Create a xHostFile resource that sets a specific value and it applies correctly, but then if I update the resource to change the IP address I see it create a new entry for the same domain name, meaning it is in the host file twice with both the old and new IP addresses, and as the old one is most likely to appear first the change does not apply.

**Expected behavior**
The previous entry should be removed so that a host name only appears once in the host file

**Software versions**
Windows Server 2012 R2, WMF5, xNetworking 2.8.0.0

**Notes on a fix**
A little while back I wrote a host file entry resource (I wasn't aware there was one in this repo) that worked correctly and was dramatically less code as it didn't try to compress all the host entries on to a single line for each IP address like this resource does, the code for this is in [my xComputerManagement repo](https://github.com/BrianFarnhill/xComputerManagement/tree/feature-xhostfileentry). If you guys want I can open a PR to bring that logic in to this resource - or you can look at fixing the issue in the existing logic if thats the preferred approach. Just let me know if you want my code and I'll get that moving.

### PR DESCRIPTION
**Pull request by BrianFarnhill**
Fixes #119 

This code base is based on a re-write that I did to simplify the code in this resource, and it fixes a bug where entries would duplicate if you tried to update a host file entry. I did extend my code to support localisation the same as the previous resource, and also to account for host file entries that could share multiple hosts on a single line, or one per line. I put some tests in to account for those scenarios as well. 

Lastly I also included the launch.json file so the tests could be easily run from VS Code as well for development testing.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xnetworking/125)

### CODE REVIEW

**Comment by BrianFarnhill** [comment]
Not sure what went wrong with the build there - looks like Pester failed to install? Might need to manually trigger that one again.

**Comment by PlagueHO** [comment]
@TravisEz13, are you able to trigger AppVeyor to rebuild this? AppVeyor broke again for no reason.

**Comment by PlagueHO** [comment]
Do you think it would be possible to add integration tests for this? It seems like it might be a resource that we could do this for.

Sorry about all the nitpicks :smile:

---

Reviewed 3 of 5 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1, line 4 \[r2\]](https://reviewable.io:443/reviews/powershell/xnetworking/125#-KKrCVtKzb6oTV39AM2o:-KKrCVtKzb6oTV39AM2p:1798514905) ([raw file](https://github.com/powershell/xnetworking/blob/3bd0f03f929eefc7cd410c09d059e704a580ae46/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1#L4)):*
> ```PowerShell
> if (Test-Path "${PSScriptRoot}\${PSUICulture}")
> {
>     Import-LocalizedData -BindingVariable LocalizedData -filename MSFT_xHostsFile.psd1 -BaseDirectory "${PSScriptRoot}\${PSUICulture}"
> ```

Sorry to be a PITA, are you able to get this line down to under 100 chars?

---

*[DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1, line 9 \[r2\]](https://reviewable.io:443/reviews/powershell/xnetworking/125#-KKrCeCQ0qm6YtBhvcLf:-KKrCeCQ0qm6YtBhvcLg:1377318206) ([raw file](https://github.com/powershell/xnetworking/blob/3bd0f03f929eefc7cd410c09d059e704a580ae46/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1#L9)):*
> ```PowerShell
> {
>     #fallback to en-US
>     Import-LocalizedData -BindingVariable LocalizedData -filename MSFT_xHostsFile.psd1 -BaseDirectory "${PSScriptRoot}\en-US"
> ```

This line needs to come down to 100 chars too :smile:

---

*[DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1, line 32 \[r2\]](https://reviewable.io:443/reviews/powershell/xnetworking/125#-KKrCshYTt5EjDYll9GH:-KKrCshYTt5EjDYll9GI:-1968848846) ([raw file](https://github.com/powershell/xnetworking/blob/3bd0f03f929eefc7cd410c09d059e704a580ae46/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1#L32)):*
> ```PowerShell
>     )
> 
>     Write-Verbose ($LocalizedData.StartingGet -f $HostName)
> ```

Can you change this to use a named parameter?

---

*[DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1, line 34 \[r2\]](https://reviewable.io:443/reviews/powershell/xnetworking/125#-KKrD5sk-cBSz1Z84pw_:-KKrD5sk-cBSz1Z84pwa:-1968848846) ([raw file](https://github.com/powershell/xnetworking/blob/3bd0f03f929eefc7cd410c09d059e704a580ae46/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1#L34)):*
> ```PowerShell
>     Write-Verbose ($LocalizedData.StartingGet -f $HostName)
> 
>     $hosts = Get-Content "$env:windir\System32\drivers\etc\hosts"
> ```

Can you change this to use a named parameter?

---

*[DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1, line 43 \[r2\]](https://reviewable.io:443/reviews/powershell/xnetworking/125#-KKrDFEhavCj8IFCMiLf:-KKrDFEhavCj8IFCMiLg:1870096929) ([raw file](https://github.com/powershell/xnetworking/blob/3bd0f03f929eefc7cd410c09d059e704a580ae46/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1#L43)):*
> ```PowerShell
>                     # Account for host entries that have multiple entries on a single line
>                     $result = @()
>                     for ($i = 1; $i -lt $data.Length; $i++) {
> ```

Move open brace to next line :smile:

---

*[DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1, line 62 \[r2\]](https://reviewable.io:443/reviews/powershell/xnetworking/125#-KKrDkjn0Uy2umFwzXKj:-KKrDkjn0Uy2umFwzXKk:714707360) ([raw file](https://github.com/powershell/xnetworking/blob/3bd0f03f929eefc7cd410c09d059e704a580ae46/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1#L62)):*
> ```PowerShell
>     $hostEntry = $allHosts | Where-Object { $_.Host -eq $HostName }
>     
>     if ($hostEntry -eq $null) 
> ```

Can you put the $null on the left hand side of the -eq (PSSA will moan about it).

---

*[DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1, line 99 \[r2\]](https://reviewable.io:443/reviews/powershell/xnetworking/125#-KKrDvYf5b45aOciPnm5:-KKrDvYf5b45aOciPnm6:-221937906) ([raw file](https://github.com/powershell/xnetworking/blob/3bd0f03f929eefc7cd410c09d059e704a580ae46/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1#L99)):*
> ```PowerShell
>     $currentValues = Get-TargetResource @PSBoundParameters
>     
>     Write-Verbose ($LocalizedData.StartingSet -f $HostName)
> ```

Change to named parameter please :smile:

---

*[DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1, line 103 \[r2\]](https://reviewable.io:443/reviews/powershell/xnetworking/125#-KKrE1gDNWCEj0q5ED1M:-KKrE1gDNWCEj0q5ED1N:710782295) ([raw file](https://github.com/powershell/xnetworking/blob/3bd0f03f929eefc7cd410c09d059e704a580ae46/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1#L103)):*
> ```PowerShell
>     if ($Ensure -eq "Present" -and $PSBoundParameters.ContainsKey("IPAddress") -eq $false) 
>     {
>         throw $LocalizedData.UnableToEnsureWithoutIP
> ```

Rather than just throw an exception, can we change this to throw a custom exception like this: https://github.com/PowerShell/xNetworking/blob/dev/DSCResources/MSFT_xDNSServerAddress/MSFT_xDNSServerAddress.psm1#L259

This enables us to add unit tests to test for a specific error.

---

*[DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1, line 110 \[r2\]](https://reviewable.io:443/reviews/powershell/xnetworking/125#-KKrESAwn1xuGnZqOuII:-KKrESAxGJfvVICjvFy9:-508990407) ([raw file](https://github.com/powershell/xnetworking/blob/3bd0f03f929eefc7cd410c09d059e704a580ae46/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1#L110)):*
> ```PowerShell
>     {
>         Write-Verbose -Message ($LocalizedData.CreateNewEntry -f $HostName)
>         Add-Content "$env:windir\System32\drivers\etc\hosts" "`r`n$IPAddress`t$HostName"
> ```

Can we change these to Named parameters?

---

*[DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1, line 114 \[r2\]](https://reviewable.io:443/reviews/powershell/xnetworking/125#-KKrEVJ8IQpUy7TUGxFI:-KKrEVJ8IQpUy7TUGxFJ:1827020186) ([raw file](https://github.com/powershell/xnetworking/blob/3bd0f03f929eefc7cd410c09d059e704a580ae46/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1#L114)):*
> ```PowerShell
>     else 
>     {
>         $hosts = Get-Content "$env:windir\System32\drivers\etc\hosts"
> ```

Need to be named parameters :smile:

---

*[DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1, line 153 \[r2\]](https://reviewable.io:443/reviews/powershell/xnetworking/125#-KKrFx0hbYeMHPWIT9aX:-KKrFx0ihQjoni-gsDu-:-1738842138) ([raw file](https://github.com/powershell/xnetworking/blob/3bd0f03f929eefc7cd410c09d059e704a580ae46/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1#L153)):*
> ```PowerShell
>             }
>         }
>         $hosts | Set-Content "$env:windir\System32\drivers\etc\hosts"
> ```

Can we change to named parameter please :smile:

---

*[DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1, line 176 \[r2\]](https://reviewable.io:443/reviews/powershell/xnetworking/125#-KKrJLePPbKTH61yqXUA:-KKrJLePPbKTH61yqXUB:702577155) ([raw file](https://github.com/powershell/xnetworking/blob/3bd0f03f929eefc7cd410c09d059e704a580ae46/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1#L176)):*
> ```PowerShell
>     
>     $currentValues = Get-TargetResource @PSBoundParameters
>     Write-Verbose ($LocalizedData.StartingTest -f $HostName)
> ```

Named parameter here please :smile:

---

*[Tests/Unit/MSFT_xHostsFile.Tests.ps1, line 25 \[r2\]](https://reviewable.io:443/reviews/powershell/xnetworking/125#-KKrGKUn66LSmTnGpIkW:-KKrGKUn66LSmTnGpIkX:-405246564) ([raw file](https://github.com/powershell/xnetworking/blob/3bd0f03f929eefc7cd410c09d059e704a580ae46/Tests/Unit/MSFT_xHostsFile.Tests.ps1#L25)):*
> ```PowerShell
>     #region Pester Tests
> 
>     InModuleScope $Global:DSCResourceName {
> ```

Any chance we can remove the InModuleScope as it should no longer be needed for testing the public *-TargetResources?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/125#-:-KKrH5hZAp2yqp4-E6GQ:993938344)*

**Comment by BrianFarnhill** [comment]
I'll have a look at the integration tests and see what I can do with it. Should just be able to take a backup of the hosts file and restore it at the end of the tests. Other feedback items are done/discussed below though. 

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1, line 4 \[r2\]](https://reviewable.io:443/reviews/powershell/xnetworking/125#-KKrCVtKzb6oTV39AM2o:-KKu_mE8NWny2F4r3vw5:-499146009) ([raw file](https://github.com/powershell/xnetworking/blob/3bd0f03f929eefc7cd410c09d059e704a580ae46/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1#L4)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> Sorry to be a PITA, are you able to get this line down to under 100 chars?
</details>
Done.

---

*[DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1, line 9 \[r2\]](https://reviewable.io:443/reviews/powershell/xnetworking/125#-KKrCeCQ0qm6YtBhvcLf:-KKu_n7wIvcEVR6BcSES:-499146009) ([raw file](https://github.com/powershell/xnetworking/blob/3bd0f03f929eefc7cd410c09d059e704a580ae46/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1#L9)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> This line needs to come down to 100 chars too :smile:
</details>
Done.

---

*[DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1, line 32 \[r2\]](https://reviewable.io:443/reviews/powershell/xnetworking/125#-KKrCshYTt5EjDYll9GH:-KKu_nxwJucw8Kb_Hf9e:-499146009) ([raw file](https://github.com/powershell/xnetworking/blob/3bd0f03f929eefc7cd410c09d059e704a580ae46/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1#L32)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> Can you change this to use a named parameter?
</details>
Done.

---

*[DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1, line 34 \[r2\]](https://reviewable.io:443/reviews/powershell/xnetworking/125#-KKrD5sk-cBSz1Z84pw_:-KKu_oabjcZ9KGRI8G52:-499146009) ([raw file](https://github.com/powershell/xnetworking/blob/3bd0f03f929eefc7cd410c09d059e704a580ae46/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1#L34)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> Can you change this to use a named parameter?
</details>
Done.

---

*[DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1, line 43 \[r2\]](https://reviewable.io:443/reviews/powershell/xnetworking/125#-KKrDFEhavCj8IFCMiLf:-KKu_pSqPVLffQOZDWJC:-499146009) ([raw file](https://github.com/powershell/xnetworking/blob/3bd0f03f929eefc7cd410c09d059e704a580ae46/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1#L43)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> Move open brace to next line :smile:
</details>
Done.

---

*[DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1, line 62 \[r2\]](https://reviewable.io:443/reviews/powershell/xnetworking/125#-KKrDkjn0Uy2umFwzXKj:-KKu_qE5HmXOWIxp9YSE:-499146009) ([raw file](https://github.com/powershell/xnetworking/blob/3bd0f03f929eefc7cd410c09d059e704a580ae46/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1#L62)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> Can you put the $null on the left hand side of the -eq (PSSA will moan about it).
</details>
Done.

---

*[DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1, line 99 \[r2\]](https://reviewable.io:443/reviews/powershell/xnetworking/125#-KKrDvYf5b45aOciPnm5:-KKu_rJV4x_YMWgYWEWj:-499146009) ([raw file](https://github.com/powershell/xnetworking/blob/3bd0f03f929eefc7cd410c09d059e704a580ae46/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1#L99)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> Change to named parameter please :smile:
</details>
Done.

---

*[DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1, line 103 \[r2\]](https://reviewable.io:443/reviews/powershell/xnetworking/125#-KKrE1gDNWCEj0q5ED1M:-KKu_sjUJ25i5uxwHt1G:-499146009) ([raw file](https://github.com/powershell/xnetworking/blob/3bd0f03f929eefc7cd410c09d059e704a580ae46/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1#L103)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> Rather than just throw an exception, can we change this to throw a custom exception like this: https://github.com/PowerShell/xNetworking/blob/dev/DSCResources/MSFT_xDNSServerAddress/MSFT_xDNSServerAddress.psm1#L259
> 
> This enables us to add unit tests to test for a specific error.
</details>
Done.

---

*[DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1, line 110 \[r2\]](https://reviewable.io:443/reviews/powershell/xnetworking/125#-KKrESAwn1xuGnZqOuII:-KKu_t_1K_YhWINwD0GJ:-499146009) ([raw file](https://github.com/powershell/xnetworking/blob/3bd0f03f929eefc7cd410c09d059e704a580ae46/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1#L110)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> Can we change these to Named parameters?
</details>
Done.

---

*[DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1, line 114 \[r2\]](https://reviewable.io:443/reviews/powershell/xnetworking/125#-KKrEVJ8IQpUy7TUGxFI:-KKu_u5FaTlhkGyHh8Kf:-499146009) ([raw file](https://github.com/powershell/xnetworking/blob/3bd0f03f929eefc7cd410c09d059e704a580ae46/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1#L114)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> Need to be named parameters :smile:
</details>
Done.

---

*[DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1, line 153 \[r2\]](https://reviewable.io:443/reviews/powershell/xnetworking/125#-KKrFx0hbYeMHPWIT9aX:-KKu_uol-CcsorvvPkSe:-499146009) ([raw file](https://github.com/powershell/xnetworking/blob/3bd0f03f929eefc7cd410c09d059e704a580ae46/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1#L153)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> Can we change to named parameter please :smile:
</details>
Done.

---

*[DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1, line 176 \[r2\]](https://reviewable.io:443/reviews/powershell/xnetworking/125#-KKrJLePPbKTH61yqXUA:-KKu_wW-jnDBmnoIEwkv:-499146009) ([raw file](https://github.com/powershell/xnetworking/blob/3bd0f03f929eefc7cd410c09d059e704a580ae46/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1#L176)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> Named parameter here please :smile:
</details>
Done.

---

*[Tests/Unit/MSFT_xHostsFile.Tests.ps1, line 25 \[r2\]](https://reviewable.io:443/reviews/powershell/xnetworking/125#-KKrGKUn66LSmTnGpIkW:-KKugHiRQF5IgySjcNV8:-1419429429) ([raw file](https://github.com/powershell/xnetworking/blob/3bd0f03f929eefc7cd410c09d059e704a580ae46/Tests/Unit/MSFT_xHostsFile.Tests.ps1#L25)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> Any chance we can remove the InModuleScope as it should no longer be needed for testing the public *-TargetResources?
</details>
It is actually still needed as that's how Pester knows which module it should mock the functions in. Without it I would need to put a -ModuleName parameter on to every mock statement, but while they are in the module scope this is automatically applied. I tested taking it out and as expected all the mocks didn't register because I didn't tell Pester which module they apply to. So I'm more inclined to leave this in based on what I've seen. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/125#-:-KKuYmlTOTK9KZ9Ti832:52054904)*

**Comment by BrianFarnhill** [comment]
@PlagueHO We do have the [integration tests that were there previously](https://ci.appveyor.com/project/PowerShell/xnetworking/build/2.9.312.0#L282) (I didn't touch them as they ran as is). Do we still need more in terms of integration testing or are we happy with that? 

---

Review status: all files reviewed at latest revision, 13 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/125#-:-KKuu9i02IrsGzllQwwX:-2119451529)*

**Comment by PlagueHO** [comment]
Oh doh! If the Integration tests are already there then I see no reason for creating them. I almost forgot that this isn't a new resource. Sorry about that!

@Tysonjhayes - I reckon this PR is all good to go and ready to merge!

---

Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[Tests/Unit/MSFT_xHostsFile.Tests.ps1, line 25 \[r2\]](https://reviewable.io:443/reviews/powershell/xnetworking/125#-KKrGKUn66LSmTnGpIkW:-KKw1by77GBV-s1JTcbi:1281004086) ([raw file](https://github.com/powershell/xnetworking/blob/3bd0f03f929eefc7cd410c09d059e704a580ae46/Tests/Unit/MSFT_xHostsFile.Tests.ps1#L25)):*
<details><summary><i>Previously, BrianFarnhill (Brian Farnhill) wrote…</i></summary>
> It is actually still needed as that's how Pester knows which module it should mock the functions in. Without it I would need to put a -ModuleName parameter on to every mock statement, but while they are in the module scope this is automatically applied. I tested taking it out and as expected all the mocks didn't register because I didn't tell Pester which module they apply to. So I'm more inclined to leave this in based on what I've seen. 
</details>
Personally, I'm OK with using InModuleScope, but it was something that was bought up a few months back (https://github.com/PowerShell/DscResources/issues/115). So it was made a "best-practice" to avoid the use of InModuleScope for the *-TargetResource functions. I won't hold this PR up though - I reckon it's all good to go!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/125#-:-KKw0u_WCk8MMSAC25pQ:851394976)*

**Comment by PlagueHO** [comment]
@BrianFarnhill - just waiting for you to sign off on the discussions so that this PR can be freed up for merge. Cheers

---

Review status: all files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/125#-:-KLcKsbIl5xH9KSL7hQQ:1709877073)*

**Comment by BrianFarnhill** [comment]
Reviewed 1 of 1 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/125)*

**Comment by PlagueHO** [comment]
:lgtm: @TysonjHayes ?

---

Reviewed 2 of 2 files at r3, 1 of 1 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/125#-:-KLu0_T_YiMlfj3W_-93:504260831)*

**Comment by PlagueHO** [comment]
@tysonjhayes  - any chance you would be able to give this a once over and merge it if you're happy?

**Pull request merged**
