### PR TITLE
MSFT_xDefaultGatewayAddress: Correct Style to meet HQRM and exceptions to use ResourceHelper functions - Fixes #221

### LINKED ISSUE #221: Convert xDefaultGatewayAddress to HQRM and convert Exceptions to use Common Code
Works on issues:
- #135
- #176

### PR DESCRIPTION
**Pull request by PlagueHO**
- MSFT_xDefaultGatewayAddress: 
 - Corrected style and formatting to meet HQRM guidelines.
  - Converted exceptions to use ResourceHelper functions.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xnetworking/222)

### CODE REVIEW

**Comment by PlagueHO** [comment]
@Johlju - any chance you'd feel like looking this one over when/if you have time? I'm just beginning the move to HQRM for this module and am doing these in resource sized chunks.

**Comment by johlju** [comment]
I will try to get to this tomorrow :)

**Comment by tysonjhayes** [comment]
:lgtm:

---

Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/222#-:-KooA3TsFYhIlZfO73DF:bnfp4nl)*

**Comment by PlagueHO** [comment]
Awesome! Thanks @tysonjhayes - are you able to sign off the last file for me? I made a change at exactly the time you were reviewing (adding the Dev/Master branch badges and cleaning up the unit tests so that they run out of order). Sorry mate!

**Comment by tysonjhayes** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/222)*

**Comment by johlju** [comment]
@PlagueHO When I browsed this code yesterday, I saw this parameter was missing [Parameter()]. Thought I comment on it today when I reviewed. But you can just change that in some other PR ;) https://github.com/PlagueHO/xNetworking/blob/eeb4abb17bcb90f258804dcc51afe3ac3de6a906/Modules/xNetworking/DSCResources/MSFT_xDefaultGatewayAddress/MSFT_xDefaultGatewayAddress.psm1#L300

**Comment by PlagueHO** [comment]
Good catch @johlju - I've slipped it in with #225

**Pull request merged**
