### PR TITLE
Corrected style and formatting to meet HQRM guidelines - Fixes #268

### LINKED ISSUE #268: Convert xHostsFile to HQRM and convert Exceptions to use Common Code
Work on issues:

- #135 
- #176

### PR DESCRIPTION
**Pull request by PlagueHO**
**Pull Request (PR) description**
Corrected style and formatting to meet HQRM guidelines.

**This Pull Request (PR) fixes the following issues:**
#268

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [x] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [x] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xnetworking/269)

### CODE REVIEW

**Comment by PlagueHO** [comment]
@Johlju - would you mind reviewing this if you get a chance? No rush or urgency - just whenever!

**Comment by johlju** [comment]
Reviewed 8 of 9 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[Modules/xNetworking/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1, line 46 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/269#-KuhbpDQVWksqLpKvrox:-KuhbpDQVWksqLpKvroy:byl5xk9) ([raw file](https://github.com/powershell/xnetworking/blob/9d50525bac7aa8260c75ef34798577f899b4eb08/Modules/xNetworking/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1#L46)):*
> ```PowerShell
> 
>         [Parameter()]
>         [ValidateSet("Present", "Absent")]
> ```

single quote

---

*[Modules/xNetworking/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1, line 48 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/269#-KuhbsD1XrqJKSbXoQ3m:-KuhbsD1XrqJKSbXoQ3n:byl5xk9) ([raw file](https://github.com/powershell/xnetworking/blob/9d50525bac7aa8260c75ef34798577f899b4eb08/Modules/xNetworking/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1#L48)):*
> ```PowerShell
>         [ValidateSet("Present", "Absent")]
>         [System.String]
>         $Ensure = "Present"
> ```

single quote

---

*[Modules/xNetworking/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1, line 60 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/269#-KuhbtEkvL1gTRukNOuk:-KuhbtEkvL1gTRukNOul:byl5xk9) ([raw file](https://github.com/powershell/xnetworking/blob/9d50525bac7aa8260c75ef34798577f899b4eb08/Modules/xNetworking/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1#L60)):*
> ```PowerShell
>             HostName  = $result.HostName
>             IPAddress = $result.IPAddress
>             Ensure    = "Present"
> ```

single quote

---

*[Modules/xNetworking/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1, line 68 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/269#-KuhbtrdoKNxZDEBQStg:-KuhbtrdoKNxZDEBQSth:byl5xk9) ([raw file](https://github.com/powershell/xnetworking/blob/9d50525bac7aa8260c75ef34798577f899b4eb08/Modules/xNetworking/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1#L68)):*
> ```PowerShell
>             HostName  = $HostName
>             IPAddress = $null
>             Ensure    = "Absent"
> ```

single quote

---

*[Modules/xNetworking/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1, line 126 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/269#-Kuhbfktp-Qm7fGAEei7:-Kuhbfktp-Qm7fGAEei8:bbcf7ok) ([raw file](https://github.com/powershell/xnetworking/blob/9d50525bac7aa8260c75ef34798577f899b4eb08/Modules/xNetworking/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1#L126)):*
> "*$HostName*"

single quote

---

*[Modules/xNetworking/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1, line 213 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/269#-KuhcF-b8tbnJVvpdAnD:-KuhcF-b8tbnJVvpdAnE:byl5xk9) ([raw file](https://github.com/powershell/xnetworking/blob/9d50525bac7aa8260c75ef34798577f899b4eb08/Modules/xNetworking/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1#L213)):*
> ```PowerShell
>     }
> 
>     if ($Ensure -eq "Present" -and $IPAddress -ne $currentValues.IPAddress)
> ```

single quote

---

*[Tests/Integration/MSFT_xHostsFile.Integration.Tests.ps1, line 57 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/269#-KuhccX_HtgfTJbJIWtG:-KuhccX_HtgfTJbJIWtH:b-leuvbu) ([raw file](https://github.com/powershell/xnetworking/blob/9d50525bac7aa8260c75ef34798577f899b4eb08/Tests/Integration/MSFT_xHostsFile.Integration.Tests.ps1#L57)):*
> ```PowerShell
> 
>         It 'Should have set the resource and all the parameters should match' {
>             $result = Get-DscConfiguration | Where-Object -FilterScript { $_.ConfigurationName -eq "$($script:DSCResourceName)_Config" }
> ```

I would rather not have the braces on the same line. Throughout.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/269)*

**Comment by PlagueHO** [comment]
Thanks for reviewing @Johlju - all changes made.

---

Review status: 7 of 9 files reviewed at latest revision, 7 unresolved discussions.

---

*[Modules/xNetworking/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1, line 46 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/269#-KuhbpDQVWksqLpKvrox:-KuiGAAsBbwLtz-bK8uj:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/9d50525bac7aa8260c75ef34798577f899b4eb08/Modules/xNetworking/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1#L46)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

single quote
</blockquote></details>

Done.

---

*[Modules/xNetworking/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1, line 48 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/269#-KuhbsD1XrqJKSbXoQ3m:-KuiGJmPQCrxIdKukLy6:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/9d50525bac7aa8260c75ef34798577f899b4eb08/Modules/xNetworking/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1#L48)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

single quote
</blockquote></details>

Done.

---

*[Modules/xNetworking/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1, line 60 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/269#-KuhbtEkvL1gTRukNOuk:-KuiGKYAj0uCei8YmOZG:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/9d50525bac7aa8260c75ef34798577f899b4eb08/Modules/xNetworking/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1#L60)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

single quote
</blockquote></details>

Done.

---

*[Modules/xNetworking/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1, line 68 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/269#-KuhbtrdoKNxZDEBQStg:-KuiGL6xCgjhbPlmDoRq:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/9d50525bac7aa8260c75ef34798577f899b4eb08/Modules/xNetworking/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1#L68)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

single quote
</blockquote></details>

Done.

---

*[Modules/xNetworking/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1, line 126 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/269#-Kuhbfktp-Qm7fGAEei7:-KuiGPkfLSddtEKQ30Vb:b4qifsv) ([raw file](https://github.com/powershell/xnetworking/blob/9d50525bac7aa8260c75ef34798577f899b4eb08/Modules/xNetworking/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1#L126)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> "*$HostName*"

single quote
</blockquote></details>

I think this one needs to stay double quotes.

---

*[Modules/xNetworking/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1, line 213 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/269#-KuhcF-b8tbnJVvpdAnD:-KuiGVFDOOqRvbBdIYqZ:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/9d50525bac7aa8260c75ef34798577f899b4eb08/Modules/xNetworking/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1#L213)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

single quote
</blockquote></details>

Done.

---

*[Tests/Integration/MSFT_xHostsFile.Integration.Tests.ps1, line 57 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/269#-KuhccX_HtgfTJbJIWtG:-KuiGjrYnriAHD2c70_C:b-896fix) ([raw file](https://github.com/powershell/xnetworking/blob/9d50525bac7aa8260c75ef34798577f899b4eb08/Tests/Integration/MSFT_xHostsFile.Integration.Tests.ps1#L57)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

I would rather not have the braces on the same line. Throughout.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/269#-:-KuiGs1IYzP3knw8iq-R:bud0uzj)*

**Comment by johlju** [comment]
:lgtm:

Sorry for not acknowledge this one sooner. Was not able to squeezing in DSC during the long travel to Orlando. :) 

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Modules/xNetworking/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1, line 126 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/269#-Kuhbfktp-Qm7fGAEei7:-KuooSWwTK8PHBFHdE1O:b15oze2) ([raw file](https://github.com/powershell/xnetworking/blob/9d50525bac7aa8260c75ef34798577f899b4eb08/Modules/xNetworking/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1#L126)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

I think this one needs to stay double quotes.
</blockquote></details>

Yeah right. My bad. All good. Non-blocking. Please acknowledge it (if possible).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/269#-:-KuooliWJ6L4KzGEj9-X:boinxss)*

**Comment by PlagueHO** [comment]
No problem at all - I'm just lucky to get a review :grin: Hope the jetlag is not too bad an Ignite is awesome! Very jealous! :grin:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[Modules/xNetworking/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1, line 126 at r2](https://reviewable.io:443/reviews/powershell/xnetworking/269#-Kuhbfktp-Qm7fGAEei7:-KurUlWceh7wEc1DLH8N:b-9kvx0s) ([raw file](https://github.com/powershell/xnetworking/blob/9d50525bac7aa8260c75ef34798577f899b4eb08/Modules/xNetworking/DSCResources/MSFT_xHostsFile/MSFT_xHostsFile.psm1#L126)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Yeah right. My bad. All good. Non-blocking. Please acknowledge it (if possible).
</blockquote></details>

No worries! :grin:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/269#-:-KurUpQ2Zkf0KRHN_nEG:bflx26q)*

**Pull request merged**
