### PR TITLE
Added xDnsClientGlobalSetting Resource - Fixes #111

### LINKED ISSUE #111: [New Resource] DNSGlobalSuffixSearchList
This would mainly be used to set the "Primary DNS Suffix of this computer":

The cmdlets ```get-dnsclientglobalsetting``` and ```set-dnsclientglobalsetting``` could be used to set this value.

The resource would be quite similar to the xNetBIOS resource I would think.

### PR DESCRIPTION
**Pull request by PlagueHO**
This adds support for setting the DNS client global suffix search list (and devolution level) as per #111.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xnetworking/129)

### CODE REVIEW

**Comment by PlagueHO** [comment]
@tysonjhayes  - any chance I could get you to do a code review for me? :smile:

**Comment by tysonjhayes** [comment]
Reviewed 7 of 8 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Tests/Integration/MSFT_xDnsClientGlobalSetting.Integration.Tests.ps1, line 21 \[r2\]](https://reviewable.io:443/reviews/powershell/xnetworking/129#-KNJIi2tKQ96343gIIQy:-KNJIi2tKQ96343gIIQz:1709221382) ([raw file](https://github.com/powershell/xnetworking/blob/d8fd31ff0bb3ab140951c45b3faed9961a933b23/Tests/Integration/MSFT_xDnsClientGlobalSetting.Integration.Tests.ps1#L21)):*
> ```PowerShell
> 
> # Backup the existing settings
> $CurrentDnsClientGlobalSetting = Get-DnsClientGlobalSetting
> ```

Shouldn't we move this into the try catch so if this or the set fails we try to roll back?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/129)*

**Comment by PlagueHO** [comment]
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[Tests/Integration/MSFT_xDnsClientGlobalSetting.Integration.Tests.ps1, line 21 \[r2\]](https://reviewable.io:443/reviews/powershell/xnetworking/129#-KNJIi2tKQ96343gIIQy:-KNL-NOO2mSJeyubY78W:-1555013996) ([raw file](https://github.com/powershell/xnetworking/blob/d8fd31ff0bb3ab140951c45b3faed9961a933b23/Tests/Integration/MSFT_xDnsClientGlobalSetting.Integration.Tests.ps1#L21)):*
<details><summary><i>Previously, tysonjhayes (Tyson J. Hayes) wrote…</i></summary>
> Shouldn't we move this into the try catch so if this or the set fails we try to roll back?
</details>
Good catch as always sir! Cheers! Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/129)*

**Comment by PlagueHO** [comment]
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[Tests/Integration/MSFT_xDnsClientGlobalSetting.Integration.Tests.ps1, line 21 \[r2\]](https://reviewable.io:443/reviews/powershell/xnetworking/129#-KNJIi2tKQ96343gIIQy:-KNL-WRPiwtlEgzfUTX9:-499146009) ([raw file](https://github.com/powershell/xnetworking/blob/d8fd31ff0bb3ab140951c45b3faed9961a933b23/Tests/Integration/MSFT_xDnsClientGlobalSetting.Integration.Tests.ps1#L21)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> Good catch as always sir! Cheers! Fixed.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/129)*

**Comment by tysonjhayes** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xnetworking/129#-:-KNi0krv4fy3lafEqk_O:1417088721)*

**Pull request merged**
